

import 'package:bldrs/view_brains/theme/flagz.dart';

var countriesList = [
  {"countryName" : "Afghanistan", "countryFlag" : Flagz.Afghanistan,},
  {"countryName" : "Aland Islands", "countryFlag" : Flagz.Aland_Islands,},
  {"countryName" : "Albania", "countryFlag" : Flagz.Albania,},
  {"countryName" : "Algeria", "countryFlag" : Flagz.Algeria,},
  {"countryName" : "American Samoa", "countryFlag" : Flagz.American_Samoa,},
  {"countryName" : "Andorra", "countryFlag" : Flagz.Andorra,},
  {"countryName" : "Angola", "countryFlag" : Flagz.Angola,},
  {"countryName" : "Anguilla", "countryFlag" : Flagz.Anguilla,},
  {"countryName" : "Antigua And Barbuda", "countryFlag" : Flagz.Antigua_And_Barbuda,},
  {"countryName" : "Argentina", "countryFlag" : Flagz.Argentina,},
  {"countryName" : "Armenia", "countryFlag" : Flagz.Armenia,},
  {"countryName" : "Aruba", "countryFlag" : Flagz.Aruba,},
  {"countryName" : "Australia", "countryFlag" : Flagz.Australia,},
  {"countryName" : "Austria", "countryFlag" : Flagz.Austria,},
  {"countryName" : "Azerbaijan", "countryFlag" : Flagz.Azerbaijan,},
  {"countryName" : "Bahamas", "countryFlag" : Flagz.Bahamas,},
  {"countryName" : "Bahrain", "countryFlag" : Flagz.Bahrain,},
  {"countryName" : "Bangladesh", "countryFlag" : Flagz.Bangladesh,},
  {"countryName" : "Barbados", "countryFlag" : Flagz.Barbados,},
  {"countryName" : "Belarus", "countryFlag" : Flagz.Belarus,},
  {"countryName" : "Belgium", "countryFlag" : Flagz.Belgium,},
  {"countryName" : "Belize", "countryFlag" : Flagz.Belize,},
  {"countryName" : "Benin", "countryFlag" : Flagz.Benin,},
  {"countryName" : "Bermuda", "countryFlag" : Flagz.Bermuda,},
  {"countryName" : "Bhutan", "countryFlag" : Flagz.Bhutan,},
  {"countryName" : "Bolivia", "countryFlag" : Flagz.Bolivia,},
  {"countryName" : "Bonaire", "countryFlag" : Flagz.Bonaire,},
  {"countryName" : "Bosnia And Herzegovina", "countryFlag" : Flagz.Bosnia_And_Herzegovina,},
  {"countryName" : "Botswana", "countryFlag" : Flagz.Botswana,},
  {"countryName" : "Brazil", "countryFlag" : Flagz.Brazil,},
  {"countryName" : "British Indian Ocean Territory", "countryFlag" : Flagz.British_Indian_Ocean_Territory,},
  {"countryName" : "British Virgin Islands", "countryFlag" : Flagz.British_Virgin_Islands,},
  {"countryName" : "Brunei", "countryFlag" : Flagz.Brunei,},
  {"countryName" : "Bulgaria", "countryFlag" : Flagz.Bulgaria,},
  {"countryName" : "Burkina Faso", "countryFlag" : Flagz.Burkina_Faso,},
  {"countryName" : "Burundi", "countryFlag" : Flagz.Burundi,},
  {"countryName" : "Cambodia", "countryFlag" : Flagz.Cambodia,},
  {"countryName" : "Cameroon", "countryFlag" : Flagz.Cameroon,},
  {"countryName" : "Canada", "countryFlag" : Flagz.Canada,},
  {"countryName" : "Cape Verde", "countryFlag" : Flagz.Cape_Verde,},
  {"countryName" : "Cayman Islands", "countryFlag" : Flagz.Cayman_Islands,},
  {"countryName" : "Central African Republic", "countryFlag" : Flagz.Central_African_Republic,},
  {"countryName" : "Chad", "countryFlag" : Flagz.Chad,},
  {"countryName" : "Chile", "countryFlag" : Flagz.Chile,},
  {"countryName" : "China", "countryFlag" : Flagz.China,},
  {"countryName" : "Christmas Island", "countryFlag" : Flagz.Christmas_Island,},
  {"countryName" : "Cocos Island", "countryFlag" : Flagz.Cocos_Island,},
  {"countryName" : "Colombia", "countryFlag" : Flagz.Colombia,},
  {"countryName" : "Comoros", "countryFlag" : Flagz.Comoros,},
  {"countryName" : "Congo", "countryFlag" : Flagz.Congo,},
  {"countryName" : "Congo2", "countryFlag" : Flagz.Congo2,},
  {"countryName" : "Cook Islands", "countryFlag" : Flagz.Cook_Islands,},
  {"countryName" : "Costa Rica", "countryFlag" : Flagz.Costa_Rica,},
  {"countryName" : "Cote Divoire", "countryFlag" : Flagz.Cote_Divoire,},
  {"countryName" : "Croatia", "countryFlag" : Flagz.Croatia,},
  {"countryName" : "Cuba", "countryFlag" : Flagz.Cuba,},
  {"countryName" : "Curacao", "countryFlag" : Flagz.Curacao,},
  {"countryName" : "Cyprus", "countryFlag" : Flagz.Cyprus,},
  {"countryName" : "Czech Republic", "countryFlag" : Flagz.Czech_Republic,},
  {"countryName" : "Denmark", "countryFlag" : Flagz.Denmark,},
  {"countryName" : "Djibouti", "countryFlag" : Flagz.Djibouti,},
  {"countryName" : "Dominica", "countryFlag" : Flagz.Dominica,},
  {"countryName" : "Dominican Republic", "countryFlag" : Flagz.Dominican_Republic,},
  {"countryName" : "Ecuador", "countryFlag" : Flagz.Ecuador,},
  {"countryName" : "Egypt", "countryFlag" : Flagz.Egypt,},
  {"countryName" : "El Salvador", "countryFlag" : Flagz.El_Salvador,},
  {"countryName" : "England", "countryFlag" : Flagz.England,},
  {"countryName" : "Equatorial Guinea", "countryFlag" : Flagz.Equatorial_Guinea,},
  {"countryName" : "Eritrea", "countryFlag" : Flagz.Eritrea,},
  {"countryName" : "Estonia", "countryFlag" : Flagz.Estonia,},
  {"countryName" : "Ethiopia", "countryFlag" : Flagz.Ethiopia,},
  {"countryName" : "Falkland Islands", "countryFlag" : Flagz.Falkland_Islands,},
  {"countryName" : "Faroe Islands", "countryFlag" : Flagz.Faroe_Islands,},
  {"countryName" : "Fiji", "countryFlag" : Flagz.Fiji,},
  {"countryName" : "Finland", "countryFlag" : Flagz.Finland,},
  {"countryName" : "France", "countryFlag" : Flagz.France,},
  {"countryName" : "French Guiana", "countryFlag" : Flagz.French_Guiana,},
  {"countryName" : "French Polynesia", "countryFlag" : Flagz.French_Polynesia,},
  {"countryName" : "Gabon", "countryFlag" : Flagz.Gabon,},
  {"countryName" : "Gambia", "countryFlag" : Flagz.Gambia,},
  {"countryName" : "Georgia", "countryFlag" : Flagz.Georgia,},
  {"countryName" : "Germany", "countryFlag" : Flagz.Germany,},
  {"countryName" : "Ghana", "countryFlag" : Flagz.Ghana,},
  {"countryName" : "Gibraltar", "countryFlag" : Flagz.Gibraltar,},
  {"countryName" : "Greece", "countryFlag" : Flagz.Greece,},
  {"countryName" : "Greenland", "countryFlag" : Flagz.Greenland,},
  {"countryName" : "Grenada", "countryFlag" : Flagz.Grenada,},
  {"countryName" : "Guadeloupe", "countryFlag" : Flagz.Guadeloupe,},
  {"countryName" : "Guam", "countryFlag" : Flagz.Guam,},
  {"countryName" : "Guatemala", "countryFlag" : Flagz.Guatemala,},
  {"countryName" : "Guernsey", "countryFlag" : Flagz.Guernsey,},
  {"countryName" : "Guinea", "countryFlag" : Flagz.Guinea,},
  {"countryName" : "Guinea Bissau", "countryFlag" : Flagz.Guinea_Bissau,},
  {"countryName" : "Haiti", "countryFlag" : Flagz.Haiti,},
  {"countryName" : "Honduras", "countryFlag" : Flagz.Honduras,},
  {"countryName" : "Hong Kong", "countryFlag" : Flagz.Hong_Kong,},
  {"countryName" : "Hungary", "countryFlag" : Flagz.Hungary,},
  {"countryName" : "Iceland", "countryFlag" : Flagz.Iceland,},
  {"countryName" : "India", "countryFlag" : Flagz.India,},
  {"countryName" : "Indonesia", "countryFlag" : Flagz.Indonesia,},
  {"countryName" : "Iran", "countryFlag" : Flagz.Iran,},
  {"countryName" : "Iraq", "countryFlag" : Flagz.Iraq,},
  {"countryName" : "Ireland", "countryFlag" : Flagz.Ireland,},
  {"countryName" : "Isle Of Man", "countryFlag" : Flagz.Isle_Of_Man,},
  {"countryName" : "Israel", "countryFlag" : Flagz.Israel,},
  {"countryName" : "Italy", "countryFlag" : Flagz.Italy,},
  {"countryName" : "Jamaica", "countryFlag" : Flagz.Jamaica,},
  {"countryName" : "Japan", "countryFlag" : Flagz.Japan,},
  {"countryName" : "Jersey", "countryFlag" : Flagz.Jersey,},
  {"countryName" : "Jordan", "countryFlag" : Flagz.Jordan,},
  {"countryName" : "Kazakhstan", "countryFlag" : Flagz.Kazakhstan,},
  {"countryName" : "Kenya", "countryFlag" : Flagz.Kenya,},
  {"countryName" : "Kiribati", "countryFlag" : Flagz.Kiribati,},
  {"countryName" : "Kuwait", "countryFlag" : Flagz.Kuwait,},
  {"countryName" : "Kyrgyzstan", "countryFlag" : Flagz.Kyrgyzstan,},
  {"countryName" : "Laos", "countryFlag" : Flagz.Laos,},
  {"countryName" : "Latvia", "countryFlag" : Flagz.Latvia,},
  {"countryName" : "Lebanon", "countryFlag" : Flagz.Lebanon,},
  {"countryName" : "Lesotho", "countryFlag" : Flagz.Lesotho,},
  {"countryName" : "Liberia", "countryFlag" : Flagz.Liberia,},
  {"countryName" : "Libya", "countryFlag" : Flagz.Libya,},
  {"countryName" : "Liechtenstein", "countryFlag" : Flagz.Liechtenstein,},
  {"countryName" : "Lithuania", "countryFlag" : Flagz.Lithuania,},
  {"countryName" : "Luxembourg", "countryFlag" : Flagz.Luxembourg,},
  {"countryName" : "Macao", "countryFlag" : Flagz.Macao,},
  {"countryName" : "Macedonia", "countryFlag" : Flagz.Macedonia,},
  {"countryName" : "Madagascar", "countryFlag" : Flagz.Madagascar,},
  {"countryName" : "Malawi", "countryFlag" : Flagz.Malawi,},
  {"countryName" : "Malaysia", "countryFlag" : Flagz.Malaysia,},
  {"countryName" : "Maldives", "countryFlag" : Flagz.Maldives,},
  {"countryName" : "Mali", "countryFlag" : Flagz.Mali,},
  {"countryName" : "Malta", "countryFlag" : Flagz.Malta,},
  {"countryName" : "Marshall Island", "countryFlag" : Flagz.Marshall_Island,},
  {"countryName" : "Martinique", "countryFlag" : Flagz.Martinique,},
  {"countryName" : "Mauritania", "countryFlag" : Flagz.Mauritania,},
  {"countryName" : "Mauritius", "countryFlag" : Flagz.Mauritius,},
  {"countryName" : "Mayotte", "countryFlag" : Flagz.Mayotte,},
  {"countryName" : "Mexico", "countryFlag" : Flagz.Mexico,},
  {"countryName" : "Micronesia", "countryFlag" : Flagz.Micronesia,},
  {"countryName" : "Moldova", "countryFlag" : Flagz.Moldova,},
  {"countryName" : "Monaco", "countryFlag" : Flagz.Monaco,},
  {"countryName" : "Mongolia", "countryFlag" : Flagz.Mongolia,},
  {"countryName" : "Montenegro", "countryFlag" : Flagz.Montenegro,},
  {"countryName" : "Montserrat", "countryFlag" : Flagz.Montserrat,},
  {"countryName" : "Morocco", "countryFlag" : Flagz.Morocco,},
  {"countryName" : "Mozambique", "countryFlag" : Flagz.Mozambique,},
  {"countryName" : "Myanmar", "countryFlag" : Flagz.Myanmar,},
  {"countryName" : "Namibia", "countryFlag" : Flagz.Namibia,},
  {"countryName" : "Nauru", "countryFlag" : Flagz.Nauru,},
  {"countryName" : "Nepal", "countryFlag" : Flagz.Nepal,},
  {"countryName" : "Netherlands", "countryFlag" : Flagz.Netherlands,},
  {"countryName" : "New Zealand", "countryFlag" : Flagz.New_Zealand,},
  {"countryName" : "Nicaragua", "countryFlag" : Flagz.Nicaragua,},
  {"countryName" : "Niger", "countryFlag" : Flagz.Niger,},
  {"countryName" : "Nigeria", "countryFlag" : Flagz.Nigeria,},
  {"countryName" : "Niue", "countryFlag" : Flagz.Niue,},
  {"countryName" : "Norfolk Island", "countryFlag" : Flagz.Norfolk_Island,},
  {"countryName" : "North Korea", "countryFlag" : Flagz.North_Korea,},
  {"countryName" : "Northen Cyprus", "countryFlag" : Flagz.Northen_Cyprus,},
  {"countryName" : "Northern Marianas Islands", "countryFlag" : Flagz.Northern_Marianas_Islands,},
  {"countryName" : "Norway", "countryFlag" : Flagz.Norway,},
  {"countryName" : "Oman", "countryFlag" : Flagz.Oman,},
  {"countryName" : "Pakistan", "countryFlag" : Flagz.Pakistan,},
  {"countryName" : "Palau", "countryFlag" : Flagz.Palau,},
  {"countryName" : "Palestine", "countryFlag" : Flagz.Palestine,},
  {"countryName" : "Panama", "countryFlag" : Flagz.Panama,},
  {"countryName" : "Papua New Guinea", "countryFlag" : Flagz.Papua_New_Guinea,},
  {"countryName" : "Paraguay", "countryFlag" : Flagz.Paraguay,},
  {"countryName" : "Peru", "countryFlag" : Flagz.Peru,},
  {"countryName" : "Philippines", "countryFlag" : Flagz.Philippines,},
  {"countryName" : "Pitcairn Islands", "countryFlag" : Flagz.Pitcairn_Islands,},
  {"countryName" : "Poland", "countryFlag" : Flagz.Poland,},
  {"countryName" : "Portugal", "countryFlag" : Flagz.Portugal,},
  {"countryName" : "Puerto Rico", "countryFlag" : Flagz.Puerto_Rico,},
  {"countryName" : "Qatar", "countryFlag" : Flagz.Qatar,},
  {"countryName" : "Reunion", "countryFlag" : Flagz.Reunion,},
  {"countryName" : "Romania", "countryFlag" : Flagz.Romania,},
  {"countryName" : "Russia", "countryFlag" : Flagz.Russia,},
  {"countryName" : "Rwanda", "countryFlag" : Flagz.Rwanda,},
  {"countryName" : "Saba Island", "countryFlag" : Flagz.Saba_Island,},
  {"countryName" : "Saint Barthelemy", "countryFlag" : Flagz.Saint_Barthelemy,},
  {"countryName" : "Saint Helena", "countryFlag" : Flagz.Saint_Helena,},
  {"countryName" : "Saint Kitts And Nevis", "countryFlag" : Flagz.Saint_Kitts_And_Nevis,},
  {"countryName" : "Saint Lucia", "countryFlag" : Flagz.Saint_Lucia,},
  {"countryName" : "Saint Pierre And Miquelon", "countryFlag" : Flagz.Saint_Pierre_And_Miquelon,},
  {"countryName" : "Saint Vincent And The Grenadines", "countryFlag" : Flagz.Saint_Vincent_And_The_Grenadines,},
  {"countryName" : "Samoa", "countryFlag" : Flagz.Samoa,},
  {"countryName" : "San Marino", "countryFlag" : Flagz.San_Marino,},
  {"countryName" : "Sao Tome And Principe", "countryFlag" : Flagz.Sao_Tome_And_Principe,},
  {"countryName" : "Saudi Arabia", "countryFlag" : Flagz.Saudi_Arabia,},
  {"countryName" : "Scotland", "countryFlag" : Flagz.Scotland,},
  {"countryName" : "Senegal", "countryFlag" : Flagz.Senegal,},
  {"countryName" : "Serbia", "countryFlag" : Flagz.Serbia,},
  {"countryName" : "Seychelles", "countryFlag" : Flagz.Seychelles,},
  {"countryName" : "Sierra Leone", "countryFlag" : Flagz.Sierra_Leone,},
  {"countryName" : "Singapore", "countryFlag" : Flagz.Singapore,},
  {"countryName" : "Sint Maarten", "countryFlag" : Flagz.Sint_Maarten,},
  {"countryName" : "Sint Eustatius", "countryFlag" : Flagz.Sint_Eustatius,},
  {"countryName" : "Slovakia", "countryFlag" : Flagz.Slovakia,},
  {"countryName" : "Slovenia", "countryFlag" : Flagz.Slovenia,},
  {"countryName" : "Solomon Islands", "countryFlag" : Flagz.Solomon_Islands,},
  {"countryName" : "Somalia", "countryFlag" : Flagz.Somalia,},
  {"countryName" : "South Africa", "countryFlag" : Flagz.South_Africa,},
  {"countryName" : "South Georgia", "countryFlag" : Flagz.South_Georgia,},
  {"countryName" : "South Korea", "countryFlag" : Flagz.South_Korea,},
  {"countryName" : "South Sudan", "countryFlag" : Flagz.South_Sudan,},
  {"countryName" : "Spain", "countryFlag" : Flagz.Spain,},
  {"countryName" : "Sri Lanka", "countryFlag" : Flagz.Sri_Lanka,},
  {"countryName" : "Sudan", "countryFlag" : Flagz.Sudan,},
  {"countryName" : "Suriname", "countryFlag" : Flagz.Suriname,},
  {"countryName" : "Svalbard And Jan Mayen Islands", "countryFlag" : Flagz.Svalbard_And_Jan_Mayen_Islands,},
  {"countryName" : "Swaziland", "countryFlag" : Flagz.Swaziland,},
  {"countryName" : "Sweden", "countryFlag" : Flagz.Sweden,},
  {"countryName" : "Switzerland", "countryFlag" : Flagz.Switzerland,},
  {"countryName" : "Syria", "countryFlag" : Flagz.Syria,},
  {"countryName" : "Taiwan", "countryFlag" : Flagz.Taiwan,},
  {"countryName" : "Tajikistan", "countryFlag" : Flagz.Tajikistan,},
  {"countryName" : "Tanzania", "countryFlag" : Flagz.Tanzania,},
  {"countryName" : "Thailand", "countryFlag" : Flagz.Thailand,},
  {"countryName" : "Timor Leste", "countryFlag" : Flagz.Timor_Leste,},
  {"countryName" : "Togo", "countryFlag" : Flagz.Togo,},
  {"countryName" : "Tokelau", "countryFlag" : Flagz.Tokelau,},
  {"countryName" : "Tonga", "countryFlag" : Flagz.Tonga,},
  {"countryName" : "Trinidad And Tobago", "countryFlag" : Flagz.Trinidad_And_Tobago,},
  {"countryName" : "Tunisia", "countryFlag" : Flagz.Tunisia,},
  {"countryName" : "Turkey", "countryFlag" : Flagz.Turkey,},
  {"countryName" : "Turkmenistan", "countryFlag" : Flagz.Turkmenistan,},
  {"countryName" : "Turks And Caicos", "countryFlag" : Flagz.Turks_And_Caicos,},
  {"countryName" : "Tuvalu", "countryFlag" : Flagz.Tuvalu,},
  {"countryName" : "Uae", "countryFlag" : Flagz.Uae,},
  {"countryName" : "Uganda", "countryFlag" : Flagz.Uganda,},
  {"countryName" : "Ukraine", "countryFlag" : Flagz.Ukraine,},
  {"countryName" : "United Kingdom", "countryFlag" : Flagz.United_Kingdom,},
  {"countryName" : "Uruguay", "countryFlag" : Flagz.Uruguay,},
  {"countryName" : "Uzbekistn", "countryFlag" : Flagz.Uzbekistn,},
  {"countryName" : "Vanuatu", "countryFlag" : Flagz.Vanuatu,},
  {"countryName" : "Vatican City", "countryFlag" : Flagz.Vatican_City,},
  {"countryName" : "Venezuela", "countryFlag" : Flagz.Venezuela,},
  {"countryName" : "Vietnam", "countryFlag" : Flagz.Vietnam,},
  {"countryName" : "Virgin Islands", "countryFlag" : Flagz.Virgin_Islands,},
  {"countryName" : "Wales", "countryFlag" : Flagz.Wales,},
  {"countryName" : "Western Sahara", "countryFlag" : Flagz.Western_Sahara,},
  {"countryName" : "Yemen", "countryFlag" : Flagz.Yemen,},
  {"countryName" : "Zambia", "countryFlag" : Flagz.Zambia,},
  {"countryName" : "Zimbabwe", "countryFlag" : Flagz.Zimbabwe,},
];