import 'package:bldrs/models/bz_model.dart';
import 'package:bldrs/models/enums/enum_bz_form.dart';
import 'package:bldrs/models/enums/enum_bz_type.dart';
import 'db_slide.dart';

final List<BzModel> dbBzz =
[
// --- mn1
  BzModel(
    bzId: 'mn1',
    bzType: BzType.Manufacturer,
    bzLogo: Dumz.XXsipes_logo,
    bzName: 'Sipes paints',
    bzCity: 'Cairo',
    bzCountry: 'Egypt',
    bldrBirth: 2020,
    bzBirth: 1992,
    bzAbout: 'Sipes provides a wide variety of paint, paint chemicals and more\nWe have been leadin the market since 1992 with our technologically chemically advanced paints which withstands moist air vacuum and space',
    bzFieldsList: ['Wall paints', 'Floor paints', 'Ceiling Paints', 'Outdoor paints', 'Paint add-ons', 'Paint chemicals'],
    bzWhatsAppIsOn: true,
    bzShowsTeam: true,
    bzIsVerified: true,
    bzAccountCanPublish: true,
    bzAccountIsPublished: true,
    bzForm: BzForm.Company,
  ),

// --- mn2
  BzModel(
    bzId: 'mn2',
    bzType: BzType.Manufacturer,
    bzLogo: Dumz.XXjotun_logo,
    bzName: 'Jotun, Egypt',
    bzCity: 'Cairo',
    bzCountry: 'Egypt',
    bldrBirth: 2020,
    bzBirth: 2001,
    bzAbout: 'Jotun Paints, you heard of us, we paint the world with happiness',
    bzFieldsList: ['Wall paints', 'Floor paints', 'Ceiling Paints', 'Outdoor paints', 'Paint add-ons', 'Paint chemicals'],
    bzWhatsAppIsOn: true,
    bzShowsTeam: true,
    bzIsVerified: true,
    bzAccountCanPublish: true,
    bzAccountIsPublished: true,
    bzForm: BzForm.Company,
  ),

// --- mn3
  BzModel(
    bzId: 'mn3',
    bzType: BzType.Manufacturer,
    bzLogo: Dumz.XXikea_logo,
    bzName: 'Ikea, Egypt',
    bzCity: 'Cairo',
    bzCountry: 'Egypt',
    bldrBirth: 2020,
    bzBirth: 2011,
    bzAbout: 'Ikea, Where great Ideas form great lives',
    bzFieldsList: ['Indoor furniture', 'Curtains', 'Outdoor furniture', 'KitchenWare', 'Office furniture', 'Kitchens', 'Kitchen Cabinets', 'Lighting fixtures', 'Wardrobes', 'fabrics', 'artificial plants', 'bathroom accessories', 'kitchen accessories'],
    bzWhatsAppIsOn: false,
    bzShowsTeam: true,
    bzIsVerified: true,
    bzAccountCanPublish: true,
    bzAccountIsPublished: true,
    bzForm: BzForm.Company,
  ),

// --- mn4
  BzModel(
    bzId: 'mn4',
    bzType: BzType.Manufacturer,
    bzLogo: Dumz.XXbticino_logo,
    bzName: 'Bticino',
    bzCity: 'Cairo',
    bzCountry: 'Egypt',
    bldrBirth: 2020,
    bzBirth: 1805,
    bzAbout: 'bticino, don\'t just control light,, controls life',
    bzFieldsList: ['lighting accessories', 'lighting switches', 'environmentally friendly bulbs', 'more'],
    bzWhatsAppIsOn: false,
    bzShowsTeam: true,
    bzIsVerified: true,
    bzAccountCanPublish: true,
    bzAccountIsPublished: true,
    bzForm: BzForm.Company,
  ),

// --- mn5
  BzModel(
    bzId: 'mn5',
    bzType: BzType.Manufacturer,
    bzLogo: Dumz.XXcat_logo,
    bzName: 'CAT',
    bzCity: 'Cairo',
    bzCountry: 'Egypt',
    bldrBirth: 2020,
    bzBirth: 1935,
    bzAbout: 'CAT pioneered the heavy machinery in world war 2, and we have assisted in the elimination of the Nazi regime, then we help the world build',
    bzFieldsList: ['Loaders', 'Excavators', 'Earth levellers', 'Cranes', 'Signage', 'generators', 'safety clothing'],
    bzWhatsAppIsOn: false,
    bzShowsTeam: true,
    bzIsVerified: true,
    bzAccountCanPublish: true,
    bzAccountIsPublished: true,
    bzForm: BzForm.Company,
  ),

// --- dv1
  BzModel(
    bzId: 'pp1',
    bzType: BzType.Developer,
    bzLogo: Dumz.XXsodic_logo,
    bzName: 'Sodic',
    bzCity: 'Cairo',
    bzCountry: 'Egypt',
    bldrBirth: 2020,
    bzBirth: 2005,
    bzAbout: 'Soidc East, Sodic West, Sodic North, Sodic South, Sodic Center',
    bzFieldsList: ['Real Estate Development', 'Facility Management'],
    bzWhatsAppIsOn: true,
    bzShowsTeam: false,
    bzIsVerified: true,
    bzAccountCanPublish: true,
    bzAccountIsPublished: true,
    bzForm: BzForm.Company,
  ),

// --- dv2
  BzModel(
    bzId: 'pp2',
    bzType: BzType.Developer,
    bzLogo: Dumz.XXsabbour_logo,
    bzName: 'Sabbour developments',
    bzCity: 'Cairo',
    bzCountry: 'Egypt',
    bldrBirth: 2020,
    bzBirth: 1945,
    bzAbout: 'Sabbour Is the Greatest Egyptian real estate developer',
    bzFieldsList: ['Real Estate Development', 'Facility Management'],
    bzWhatsAppIsOn: true,
    bzShowsTeam: false,
    bzIsVerified: true,
    bzAccountCanPublish: true,
    bzAccountIsPublished: true,
    bzForm: BzForm.Company,
  ),

// --- dv3
  BzModel(
    bzId: 'pp3',
    bzType: BzType.Developer,
    bzLogo: Dumz.XXemaar_logo,
    bzName: 'Emaar',
    bzCity: 'Dubai',
    bzCountry: 'UAE',
    bldrBirth: 2020,
    bzBirth: 2001,
    bzAbout: 'Emaar is the middle east leading real estate developer',
    bzFieldsList: ['Real Estate Development', 'Facility Management'],
    bzWhatsAppIsOn: true,
    bzShowsTeam: true,
    bzIsVerified: true,
    bzAccountCanPublish: true,
    bzAccountIsPublished: true,
    bzForm: BzForm.Company,
  ),

// --- dr1
  BzModel(
    bzId: 'dr1',
    bzType: BzType.Designer,
    bzLogo: Dumz.XXmhdh_logo,
    bzName: 'MHDH, Mona Hussein Design House',
    bzCity: 'Cairo',
    bzCountry: 'Egypt',
    bldrBirth: 2020,
    bzBirth: 2018,
    bzAbout: 'Mona Hussein with her eccentric aesthetic design philosophy transcends the meaning of decor into a rank of design persona for spaces which reflects the souls of our beloved customers',
    bzFieldsList: ['Interior design', 'Exterior design', 'Design & build', 'Landscape design', 'Furniture design', 'Booth design', 'Pool design', 'Kitchen Design'],
    bzWhatsAppIsOn: false,
    bzShowsTeam: true,
    bzIsVerified: true,
    bzAccountCanPublish: true,
    bzAccountIsPublished: true,
    bzForm: BzForm.Company,
  ),

// --- dr2
  BzModel(
    bzId: 'dr2',
    bzType: BzType.Designer,
    bzLogo: Dumz.XXhs_logo,
    bzName: 'HSI . Hany Saad Innovations',
    bzCity: 'Cairo',
    bzCountry: 'Egypt',
    bldrBirth: 2020,
    bzBirth: 2010,
    bzAbout: 'Hany Saad Innovations is the award winning design studio of the internation prize of interior innovation & design',
    bzFieldsList: ['Interior design', 'Exterior design', 'Design & build', 'Landscape design', 'Furniture design', 'Booth design', 'Pool design', 'Kitchen Design'],
    bzWhatsAppIsOn: false,
    bzShowsTeam: true,
    bzIsVerified: true,
    bzAccountCanPublish: true,
    bzAccountIsPublished: true,
    bzForm: BzForm.Company,
  ),

// --- dr2
  BzModel(
    bzId: 'dr3',
    bzType: BzType.Designer,
    bzLogo: Dumz.XXeklego_logo,
    bzName: 'Eklego',
    bzCity: 'Cairo',
    bzCountry: 'Egypt',
    bldrBirth: 2020,
    bzBirth: 2001,
    bzAbout: 'Eklego focuses on remoling life with art, and when art meets engineering, a new realm of architecture, interior design & furniture design emerges, Eklego has been in the market since 1901, and has built a countless amount of spaces and built a termendous amount of projects ever since',
    bzFieldsList: ['Interior design', 'Exterior design', 'Design & build', 'Landscape design', 'Furniture design', 'Booth design', 'Pool design', 'Kitchen Design', 'Furniture design', 'home accessories', 'bathroom accessories', 'mirrors', 'furniture', 'light fixtures'],
    bzWhatsAppIsOn: false,
    bzShowsTeam: true,
    bzIsVerified: true,
    bzAccountCanPublish: true,
    bzAccountIsPublished: true,
    bzForm: BzForm.Company,
  ),

// --- cn1
  BzModel(
    bzId: 'cn1',
    bzType: BzType.Contractor,
    bzLogo: Dumz.XXzahran_logo,
    bzName: 'Zahran Contracting',
    bzCity: 'Cairo',
    bzCountry: 'Egypt',
    bldrBirth: 2020,
    bzBirth: 2011,
    bzAbout: 'زهران لجميع بنود المقاولات، مقاولات عامة ، مقاولات خرسانة، و متوفر جديم المعدات و العمالة بأنسب الأسعار',
    bzFieldsList: ['Contractor', 'Home Builder', 'Interior Finishing', 'Pool building', 'Construction management', 'Construction planning'],
    bzWhatsAppIsOn: true,
    bzShowsTeam: true,
    bzIsVerified: true,
    bzAccountCanPublish: true,
    bzAccountIsPublished: true,
    bzForm: BzForm.Company,
  ),

// --- cn2
  BzModel(
    bzId: 'cn2',
    bzType: BzType.Contractor,
    bzLogo: Dumz.XXeng_logo,
    bzName: 'مكتب المهندس للمقاولات العامة',
    bzCity: 'Cairo',
    bzCountry: 'Egypt',
    bldrBirth: 2021,
    bzBirth: 2015,
    bzAbout: 'زهران لجميع بنود المقاولات، مقاولات عامة ، مقاولات خرسانة',
    bzFieldsList: ['Contractor', 'Home Builder', 'Interior Finishing', 'Construction management', 'Construction planning'],
    bzWhatsAppIsOn: true,
    bzShowsTeam: true,
    bzIsVerified: true,
    bzAccountCanPublish: true,
    bzAccountIsPublished: true,
    bzForm: BzForm.Company,
  ),

// --- br1
  BzModel(
    bzId: 'br1',
    bzType: BzType.Broker,
    bzLogo: Dumz.XXultimate_logo,
    bzName: 'Ultimate Real Estate',
    bzCity: 'Cairo',
    bzCountry: 'Egypt',
    bldrBirth: 2020,
    bzBirth: 1987,
    bzAbout: 'With a big variety of up-to-date inventory of realestate across Egypt, we Make sure all your requirements are properly met and the best decissions are made for best investments in the market',
    bzFieldsList: ['Realestate brokerage', 'Realestate consultancy', ],
    bzWhatsAppIsOn: true,
    bzShowsTeam: true,
    bzIsVerified: true,
    bzAccountCanPublish: true,
    bzAccountIsPublished: true,
    bzForm: BzForm.Company,
  ),

// --- sp1
  BzModel(
    bzId: 'sp1',
    bzType: BzType.Supplier,
    bzLogo: Dumz.XXalumital_logo,
    bzName: 'Mohamed Ali for All Alumital windows & doors',
    bzCity: 'Cairo',
    bzCountry: 'Egypt',
    bldrBirth: 2020,
    bzBirth: 1999,
    bzAbout: 'visit us, we are always here, we make good windows, and best doors in country 01554555107',
    bzFieldsList: ['doors', 'windows', 'skylights'],
    bzWhatsAppIsOn: true,
    bzShowsTeam: true,
    bzIsVerified: true,
    bzAccountCanPublish: true,
    bzAccountIsPublished: true,
    bzForm: BzForm.Company,
  ),

// --- sp2
  BzModel(
    bzId: 'sp2',
    bzType: BzType.Supplier,
    bzLogo: Dumz.XXpower_logo,
    bzName: 'Powerezza for powerfull power tools',
    bzCity: 'Cairo',
    bzCountry: 'Egypt',
    bldrBirth: 2020,
    bzBirth: 2005,
    bzAbout: 'contact us, we deliver anywhere in cairo,  اتصل بنا ، نحن هنا دائما',
    bzFieldsList: ['power tools', 'hand tools', 'heavy equipment'],
    bzWhatsAppIsOn: true,
    bzShowsTeam: true,
    bzIsVerified: true,
    bzAccountCanPublish: true,
    bzAccountIsPublished: true,
    bzForm: BzForm.Company,
  ),

// --- sp3
  BzModel(
    bzId: 'sp3',
    bzType: BzType.Supplier,
    bzLogo: Dumz.XXloader_logo,
    bzName: 'علاء لوادر للوادر',
    bzCity: 'Cairo',
    bzCountry: 'Egypt',
    bldrBirth: 2020,
    bzBirth: 2018,
    bzAbout: '01554555107  اتصل بنا ، نحن هنا دائما',
    bzFieldsList: ['Loader', 'Excavator', 'Crane', 'generators'],
    bzWhatsAppIsOn: true,
    bzShowsTeam: true,
    bzIsVerified: true,
    bzAccountCanPublish: true,
    bzAccountIsPublished: true,
    bzForm: BzForm.Company,
  ),

  // --- ar1
  BzModel(
    bzId: 'ar1',
    bzType: BzType.Artisan,
    bzLogo: Dumz.XXfixawy_logo,
    bzName: 'Fixawy',
    bzCity: 'Cairo',
    bzCountry: 'Egypt',
    bldrBirth: 2020,
    bzBirth: 2012,
    bzAbout: 'Fixawy for home & office Maintenance',
    bzFieldsList: ['Maintenance', 'Electricity maintenance', 'plumbing', 'Carpentering'],
    bzWhatsAppIsOn: false,
    bzShowsTeam: true,
    bzIsVerified: true,
    bzAccountCanPublish: true,
    bzAccountIsPublished: true,
    bzForm: BzForm.Company,
  ),

// --- ar2
  BzModel(
    bzId: 'ar2',
    bzType: BzType.Artisan,
    bzLogo: Dumz.XXahmad_logo,
    bzName: 'Ahmad for wood',
    bzCity: 'Cairo',
    bzCountry: 'Egypt',
    bldrBirth: 2020,
    bzBirth: 1993,
    bzAbout: 'اتصلوا بنا 01554555107 لجميع أنواع الأساس الخشب و الكونتا والسراير و دوليب و كله.. نحن دايما في الخدمة',
    bzFieldsList: ['Carpentry'],
    bzWhatsAppIsOn: true,
    bzShowsTeam: true,
    bzIsVerified: true,
    bzAccountCanPublish: true,
    bzAccountIsPublished: true,
    bzForm: BzForm.Company,
  ),

];