linter:
  rules:
    parameter_assignments: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    always_use_package_imports: true
    avoid_returning_null_for_future: true
    avoid_web_libraries_in_flutter: true
    close_sinks: true
    comment_references: true
    control_flow_in_finally: true
    empty_statements: true
    hash_and_equals: true
    invariant_booleans: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    prefer_void_to_null: true
    avoid_relative_lib_imports: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    use_key_in_widget_constructors: true

    diagnostic_describe_all_properties: false
    avoid_types_as_parameter_names: false
    avoid_type_to_string: false
    avoid_dynamic_calls: false
    avoid_empty_else: false
    avoid_print: false

    # defiantly false rules
    prefer_relative_imports: false

analyzer:
  errors:
    missing_required_param: error
    parameter_assignments: error