linter:
  rules:
    parameter_assignments: false
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

analyzer:
  errors:
    missing_required_param: error
    parameter_assignments: error