library keywords_tree;
// --------------------------------------------------------------------------
import 'package:basics/helpers/maps/lister.dart';
import 'package:basics/helpers/strings/stringer.dart';
import 'package:bldrs/c_protocols/main_providers/ui_provider.dart';
import 'package:bldrs/e_back_end/g_storage/storage_path.dart';
import 'package:flutter/material.dart';
import 'package:basics/helpers/checks/tracers.dart';
import 'package:basics/helpers/maps/map_pathing.dart';
import 'package:basics/helpers/maps/mapper.dart';
import 'package:basics/bldrs_theme/classes/colorz.dart';
import 'package:basics/bldrs_theme/classes/iconz.dart';
import 'package:basics/helpers/space/borderers.dart';
import 'package:bldrs/z_components/buttons/general_buttons/bldrs_box.dart';
import 'package:bldrs/z_components/texting/super_verse/super_verse.dart';
import 'package:bldrs/z_components/texting/super_verse/verse_model.dart';
import 'package:bldrs/f_helpers/drafters/bldrs_aligners.dart';
import 'package:bldrs/f_helpers/drafters/iconizers.dart';
import 'package:bldrs/f_helpers/localization/localizer.dart';
import 'dart:math';
import 'package:thebrio_segmented_circle_border/thebri_segmented_circle_border.dart';
// --------------------------------------------------------------------------
part 'src/a_keywords_tree_starter.dart';
part 'src/b_keyword_node_viewer.dart';
part 'src/c_keyword_tree_strip.dart';
part 'src/tree_line.dart';
// --------------------------------------------------------------------------
