
import 'package:bldrs/models/planet/city_model.dart';

List<Area> dbAreas = <Area>[
  Area(iso3: 'egy', province: 'Cairo', id:'1', name:'Heliopolis', names:[Namez(code:'ar', value: 'مصر الجديدة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'2', name:'Nasr City', names:[Namez(code:'ar', value: 'مدينة نصر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'3', name:'El-Maadi', names:[Namez(code:'ar', value: 'المعادي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'4', name:'New Cairo', names:[Namez(code:'ar', value: 'التجمع'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'5', name:'Hadayek El-Kobba', names:[Namez(code:'ar', value: 'حدائق القبة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'6', name:'El-Obour City', names:[Namez(code:'ar', value: 'مدينة العبور'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'7', name:'El-Manyal', names:[Namez(code:'ar', value: 'المنيل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'8', name:'Shoubra', names:[Namez(code:'ar', value: 'شبرا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'9', name:'West El-Balad', names:[Namez(code:'ar', value: 'وسط البلد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'10', name:'El Salam City', names:[Namez(code:'ar', value: 'مدينة السلام'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'11', name:'El-Rehab', names:[Namez(code:'ar', value: 'الرحاب'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'12', name:'El-Zamalek', names:[Namez(code:'ar', value: 'الزمالك'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'13', name:'El-Zaitoun', names:[Namez(code:'ar', value: 'الزيتون'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'14', name:'El-Sayeda Zainab', names:[Namez(code:'ar', value: 'السيدة زينب'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'15', name:'El-Shorouk', names:[Namez(code:'ar', value: 'الشروق'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'16', name:'10th of Ramadan', names:[Namez(code:'ar', value: 'العاشر من رمضان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'17', name:'El-Abbasia', names:[Namez(code:'ar', value: 'العباسية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'18', name:'El-Kattameya', names:[Namez(code:'ar', value: 'القطامية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'19', name:'El-Marg', names:[Namez(code:'ar', value: 'المرج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'20', name:'El-Matareya', names:[Namez(code:'ar', value: 'المطرية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'21', name:'El-Mokattam', names:[Namez(code:'ar', value: 'المقطم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'22', name:'Boulaq', names:[Namez(code:'ar', value: 'بولاق'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'23', name:'Hadayek El Maadi', names:[Namez(code:'ar', value: 'حدائق المعادي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'24', name:'Hadayek Helwan', names:[Namez(code:'ar', value: 'حدائق حلوان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'25', name:'Helwan', names:[Namez(code:'ar', value: 'حلوان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'26', name:'Dar El-Salam', names:[Namez(code:'ar', value: 'دار السلام'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'27', name:'Shoubra El-Kheima', names:[Namez(code:'ar', value: 'شبرا الخيمة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'28', name:'Ain Shams', names:[Namez(code:'ar', value: 'عين شمس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'29', name:'Badr City', names:[Namez(code:'ar', value: 'مدينة بدر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'30', name:'Madinaty', names:[Namez(code:'ar', value: 'مدينتي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'31', name:'Masr El-Kadima', names:[Namez(code:'ar', value: 'مصر القديمة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'32', name:'Mahatet El-Raml', names:[Namez(code:'ar', value: 'محطة الرمل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'33', name:'Roshdy', names:[Namez(code:'ar', value: 'رشدي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'34', name:'Smouha', names:[Namez(code:'ar', value: 'سموحة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'35', name:'Sporting', names:[Namez(code:'ar', value: 'سبورتينج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'36', name:'Sidy Gaber', names:[Namez(code:'ar', value: 'سيدي جابر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'37', name:'Loran', names:[Namez(code:'ar', value: 'لوران'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'38', name:'Camp Caesar', names:[Namez(code:'ar', value: 'كامب شيزار'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'39', name:'El-Ibrahimia', names:[Namez(code:'ar', value: 'الإبراهيمية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'40', name:'Janaklees', names:[Namez(code:'ar', value: 'جانكليس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'41', name:'Abou Keir', names:[Namez(code:'ar', value: 'ابو قير'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'42', name:'El-Azarita', names:[Namez(code:'ar', value: 'الأزاريطه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'43', name:'El-Seyouf', names:[Namez(code:'ar', value: 'السيوف'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'44', name:'El-Shatby', names:[Namez(code:'ar', value: 'الشاطبي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'45', name:'El-Amreya', names:[Namez(code:'ar', value: 'العامرية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'46', name:'El-Agamy', names:[Namez(code:'ar', value: 'العجمي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'47', name:'El-Asafra', names:[Namez(code:'ar', value: 'العصافرة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'48', name:'El-Montazah', names:[Namez(code:'ar', value: 'المنتزه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'49', name:'El-Mandara', names:[Namez(code:'ar', value: 'المندرة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'50', name:'El-Mansheyah', names:[Namez(code:'ar', value: 'المنشية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'51', name:'El-Werdeyan', names:[Namez(code:'ar', value: 'الورديان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'52', name:'Bakos', names:[Namez(code:'ar', value: 'باكوس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'53', name:'Bahary', names:[Namez(code:'ar', value: 'بحري'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'54', name:'Bulkly', names:[Namez(code:'ar', value: 'بولكلي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'55', name:'Glym', names:[Namez(code:'ar', value: 'جليم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'56', name:'Zizenia', names:[Namez(code:'ar', value: 'زيزينيا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'57', name:'Saba Basha', names:[Namez(code:'ar', value: 'سابا باشا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'58', name:'San Stefano', names:[Namez(code:'ar', value: 'سان ستيفانو'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'59', name:'Stanley', names:[Namez(code:'ar', value: 'ستانلي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'60', name:'Sidy Bishr', names:[Namez(code:'ar', value: 'سيدي بشر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'61', name:'Fouad Street', names:[Namez(code:'ar', value: 'شارع فؤاد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'62', name:'Fleming', names:[Namez(code:'ar', value: 'فلمنج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'63', name:'Victoria', names:[Namez(code:'ar', value: 'فيكتوريا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'64', name:'Kafr Abdouh', names:[Namez(code:'ar', value: 'كفر عبده'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'65', name:'Cleopatra', names:[Namez(code:'ar', value: 'كليوباترا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'66', name:'King Mariout', names:[Namez(code:'ar', value: 'كينج ماريوط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'67', name:'Moharam Bek', names:[Namez(code:'ar', value: 'محرم بيك'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'68', name:'Moustafa Kamel', names:[Namez(code:'ar', value: 'مصطفى كامل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'69', name:'Miamy', names:[Namez(code:'ar', value: 'ميامي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Port Said', id:'70', name:'Port Said City', names:[Namez(code:'ar', value: 'مدينة بورسعيد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Port Said', id:'71', name:'Port Fouad', names:[Namez(code:'ar', value: 'بورفؤاد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Suez', id:'72', name:'مدينة السويس', names:[Namez(code:'ar', value: 'مدينة السويس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Damietta', id:'73', name:'Damietta El Gadeeda', names:[Namez(code:'ar', value: 'مدينة دمياط الجديدة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Damietta', id:'74', name:'Damietta City', names:[Namez(code:'ar', value: 'مدينة دمياط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Dakahlia', id:'75', name:'Aga', names:[Namez(code:'ar', value: 'أجا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Dakahlia', id:'76', name:'Belkas', names:[Namez(code:'ar', value: 'بلقاس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Dakahlia', id:'77', name:'Shirbin', names:[Namez(code:'ar', value: 'شربين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Dakahlia', id:'78', name:'El Senbellawein', names:[Namez(code:'ar', value: 'السنبلاوين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Dakahlia', id:'79', name:'El-Mansoura', names:[Namez(code:'ar', value: 'المنصورة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Dakahlia', id:'80', name:'Mit Ghamr', names:[Namez(code:'ar', value: 'ميت غمر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Sharkia', id:'81', name:'Abu Hammad', names:[Namez(code:'ar', value: 'أبو حماد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Sharkia', id:'82', name:'Belbes', names:[Namez(code:'ar', value: 'بلبيس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Sharkia', id:'83', name:'El-Zagazig', names:[Namez(code:'ar', value: 'الزقازيق'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Sharkia', id:'84', name:'Menya El-Kamh', names:[Namez(code:'ar', value: 'منيا القمح'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Sharkia', id:'85', name:'Fakous', names:[Namez(code:'ar', value: 'فاقوس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Qaliubiya', id:'86', name:'Shibin Al Qanater', names:[Namez(code:'ar', value: 'شبين القناطر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Qaliubiya', id:'87', name:'Banha', names:[Namez(code:'ar', value: 'مركز بنها'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Qaliubiya', id:'88', name:'Qalyoub', names:[Namez(code:'ar', value: 'قليوب'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Kafr El Sheikh', id:'89', name:'Kafr El sheikh City', names:[Namez(code:'ar', value: 'مركز كفر الشيخ'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Gharbia', id:'90', name:'Tanta', names:[Namez(code:'ar', value: 'طنطا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Gharbia', id:'91', name:'Kafr El Zayat', names:[Namez(code:'ar', value: 'مركز كفر الزيات'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Gharbia', id:'92', name:'Mahalla', names:[Namez(code:'ar', value: 'المحلة الكبرى'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Monoufia', id:'93', name:'Ashmun', names:[Namez(code:'ar', value: 'اشمون'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Monoufia', id:'94', name:'Shibin El-Kom', names:[Namez(code:'ar', value: 'شبين الكوم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Monoufia', id:'95', name:'Menouf', names:[Namez(code:'ar', value: 'منوف'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Monoufia', id:'96', name:'Sadat City', names:[Namez(code:'ar', value: 'مدينة السادات'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Monoufia', id:'97', name:'Birket El Sabea', names:[Namez(code:'ar', value: 'بركة السبع'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Beheira', id:'98', name:'Damanhur', names:[Namez(code:'ar', value: 'دمنهور'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Beheira', id:'99', name:'kafr El dawar', names:[Namez(code:'ar', value: 'مركز كفر الدوار'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Ismailia', id:'100', name:'El-Ismailia city', names:[Namez(code:'ar', value: 'مدينة الإسماعيلية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'101', name:'Dokki and Mohandessin', names:[Namez(code:'ar', value: 'الدقي والمهندسين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'102', name:'6th of October', names:[Namez(code:'ar', value: '6 اكتوبر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'103', name:'El-Haram', names:[Namez(code:'ar', value: 'الهرم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'104', name:'Faisal', names:[Namez(code:'ar', value: 'فيصل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'105', name:'El-Sheikh Zayed', names:[Namez(code:'ar', value: 'الشيخ زايد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'106', name:'Hadayek El-Ahram', names:[Namez(code:'ar', value: 'حدائق الأهرام'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'107', name:'El-Agouza', names:[Namez(code:'ar', value: 'العجوزة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'108', name:'New Giza', names:[Namez(code:'ar', value: 'الجيزة الجديدة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'109', name:'Boulaq El Dakrour', names:[Namez(code:'ar', value: 'بولاق الدكرور'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'110', name:'El-Badrashin', names:[Namez(code:'ar', value: 'البدراشين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'111', name:'El-Hawamdeya', names:[Namez(code:'ar', value: 'الحوامدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'112', name:'El-Ayyat', names:[Namez(code:'ar', value: 'العياط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'113', name:'Imbaba', names:[Namez(code:'ar', value: 'إمبابة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'114', name:'El-Giza square', names:[Namez(code:'ar', value: 'ميدان الجيزة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Bani Sweif', id:'115', name:'Beni Suef City', names:[Namez(code:'ar', value: 'مدينة بنى سويف'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Fayoum', id:'116', name:'Ibsheway', names:[Namez(code:'ar', value: 'ابشواي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Fayoum', id:'117', name:'El-Fayoum city', names:[Namez(code:'ar', value: 'مدينة الفيوم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Minya', id:'118', name:'El Minya City', names:[Namez(code:'ar', value: 'مركز المنيا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Minya', id:'119', name:'Mallawi', names:[Namez(code:'ar', value: 'ملوي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Asyut', id:'120', name:'Abnub', names:[Namez(code:'ar', value: 'ابنوب'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Asyut', id:'121', name:'Dayrout', names:[Namez(code:'ar', value: 'ديروط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Asyut', id:'122', name:'Manfalut', names:[Namez(code:'ar', value: 'منفلوط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Asyut', id:'123', name:'Assiut city', names:[Namez(code:'ar', value: 'مركز أسيوط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Sohag', id:'124', name:'Sohag City', names:[Namez(code:'ar', value: 'مدينة سوهاج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Qena', id:'125', name:'Qena City', names:[Namez(code:'ar', value: 'مدينة سوهاج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Aswan', id:'126', name:'Aswan City', names:[Namez(code:'ar', value: 'مدينة أسوان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Luxor', id:'127', name:'Luxor City', names:[Namez(code:'ar', value: 'مدينة الاقصر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Luxor', id:'128', name:'Esna', names:[Namez(code:'ar', value: 'إسنا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Red Sea', id:'129', name:'Hurghada', names:[Namez(code:'ar', value: 'الغردقة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Matrouh', id:'130', name:'Matrouh', names:[Namez(code:'ar', value: 'مرسى مطروح'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'South Sinai', id:'131', name:'Sharm Al-Sheikh', names:[Namez(code:'ar', value: 'شرم الشيخ'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'South Sinai', id:'132', name:'Al-Areish', names:[Namez(code:'ar', value: 'العريش'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'NorthCoast', id:'133', name:'North Coast', names:[Namez(code:'ar', value: 'الساحل الشمالي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'134', name:'Al Sulaimaniyah', names:[Namez(code:'ar', value: 'السليمانية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'135', name:'King Fahad', names:[Namez(code:'ar', value: 'الملك فهد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'136', name:'Al Worood', names:[Namez(code:'ar', value: 'الورود'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'137', name:'Al Maseef', names:[Namez(code:'ar', value: 'المصيف'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'138', name:'Al Muruj', names:[Namez(code:'ar', value: 'المروج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'139', name:'Al Morsalat', names:[Namez(code:'ar', value: 'المرسلات'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'140', name:'Al Ghadeer', names:[Namez(code:'ar', value: 'الغدير'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'141', name:'Al Wahah', names:[Namez(code:'ar', value: 'الواحة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'142', name:'Al Rahmaniyyah', names:[Namez(code:'ar', value: 'الرحمانية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'143', name:'Ishbiliyah', names:[Namez(code:'ar', value: 'اشبيلية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'144', name:'Al Izdihar', names:[Namez(code:'ar', value: 'الازدهار'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'145', name:'Al Badiah', names:[Namez(code:'ar', value: 'البديعة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'146', name:'Al Batha', names:[Namez(code:'ar', value: 'البطحاء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'147', name:'Takhassusi', names:[Namez(code:'ar', value: 'التخصصي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'148', name:'Al Taawun', names:[Namez(code:'ar', value: 'التعاون'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'149', name:'Al Janadriyyah', names:[Namez(code:'ar', value: 'الجنادرية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'150', name:'Al Hamra', names:[Namez(code:'ar', value: 'الحمرا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'151', name:'Al Khaleej', names:[Namez(code:'ar', value: 'الخليج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'152', name:'Al Diriyah', names:[Namez(code:'ar', value: 'الدرعية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'153', name:'Al Raed', names:[Namez(code:'ar', value: 'الرائد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'154', name:'Al Rabwah', names:[Namez(code:'ar', value: 'الربوة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'155', name:'Al Rabie', names:[Namez(code:'ar', value: 'الربيع'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'156', name:'Al Rawabi', names:[Namez(code:'ar', value: 'الروابي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'157', name:'Al Rawdah', names:[Namez(code:'ar', value: 'الروضة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'158', name:'Al Rayyan', names:[Namez(code:'ar', value: 'الريان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'159', name:'Al  Zahrah', names:[Namez(code:'ar', value: 'الزهرة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'160', name:'Al  Saadah', names:[Namez(code:'ar', value: 'السعادة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'161', name:'Al Safarat', names:[Namez(code:'ar', value: 'السفارات'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'162', name:'Al Salam', names:[Namez(code:'ar', value: 'السلام'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'163', name:'Al Sulay', names:[Namez(code:'ar', value: 'السلي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'164', name:'Al Suwaidi', names:[Namez(code:'ar', value: 'السويدي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'165', name:'Al Shifa', names:[Namez(code:'ar', value: 'الشفا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'166', name:'Al Shimaisi', names:[Namez(code:'ar', value: 'الشميسي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'167', name:'Al Shuhada', names:[Namez(code:'ar', value: 'الشهداء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'168', name:'Al Sahafa', names:[Namez(code:'ar', value: 'الصحافة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'169', name:'Al Uraija', names:[Namez(code:'ar', value: 'العريجاء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'170', name:'Al Aziziyah', names:[Namez(code:'ar', value: 'العزيزية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'171', name:'Al Aqiq', names:[Namez(code:'ar', value: 'العقيق'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'172', name:'Al Olaya', names:[Namez(code:'ar', value: 'العليا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'173', name:'Al Falah', names:[Namez(code:'ar', value: 'الفلاح'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'174', name:'Al Fayha', names:[Namez(code:'ar', value: 'الفيحاء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'175', name:'Al Quds', names:[Namez(code:'ar', value: 'القدس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'176', name:'Al Mohammadiyyah', names:[Namez(code:'ar', value: 'المحمدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'177', name:'Al Murabba', names:[Namez(code:'ar', value: 'المربع'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'178', name:'Al Marwah', names:[Namez(code:'ar', value: 'المروة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'179', name:'Al Mashael', names:[Namez(code:'ar', value: 'المشاعل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'180', name:'Al Maather', names:[Namez(code:'ar', value: 'المعذر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'181', name:'Al Mathar Ash Shamali', names:[Namez(code:'ar', value: 'المعذر الشمالي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'182', name:'Al Mughrizat', names:[Namez(code:'ar', value: 'المغرزات'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'183', name:'Al Malaz', names:[Namez(code:'ar', value: 'الملز'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'184', name:'Al Malqa', names:[Namez(code:'ar', value: 'الملقا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'185', name:'Al Mutamarat', names:[Namez(code:'ar', value: 'المؤتمرات'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'186', name:'Al Munsiyah', names:[Namez(code:'ar', value: 'المونسية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'187', name:'Al Nadwa', names:[Namez(code:'ar', value: 'الندوة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'188', name:'Al Narjis', names:[Namez(code:'ar', value: 'النرجس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'189', name:'Al Nozha', names:[Namez(code:'ar', value: 'النزهة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'190', name:'Al Naseem Al Sharqi', names:[Namez(code:'ar', value: 'النسيم الشرقي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'191', name:'Al Naseem Al Gharbi', names:[Namez(code:'ar', value: 'النسيم الغربي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'192', name:'Al Nadheem', names:[Namez(code:'ar', value: 'النظيم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'193', name:'Al Nafal', names:[Namez(code:'ar', value: 'النفل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'194', name:'Al Nahdah', names:[Namez(code:'ar', value: 'النهضة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'195', name:'Al Wadi', names:[Namez(code:'ar', value: 'الوادي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'196', name:'Al Wizarat', names:[Namez(code:'ar', value: 'الوزارات'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'197', name:'Al Yasmin', names:[Namez(code:'ar', value: 'الياسمين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'198', name:'Al Yarmuk', names:[Namez(code:'ar', value: 'اليرموك'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'199', name:'Um Al Hammam', names:[Namez(code:'ar', value: 'ام الحمام'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'200', name:'Hittin', names:[Namez(code:'ar', value: 'حطين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'201', name:'Badr', names:[Namez(code:'ar', value: 'حي بدر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'202', name:'Shubra', names:[Namez(code:'ar', value: 'شبرا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'203', name:'Salah Al Din', names:[Namez(code:'ar', value: 'صلاح الدين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'204', name:'Tuwaiq', names:[Namez(code:'ar', value: 'طويق'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'205', name:'Dhahrat Laban', names:[Namez(code:'ar', value: 'ظهرة لبن'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'206', name:'Irqah', names:[Namez(code:'ar', value: 'عرقة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'207', name:'Okaz', names:[Namez(code:'ar', value: 'عكاظ'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'208', name:'Ghubairah', names:[Namez(code:'ar', value: 'غبيرة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'209', name:'Ghirnatah', names:[Namez(code:'ar', value: 'غرناطة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'210', name:'Qurtubah', names:[Namez(code:'ar', value: 'قرطبة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'211', name:'Laban', names:[Namez(code:'ar', value: 'لبن'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'212', name:'Manfuhah', names:[Namez(code:'ar', value: 'منفوحة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'213', name:'Namar', names:[Namez(code:'ar', value: 'نمار'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'214', name:'Wadi Laban', names:[Namez(code:'ar', value: 'وادي لبن'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'215', name:'Al Shati', names:[Namez(code:'ar', value: 'الشاطىء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'216', name:'Al Faisaliyah', names:[Namez(code:'ar', value: 'الفيصلية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'217', name:'Al Rawdah', names:[Namez(code:'ar', value: 'الروضة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'218', name:'Al Salamah', names:[Namez(code:'ar', value: 'السلامة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'219', name:'Al Safa', names:[Namez(code:'ar', value: 'الصفا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'220', name:'Al Andalus', names:[Namez(code:'ar', value: 'الأندلس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'221', name:'Al Marwah', names:[Namez(code:'ar', value: 'المروة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'222', name:'Al Zahraa', names:[Namez(code:'ar', value: 'الزهراء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'223', name:'Al Bawadi', names:[Namez(code:'ar', value: 'البوادي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'224', name:'Obhur Al Janoobiyah', names:[Namez(code:'ar', value: 'أبحر الجنوبية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'225', name:'Obhur Al Shamaliyah', names:[Namez(code:'ar', value: 'أبحر الشمالية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'226', name:'Abruq Al Rughamah', names:[Namez(code:'ar', value: 'ابرق الرغامة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'227', name:'Al Ajaweed', names:[Namez(code:'ar', value: 'الاجاويد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'228', name:'Al Bsateen', names:[Namez(code:'ar', value: 'البساتين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'229', name:'Al Balad', names:[Namez(code:'ar', value: 'البلد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'230', name:'AL Thagher', names:[Namez(code:'ar', value: 'الثغر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'231', name:'Al Jam’Iah', names:[Namez(code:'ar', value: 'الجامعة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'232', name:'Al Hamadaniyyah', names:[Namez(code:'ar', value: 'الحمدانية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'233', name:'Al Hamra', names:[Namez(code:'ar', value: 'الحمرا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'234', name:'Al Khaldiya', names:[Namez(code:'ar', value: 'الخالدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'235', name:'Al Rehab', names:[Namez(code:'ar', value: 'الرحاب'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'236', name:'Al Rawabi', names:[Namez(code:'ar', value: 'الروابي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'237', name:'Al Ruwais', names:[Namez(code:'ar', value: 'الرويس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'238', name:'Al Samer', names:[Namez(code:'ar', value: 'السامر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'239', name:'Al Sulymaniya', names:[Namez(code:'ar', value: 'السليمانية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'240', name:'Al Sanabel', names:[Namez(code:'ar', value: 'السنابل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'241', name:'Al Fayhaa', names:[Namez(code:'ar', value: 'الفيحاء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'242', name:'Al Mahameed', names:[Namez(code:'ar', value: 'المحاميد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'243', name:'Al Mahjar', names:[Namez(code:'ar', value: 'المحجر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'244', name:'Al Muhamdeya', names:[Namez(code:'ar', value: 'المحمدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'245', name:'Al Manar', names:[Namez(code:'ar', value: 'المنار'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'246', name:'Al Nuzhah', names:[Namez(code:'ar', value: 'النزهة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'247', name:'Al Naseem', names:[Namez(code:'ar', value: 'النسيم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'248', name:'Al Naeem', names:[Namez(code:'ar', value: 'النعيم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'249', name:'Al Nahda', names:[Namez(code:'ar', value: 'النهضة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'250', name:'Al Wazeeriyah', names:[Namez(code:'ar', value: 'الوزيرية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'251', name:'Buriman', names:[Namez(code:'ar', value: 'بريمان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'252', name:'Bani Malik', names:[Namez(code:'ar', value: 'بني مالك'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'253', name:'Tiba', names:[Namez(code:'ar', value: 'طيبة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'254', name:'Quwaizah', names:[Namez(code:'ar', value: 'قويزة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'255', name:'Mraykh', names:[Namez(code:'ar', value: 'مريخ'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'256', name:'Mishrifah', names:[Namez(code:'ar', value: 'مشرفة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'257', name:'Al Badiyah', names:[Namez(code:'ar', value: 'البادية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'258', name:'Al Rakah Al Shamaliyah', names:[Namez(code:'ar', value: 'الراكة الشمالية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'259', name:'Al Tubayshi', names:[Namez(code:'ar', value: 'الطبيشي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'260', name:'Abdullah Fouad', names:[Namez(code:'ar', value: 'عبدالله فؤاد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'261', name:'Hajar', names:[Namez(code:'ar', value: 'هجر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'262', name:'Al Muntazah', names:[Namez(code:'ar', value: 'المنتزة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'263', name:'Qasr Al Khaleej', names:[Namez(code:'ar', value: 'قصر الخليج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'264', name:'Al Nahdah', names:[Namez(code:'ar', value: 'النهضة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'265', name:'Tihamah', names:[Namez(code:'ar', value: 'تهامه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'266', name:'Uhud', names:[Namez(code:'ar', value: 'أحد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'267', name:'Al Itisalat', names:[Namez(code:'ar', value: 'الاتصالات'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'268', name:'Al Badea', names:[Namez(code:'ar', value: 'البديع'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'269', name:'Al Jamiyin', names:[Namez(code:'ar', value: 'الجامعيين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'270', name:'Al Jalawiyah', names:[Namez(code:'ar', value: 'الجلوية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'271', name:'Al Jawharah', names:[Namez(code:'ar', value: 'الجوهرة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'272', name:'Al Hamra', names:[Namez(code:'ar', value: 'الحمرا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'273', name:'Al Dana', names:[Namez(code:'ar', value: 'الدانة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'274', name:'Al Rayyan', names:[Namez(code:'ar', value: 'الريان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'275', name:'Al Zuhur', names:[Namez(code:'ar', value: 'الزهور'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'276', name:'Al Shati', names:[Namez(code:'ar', value: 'الشاطىء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'277', name:'Al Adamah', names:[Namez(code:'ar', value: 'العدامة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'278', name:'Al Aziziyah', names:[Namez(code:'ar', value: 'العزيزية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'279', name:'Al Firdaws', names:[Namez(code:'ar', value: 'الفردوس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'280', name:'Al Faisaliyah', names:[Namez(code:'ar', value: 'الفيصلية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'281', name:'Al Muhammadiyah', names:[Namez(code:'ar', value: 'المحمدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'282', name:'Al Muraikabat', names:[Namez(code:'ar', value: 'المريكبات'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'283', name:'Al Mazruiyah', names:[Namez(code:'ar', value: 'المزروعية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'284', name:'Al Nakhil', names:[Namez(code:'ar', value: 'النخيل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'285', name:'Al Nuzha', names:[Namez(code:'ar', value: 'النزهة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'286', name:'Al Nur', names:[Namez(code:'ar', value: 'النور'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'287', name:'Al Wahah', names:[Namez(code:'ar', value: 'الواحة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'288', name:'Al Rakah Al Janubiyah', names:[Namez(code:'ar', value: 'الراكة الجنوبية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'289', name:'Al Khuzama', names:[Namez(code:'ar', value: 'الخزامى'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'290', name:'Al Aziziyah', names:[Namez(code:'ar', value: 'العزيزية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'291', name:'Ishbilia', names:[Namez(code:'ar', value: 'اشبيلية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'292', name:'Al Jisr', names:[Namez(code:'ar', value: 'الجسر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'293', name:'Al Hamra', names:[Namez(code:'ar', value: 'الحمراء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'294', name:'Al Khobar Al Janubiyah', names:[Namez(code:'ar', value: 'الخبر الجنوبية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'295', name:'Madinat Al Umal', names:[Namez(code:'ar', value: 'مدينة العمال'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'296', name:'Al Hada', names:[Namez(code:'ar', value: 'الهداء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'297', name:'Al Andalus', names:[Namez(code:'ar', value: 'الاندلس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'298', name:'Al Buhaira', names:[Namez(code:'ar', value: 'البحيرة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'299', name:'Al Bandariyah', names:[Namez(code:'ar', value: 'البندرية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'300', name:'Al Thuqbah', names:[Namez(code:'ar', value: 'الثقبة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'301', name:'Al Hizam Al Akhdar', names:[Namez(code:'ar', value: 'الحزام الاخضر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'302', name:'Al Hizam Al Thahabi', names:[Namez(code:'ar', value: 'الحزام الذهبي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'303', name:'Al Khobar Al Shamalia', names:[Namez(code:'ar', value: 'الخبر الشمالية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'304', name:'Al Rawabi', names:[Namez(code:'ar', value: 'الروابي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'305', name:'Al Aqrabiyah', names:[Namez(code:'ar', value: 'العقربية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'306', name:'Al Ulaya', names:[Namez(code:'ar', value: 'العليا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'307', name:'Al Yarmouk', names:[Namez(code:'ar', value: 'اليرموك'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'308', name:'Qurtoba', names:[Namez(code:'ar', value: 'قرطبة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Duwadimi', id:'309', name:'Al Nahdah', names:[Namez(code:'ar', value: 'النهضه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Duwadimi', id:'310', name:'Al Qudus', names:[Namez(code:'ar', value: 'القدس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Duwadimi', id:'311', name:'Al Harmin', names:[Namez(code:'ar', value: 'الحرمين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Duwadimi', id:'312', name:'Al Salam', names:[Namez(code:'ar', value: 'السلام'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Duwadimi', id:'313', name:'Al Faisaliah', names:[Namez(code:'ar', value: 'الفيصلية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Shaqra', id:'314', name:'Al Rawdah', names:[Namez(code:'ar', value: 'الخبر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Kharj', id:'315', name:'Al Rayyan', names:[Namez(code:'ar', value: 'الريان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Wadi Al Dawasir', id:'316', name:'Al Khamasin', names:[Namez(code:'ar', value: 'الخماسين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Wadi Al Dawasir', id:'317', name:'Al Lidam North', names:[Namez(code:'ar', value: 'اللدام الشمالي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Wadi Al Dawasir', id:'318', name:'Al Lidam South', names:[Namez(code:'ar', value: 'اللدام الجنوبي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Wadi Al Dawasir', id:'319', name:'Al Nuayema', names:[Namez(code:'ar', value: 'النويعمة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Wadi Al Dawasir', id:'320', name:'Al Sharafa', names:[Namez(code:'ar', value: 'الشرافاء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Wadi Al Dawasir', id:'321', name:'Al Quwayz', names:[Namez(code:'ar', value: 'القويز'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Qutaif', id:'322', name:'Al Majidiyah', names:[Namez(code:'ar', value: 'المجيدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Qutaif', id:'323', name:'Al Khamisah', names:[Namez(code:'ar', value: 'الخامسة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Qutaif', id:'324', name:'Al Khuzama', names:[Namez(code:'ar', value: 'الخزامى'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Qutaif', id:'325', name:'Al Fath', names:[Namez(code:'ar', value: 'الفتح'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Qutaif', id:'326', name:'Al Nassirah', names:[Namez(code:'ar', value: 'الناصرة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Qutaif', id:'327', name:'Al Wahah', names:[Namez(code:'ar', value: 'الواحة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Anak', id:'328', name:'Al Narjis', names:[Namez(code:'ar', value: 'النرجس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Anak', id:'329', name:'Al Mahar', names:[Namez(code:'ar', value: 'المحار'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Khamis Mushait', id:'330', name:'Al Khalidiyyah', names:[Namez(code:'ar', value: 'الخالدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Khamis Mushait', id:'331', name:'Al Nasim', names:[Namez(code:'ar', value: 'حي النسيم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Khamis Mushait', id:'332', name:'Al Aziziyah', names:[Namez(code:'ar', value: 'العزيزية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Khamis Mushait', id:'333', name:'Al Suqur', names:[Namez(code:'ar', value: 'الصقور'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Khamis Mushait', id:'334', name:'Al Nakhil', names:[Namez(code:'ar', value: 'النخيل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Khamis Mushait', id:'335', name:'Al Fath', names:[Namez(code:'ar', value: 'الفتح'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Khamis Mushait', id:'336', name:'Al Rawdah', names:[Namez(code:'ar', value: 'الروضة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Khamis Mushait', id:'337', name:'Al Sadd', names:[Namez(code:'ar', value: 'السد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Khamis Mushait', id:'338', name:'Al Sharafiyah', names:[Namez(code:'ar', value: 'الشرفية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Khamis Mushait', id:'339', name:'Shakar', names:[Namez(code:'ar', value: 'شكر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'340', name:'Al Baladiyah', names:[Namez(code:'ar', value: 'البلدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'341', name:'Abu Musa Al Ashari', names:[Namez(code:'ar', value: 'ابو موسى الاشعري'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'342', name:'Al Sinaiyah', names:[Namez(code:'ar', value: 'الصناعية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'343', name:'Al Rabi', names:[Namez(code:'ar', value: 'الربيع'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'344', name:'Al Faiha', names:[Namez(code:'ar', value: 'الفيحاء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'345', name:'Al Batin', names:[Namez(code:'ar', value: 'الباطن'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'346', name:'Al Rawdah', names:[Namez(code:'ar', value: 'الروضة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'347', name:'Al Aziziyah', names:[Namez(code:'ar', value: 'العزيزية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'348', name:'Al Masif', names:[Namez(code:'ar', value: 'المصيف'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'349', name:'Al Khalidiyah', names:[Namez(code:'ar', value: 'الخالدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'350', name:'Al Safaa', names:[Namez(code:'ar', value: 'الصفاء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'351', name:'Al Muhammadiyah', names:[Namez(code:'ar', value: 'المحمدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'352', name:'Al Muruj', names:[Namez(code:'ar', value: 'المروج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'353', name:'Al Wahah', names:[Namez(code:'ar', value: 'الواحة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'354', name:'Fulaij', names:[Namez(code:'ar', value: 'فليج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'355', name:'Prince Mishal District', names:[Namez(code:'ar', value: 'حي الامير مشعل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'356', name:'Al Khalidiyyah', names:[Namez(code:'ar', value: 'الخالدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'357', name:'Al Mukhayyam', names:[Namez(code:'ar', value: 'المخيم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'358', name:'Al Faisaliah', names:[Namez(code:'ar', value: 'الفيصلية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'359', name:'Housing Of Interior Security Forces', names:[Namez(code:'ar', value: 'الاسكان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'360', name:'Al Athaybah', names:[Namez(code:'ar', value: 'الأثايبة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'361', name:'Dahdah', names:[Namez(code:'ar', value: 'دحضه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'362', name:'Northern Al Fahd', names:[Namez(code:'ar', value: 'شمال الفهد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'363', name:'Al Fahd', names:[Namez(code:'ar', value: 'الفهد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'364', name:'Aba Lasaud', names:[Namez(code:'ar', value: 'ابا لسعود'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'365', name:'Al Amlah', names:[Namez(code:'ar', value: 'الاملاح'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'366', name:'Al Jurbah', names:[Namez(code:'ar', value: 'الجربه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'367', name:'Al Dubat', names:[Namez(code:'ar', value: 'الضباط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'368', name:'Al Qabil', names:[Namez(code:'ar', value: 'القابل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'369', name:'Sharq Al Dubat', names:[Namez(code:'ar', value: 'شرق الضباط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'370', name:'Shamal Al Dubat', names:[Namez(code:'ar', value: 'شمال الضباط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'371', name:'Al Sharaei', names:[Namez(code:'ar', value: 'الشرائع'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'372', name:'Al Rashidiyyah', names:[Namez(code:'ar', value: 'الراشدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'373', name:'Al Juranah', names:[Namez(code:'ar', value: 'الجعرانة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'374', name:'Al Usaylah', names:[Namez(code:'ar', value: 'العسيلة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'375', name:'Wadi Jalil', names:[Namez(code:'ar', value: 'وادي جليل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'376', name:'Jabal Al Nour', names:[Namez(code:'ar', value: 'جبل النور'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'377', name:'Al Khansa', names:[Namez(code:'ar', value: 'الخنساء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'378', name:'Al Adel', names:[Namez(code:'ar', value: 'العدل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'379', name:'Al Khadra', names:[Namez(code:'ar', value: 'الخضراء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'380', name:'Al Buhayrat', names:[Namez(code:'ar', value: 'البحيرات'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'381', name:'Al Bibyan', names:[Namez(code:'ar', value: 'البيبان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'382', name:'Al Tanim', names:[Namez(code:'ar', value: 'التنعيم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'383', name:'Al Taysir', names:[Namez(code:'ar', value: 'التيسير'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'384', name:'Al Hujun', names:[Namez(code:'ar', value: 'الحجون'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'385', name:'Al Hamra & Um Al Jud', names:[Namez(code:'ar', value: 'الحمراء و أم الجود'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'386', name:'Al Khalidiya', names:[Namez(code:'ar', value: 'الخالدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'387', name:'Al Rusayfah', names:[Namez(code:'ar', value: 'الرصيفة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'388', name:'Al Zahir', names:[Namez(code:'ar', value: 'الزاهر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'389', name:'Al Zahra', names:[Namez(code:'ar', value: 'الزهراء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'390', name:'Al Salamah', names:[Namez(code:'ar', value: 'السلامة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'391', name:'Al Shoqiyah', names:[Namez(code:'ar', value: 'الشوقية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'392', name:'Al Diyafah', names:[Namez(code:'ar', value: 'الضيافة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'393', name:'Al Utaybiyyah', names:[Namez(code:'ar', value: 'العتيبية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'394', name:'Al Aziziyah', names:[Namez(code:'ar', value: 'العزيزية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'395', name:'Al Umrah Al Jadidah', names:[Namez(code:'ar', value: 'العمرة الجديدة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'396', name:'Al Awali', names:[Namez(code:'ar', value: 'العوالي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'397', name:'Al Kakiyyah', names:[Namez(code:'ar', value: 'الكعكية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'398', name:'Al Mansur', names:[Namez(code:'ar', value: 'المنصور'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'399', name:'Al Nuzhah', names:[Namez(code:'ar', value: 'النزهة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'400', name:'Al Nawariyah', names:[Namez(code:'ar', value: 'النوارية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'401', name:'Al Hindawiyah', names:[Namez(code:'ar', value: 'الهنداوية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'402', name:'Bathaa Quraish', names:[Namez(code:'ar', value: 'بطحاء قريش'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'403', name:'Al Laith Road', names:[Namez(code:'ar', value: 'طريق الليث'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'404', name:'Waly Al Ahd', names:[Namez(code:'ar', value: 'ولي العهد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jazan', id:'405', name:'Al Safa', names:[Namez(code:'ar', value: 'الصفا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jazan', id:'406', name:'Al Rawdah', names:[Namez(code:'ar', value: 'الروضة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jazan', id:'407', name:'Al Suways', names:[Namez(code:'ar', value: 'السويس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jazan', id:'408', name:'Sabya', names:[Namez(code:'ar', value: 'صبيا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jazan', id:'409', name:'Abu Arish', names:[Namez(code:'ar', value: 'أبو عريش'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dhahran', id:'410', name:'Dana Al Shamaliah', names:[Namez(code:'ar', value: 'الدانة الشمالية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dhahran', id:'411', name:'Dana Al Janubiyah', names:[Namez(code:'ar', value: 'الدانة الجنوبية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dhahran', id:'412', name:'Doha Al Shamaliah', names:[Namez(code:'ar', value: 'الدوحة الشمالية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dhahran', id:'413', name:'Doha Al Janubiyah', names:[Namez(code:'ar', value: 'الدوحة الجنوبية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dhahran', id:'414', name:'Al Jameah', names:[Namez(code:'ar', value: 'الجامعة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dhahran', id:'415', name:'Al Qusur', names:[Namez(code:'ar', value: 'القصور'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dhahran', id:'416', name:'Tihamah', names:[Namez(code:'ar', value: 'تهـامة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'417', name:'Um Khalid', names:[Namez(code:'ar', value: 'ام خالد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'418', name:'Al Aziziyyah', names:[Namez(code:'ar', value: 'العزيزيه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'419', name:'Dhul Hulaifah', names:[Namez(code:'ar', value: 'ذو الحليفه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'420', name:'Abu Kabir', names:[Namez(code:'ar', value: 'ابو كبير'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'421', name:'Al Faisaliyyah', names:[Namez(code:'ar', value: 'الفيصلية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'422', name:'Al Jameiah', names:[Namez(code:'ar', value: 'حي الجامعة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'423', name:'Al Salam', names:[Namez(code:'ar', value: 'السلام'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'424', name:'Al Aqeeq', names:[Namez(code:'ar', value: 'العقيق'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'425', name:'Al Shefa', names:[Namez(code:'ar', value: 'الشفا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'426', name:'Al Khalidiyyah', names:[Namez(code:'ar', value: 'الخالدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'427', name:'Al Difa', names:[Namez(code:'ar', value: 'الدفاع'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'428', name:'Al Rayah', names:[Namez(code:'ar', value: 'الراية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'429', name:'Al Aridh', names:[Namez(code:'ar', value: 'العريض'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'430', name:'Al Usbah', names:[Namez(code:'ar', value: 'العصبة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'431', name:'Al Anabis', names:[Namez(code:'ar', value: 'العنابس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'432', name:'Al Fath', names:[Namez(code:'ar', value: 'الفتح'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'433', name:'Al Mughaisilah', names:[Namez(code:'ar', value: 'المغيسلة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'434', name:'Al Wabra', names:[Namez(code:'ar', value: 'الوبرة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'435', name:'Bani Muawiyah', names:[Namez(code:'ar', value: 'بني معاوية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'436', name:'Bir Uthman', names:[Namez(code:'ar', value: 'بئر عثمان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'437', name:'Qurban', names:[Namez(code:'ar', value: 'قربان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Ehsaa', id:'438', name:'Al Hulaylah', names:[Namez(code:'ar', value: 'الحليلة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Ehsaa', id:'439', name:'Al Mubarraz', names:[Namez(code:'ar', value: 'المبرز'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Ehsaa', id:'440', name:'Al Hofuf', names:[Namez(code:'ar', value: 'الهفوف'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Ehsaa', id:'441', name:'Madinat Al Jafr', names:[Namez(code:'ar', value: 'مدينة الجفر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'442', name:'Al Muntazah', names:[Namez(code:'ar', value: 'المنتزة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'443', name:'Al Nahdah', names:[Namez(code:'ar', value: 'النهضة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'444', name:'Al Quway', names:[Namez(code:'ar', value: 'القويع'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'445', name:'Al Safra', names:[Namez(code:'ar', value: 'حي الصفراء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'446', name:'Al Qadissya', names:[Namez(code:'ar', value: 'القادسية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'447', name:'Al Shamas', names:[Namez(code:'ar', value: 'الشماس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'448', name:'Al Amn', names:[Namez(code:'ar', value: 'الأمن'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'449', name:'Al Nour', names:[Namez(code:'ar', value: 'النور'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'450', name:'Al Taleem', names:[Namez(code:'ar', value: 'التعليم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'451', name:'Al Iskan', names:[Namez(code:'ar', value: 'الاسكان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'452', name:'Al Ofoq', names:[Namez(code:'ar', value: 'الأفق'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'453', name:'Al Janoub', names:[Namez(code:'ar', value: 'الجنوب'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'454', name:'Al Rawda', names:[Namez(code:'ar', value: 'الروضة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'455', name:'Al Rayan', names:[Namez(code:'ar', value: 'الريان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'456', name:'Al Sadah', names:[Namez(code:'ar', value: 'السادة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'457', name:'Al Salhiyah', names:[Namez(code:'ar', value: 'الصالحية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'458', name:'Al Fayziyyah', names:[Namez(code:'ar', value: 'الفايزية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'459', name:'Al Manar', names:[Namez(code:'ar', value: 'المنار'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'460', name:'Al Sulimaniyah', names:[Namez(code:'ar', value: 'السليمانية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'461', name:'Al Mazadah', names:[Namez(code:'ar', value: 'المزادة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'462', name:'Al Salhiyah', names:[Namez(code:'ar', value: 'الصالحية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'463', name:'Al Shuraymiyyah', names:[Namez(code:'ar', value: 'الشريمية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'464', name:'Al Fakhrya', names:[Namez(code:'ar', value: 'الفاخرية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'465', name:'Al Manar', names:[Namez(code:'ar', value: 'المنار'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'466', name:'Al Ashrafyah', names:[Namez(code:'ar', value: 'الأشرفية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'467', name:'Al Khuzama', names:[Namez(code:'ar', value: 'الخزامى'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'468', name:'Al Olaya', names:[Namez(code:'ar', value: 'العليا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'469', name:'Al Badya', names:[Namez(code:'ar', value: 'البديعة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'470', name:'Al Rayan', names:[Namez(code:'ar', value: 'الريان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'471', name:'Al Faidha', names:[Namez(code:'ar', value: 'الفيضة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'472', name:'Al Qadisiyah', names:[Namez(code:'ar', value: 'القادسية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'473', name:'Al Matar', names:[Namez(code:'ar', value: 'المطار'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'474', name:'Al Nuzha', names:[Namez(code:'ar', value: 'النزهة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'475', name:'Al Hadaa', names:[Namez(code:'ar', value: 'الهداء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'476', name:'Sultanah', names:[Namez(code:'ar', value: 'سلطانة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'477', name:'Shaikhah', names:[Namez(code:'ar', value: 'شيخة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hail', id:'478', name:'Al Khuzama', names:[Namez(code:'ar', value: 'الخزامي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hail', id:'479', name:'Al Wusayta', names:[Namez(code:'ar', value: 'الوسيطاء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hail', id:'480', name:'Al Mahattah', names:[Namez(code:'ar', value: 'المحطة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hail', id:'481', name:'Al Zahra', names:[Namez(code:'ar', value: 'الزهراء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hail', id:'482', name:'Al Aziziyah', names:[Namez(code:'ar', value: 'العزيزية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hail', id:'483', name:'Al Masyaf', names:[Namez(code:'ar', value: 'المصيف'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hail', id:'484', name:'Al Zibarah', names:[Namez(code:'ar', value: 'الزبارة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hail', id:'485', name:'Aja', names:[Namez(code:'ar', value: 'اجا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'486', name:'Al Maashi', names:[Namez(code:'ar', value: 'المعشي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'487', name:'Al Huwaya', names:[Namez(code:'ar', value: 'الحويه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'488', name:'Qurwa', names:[Namez(code:'ar', value: 'قروي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'489', name:'Al Sharqyyah', names:[Namez(code:'ar', value: 'الشرقية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'490', name:'Wadi Waj', names:[Namez(code:'ar', value: 'وادي وج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'491', name:'Shihar', names:[Namez(code:'ar', value: 'شهار'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'492', name:'Al Jal', names:[Namez(code:'ar', value: 'الجال'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'493', name:'Jubrah', names:[Namez(code:'ar', value: 'جبره'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'494', name:'Al Aqeeq', names:[Namez(code:'ar', value: 'العقيق'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'495', name:'Al Khalidiyyah', names:[Namez(code:'ar', value: 'الخالديه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'496', name:'Al Sadad', names:[Namez(code:'ar', value: 'السداد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'497', name:'Al Salamah', names:[Namez(code:'ar', value: 'السلامه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'498', name:'Al Shuhada', names:[Namez(code:'ar', value: 'الشهداء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'499', name:'Al Aziziyyah', names:[Namez(code:'ar', value: 'العزيزيه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'500', name:'Al Mathnah', names:[Namez(code:'ar', value: 'المثناه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'501', name:'Hawaya', names:[Namez(code:'ar', value: 'حوايا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'502', name:'Nakhab', names:[Namez(code:'ar', value: 'نخب'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Abha', id:'503', name:'Mansak', names:[Namez(code:'ar', value: 'المنسك'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Abha', id:'504', name:'Al Muftaha', names:[Namez(code:'ar', value: 'المفتاحة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Abha', id:'505', name:'Al Qabil', names:[Namez(code:'ar', value: 'القابل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Abha', id:'506', name:'Al Alandalus', names:[Namez(code:'ar', value: 'الاندلس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Abha', id:'507', name:'Al Arin', names:[Namez(code:'ar', value: 'العرين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Abha', id:'508', name:'Al Marooj', names:[Namez(code:'ar', value: 'المروج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Abha', id:'509', name:'Al Nasim', names:[Namez(code:'ar', value: 'النسيم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Abha', id:'510', name:'Al Muathafein', names:[Namez(code:'ar', value: 'الموظفين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Abha', id:'511', name:'Al Dabab', names:[Namez(code:'ar', value: 'الضباب'),], isActivated: true, isPublic: false, ),
];