
import 'package:bldrs/models/planet/city_model.dart';

List<Area> dbAreas = <Area>[
  Area(iso3: 'egy', province: 'Cairo', name:'Heliopolis', names:[Namez(code:'ar', value: 'مصر الجديدة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'Nasr City', names:[Namez(code:'ar', value: 'مدينة نصر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'El-Maadi', names:[Namez(code:'ar', value: 'المعادي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'New Cairo', names:[Namez(code:'ar', value: 'التجمع'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'Hadayek El-Kobba', names:[Namez(code:'ar', value: 'حدائق القبة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'El-Obour City', names:[Namez(code:'ar', value: 'مدينة العبور'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'El-Manyal', names:[Namez(code:'ar', value: 'المنيل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'Shoubra', names:[Namez(code:'ar', value: 'شبرا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'West El-Balad', names:[Namez(code:'ar', value: 'وسط البلد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'El Salam City', names:[Namez(code:'ar', value: 'مدينة السلام'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'El-Rehab', names:[Namez(code:'ar', value: 'الرحاب'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'El-Zamalek', names:[Namez(code:'ar', value: 'الزمالك'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'El-Zaitoun', names:[Namez(code:'ar', value: 'الزيتون'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'El-Sayeda Zainab', names:[Namez(code:'ar', value: 'السيدة زينب'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'El-Shorouk', names:[Namez(code:'ar', value: 'الشروق'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'10th of Ramadan', names:[Namez(code:'ar', value: 'العاشر من رمضان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'El-Abbasia', names:[Namez(code:'ar', value: 'العباسية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'El-Kattameya', names:[Namez(code:'ar', value: 'القطامية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'El-Marg', names:[Namez(code:'ar', value: 'المرج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'El-Matareya', names:[Namez(code:'ar', value: 'المطرية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'El-Mokattam', names:[Namez(code:'ar', value: 'المقطم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'Boulaq', names:[Namez(code:'ar', value: 'بولاق'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'Hadayek El Maadi', names:[Namez(code:'ar', value: 'حدائق المعادي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'Hadayek Helwan', names:[Namez(code:'ar', value: 'حدائق حلوان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'Helwan', names:[Namez(code:'ar', value: 'حلوان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'Dar El-Salam', names:[Namez(code:'ar', value: 'دار السلام'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'Shoubra El-Kheima', names:[Namez(code:'ar', value: 'شبرا الخيمة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'Ain Shams', names:[Namez(code:'ar', value: 'عين شمس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'Badr City', names:[Namez(code:'ar', value: 'مدينة بدر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'Madinaty', names:[Namez(code:'ar', value: 'مدينتي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', name:'Masr El-Kadima', names:[Namez(code:'ar', value: 'مصر القديمة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Mahatet El-Raml', names:[Namez(code:'ar', value: 'محطة الرمل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Roshdy', names:[Namez(code:'ar', value: 'رشدي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Smouha', names:[Namez(code:'ar', value: 'سموحة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Sporting', names:[Namez(code:'ar', value: 'سبورتينج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Sidy Gaber', names:[Namez(code:'ar', value: 'سيدي جابر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Loran', names:[Namez(code:'ar', value: 'لوران'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Camp Caesar', names:[Namez(code:'ar', value: 'كامب شيزار'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'El-Ibrahimia', names:[Namez(code:'ar', value: 'الإبراهيمية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Janaklees', names:[Namez(code:'ar', value: 'جانكليس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Abou Keir', names:[Namez(code:'ar', value: 'ابو قير'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'El-Azarita', names:[Namez(code:'ar', value: 'الأزاريطه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'El-Seyouf', names:[Namez(code:'ar', value: 'السيوف'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'El-Shatby', names:[Namez(code:'ar', value: 'الشاطبي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'El-Amreya', names:[Namez(code:'ar', value: 'العامرية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'El-Agamy', names:[Namez(code:'ar', value: 'العجمي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'El-Asafra', names:[Namez(code:'ar', value: 'العصافرة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'El-Montazah', names:[Namez(code:'ar', value: 'المنتزه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'El-Mandara', names:[Namez(code:'ar', value: 'المندرة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'El-Mansheyah', names:[Namez(code:'ar', value: 'المنشية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'El-Werdeyan', names:[Namez(code:'ar', value: 'الورديان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Bakos', names:[Namez(code:'ar', value: 'باكوس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Bahary', names:[Namez(code:'ar', value: 'بحري'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Bulkly', names:[Namez(code:'ar', value: 'بولكلي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Glym', names:[Namez(code:'ar', value: 'جليم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Zizenia', names:[Namez(code:'ar', value: 'زيزينيا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Saba Basha', names:[Namez(code:'ar', value: 'سابا باشا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'San Stefano', names:[Namez(code:'ar', value: 'سان ستيفانو'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Stanley', names:[Namez(code:'ar', value: 'ستانلي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Sidy Bishr', names:[Namez(code:'ar', value: 'سيدي بشر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Fouad Street', names:[Namez(code:'ar', value: 'شارع فؤاد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Fleming', names:[Namez(code:'ar', value: 'فلمنج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Victoria', names:[Namez(code:'ar', value: 'فيكتوريا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Kafr Abdouh', names:[Namez(code:'ar', value: 'كفر عبده'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Cleopatra', names:[Namez(code:'ar', value: 'كليوباترا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'King Mariout', names:[Namez(code:'ar', value: 'كينج ماريوط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Moharam Bek', names:[Namez(code:'ar', value: 'محرم بيك'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Moustafa Kamel', names:[Namez(code:'ar', value: 'مصطفى كامل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', name:'Miamy', names:[Namez(code:'ar', value: 'ميامي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Port Said', name:'Port Said City', names:[Namez(code:'ar', value: 'مدينة بورسعيد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Port Said', name:'Port Fouad', names:[Namez(code:'ar', value: 'بورفؤاد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Suez', name:'مدينة السويس', names:[Namez(code:'ar', value: 'مدينة السويس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Damietta', name:'Damietta El Gadeeda', names:[Namez(code:'ar', value: 'مدينة دمياط الجديدة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Damietta', name:'Damietta City', names:[Namez(code:'ar', value: 'مدينة دمياط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Dakahlia', name:'Aga', names:[Namez(code:'ar', value: 'أجا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Dakahlia', name:'Belkas', names:[Namez(code:'ar', value: 'بلقاس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Dakahlia', name:'Shirbin', names:[Namez(code:'ar', value: 'شربين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Dakahlia', name:'El Senbellawein', names:[Namez(code:'ar', value: 'السنبلاوين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Dakahlia', name:'El-Mansoura', names:[Namez(code:'ar', value: 'المنصورة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Dakahlia', name:'Mit Ghamr', names:[Namez(code:'ar', value: 'ميت غمر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Sharkia', name:'Abu Hammad', names:[Namez(code:'ar', value: 'أبو حماد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Sharkia', name:'Belbes', names:[Namez(code:'ar', value: 'بلبيس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Sharkia', name:'El-Zagazig', names:[Namez(code:'ar', value: 'الزقازيق'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Sharkia', name:'Menya El-Kamh', names:[Namez(code:'ar', value: 'منيا القمح'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Sharkia', name:'Fakous', names:[Namez(code:'ar', value: 'فاقوس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Qaliubiya', name:'Shibin Al Qanater', names:[Namez(code:'ar', value: 'شبين القناطر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Qaliubiya', name:'Banha', names:[Namez(code:'ar', value: 'مركز بنها'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Qaliubiya', name:'Qalyoub', names:[Namez(code:'ar', value: 'قليوب'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Kafr El Sheikh', name:'Kafr El sheikh City', names:[Namez(code:'ar', value: 'مركز كفر الشيخ'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Gharbia', name:'Tanta', names:[Namez(code:'ar', value: 'طنطا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Gharbia', name:'Kafr El Zayat', names:[Namez(code:'ar', value: 'مركز كفر الزيات'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Gharbia', name:'Mahalla', names:[Namez(code:'ar', value: 'المحلة الكبرى'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Monoufia', name:'Ashmun', names:[Namez(code:'ar', value: 'اشمون'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Monoufia', name:'Shibin El-Kom', names:[Namez(code:'ar', value: 'شبين الكوم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Monoufia', name:'Menouf', names:[Namez(code:'ar', value: 'منوف'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Monoufia', name:'Sadat City', names:[Namez(code:'ar', value: 'مدينة السادات'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Monoufia', name:'Birket El Sabea', names:[Namez(code:'ar', value: 'بركة السبع'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Beheira', name:'Damanhur', names:[Namez(code:'ar', value: 'دمنهور'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Beheira', name:'kafr El dawar', names:[Namez(code:'ar', value: 'مركز كفر الدوار'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Ismailia', name:'El-Ismailia city', names:[Namez(code:'ar', value: 'مدينة الإسماعيلية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', name:'Dokki and Mohandessin', names:[Namez(code:'ar', value: 'الدقي والمهندسين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', name:'6th of October', names:[Namez(code:'ar', value: '6 اكتوبر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', name:'El-Haram', names:[Namez(code:'ar', value: 'الهرم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', name:'Faisal', names:[Namez(code:'ar', value: 'فيصل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', name:'El-Sheikh Zayed', names:[Namez(code:'ar', value: 'الشيخ زايد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', name:'Hadayek El-Ahram', names:[Namez(code:'ar', value: 'حدائق الأهرام'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', name:'El-Agouza', names:[Namez(code:'ar', value: 'العجوزة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', name:'New Giza', names:[Namez(code:'ar', value: 'الجيزة الجديدة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', name:'Boulaq El Dakrour', names:[Namez(code:'ar', value: 'بولاق الدكرور'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', name:'El-Badrashin', names:[Namez(code:'ar', value: 'البدراشين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', name:'El-Hawamdeya', names:[Namez(code:'ar', value: 'الحوامدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', name:'El-Ayyat', names:[Namez(code:'ar', value: 'العياط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', name:'Imbaba', names:[Namez(code:'ar', value: 'إمبابة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', name:'El-Giza square', names:[Namez(code:'ar', value: 'ميدان الجيزة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Bani Sweif', name:'Beni Suef City', names:[Namez(code:'ar', value: 'مدينة بنى سويف'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Fayoum', name:'Ibsheway', names:[Namez(code:'ar', value: 'ابشواي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Fayoum', name:'El-Fayoum city', names:[Namez(code:'ar', value: 'مدينة الفيوم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Minya', name:'El Minya City', names:[Namez(code:'ar', value: 'مركز المنيا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Minya', name:'Mallawi', names:[Namez(code:'ar', value: 'ملوي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Asyut', name:'Abnub', names:[Namez(code:'ar', value: 'ابنوب'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Asyut', name:'Dayrout', names:[Namez(code:'ar', value: 'ديروط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Asyut', name:'Manfalut', names:[Namez(code:'ar', value: 'منفلوط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Asyut', name:'Assiut city', names:[Namez(code:'ar', value: 'مركز أسيوط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Sohag', name:'Sohag City', names:[Namez(code:'ar', value: 'مدينة سوهاج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Qena', name:'Qena City', names:[Namez(code:'ar', value: 'مدينة سوهاج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Aswan', name:'Aswan City', names:[Namez(code:'ar', value: 'مدينة أسوان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Luxor', name:'Luxor City', names:[Namez(code:'ar', value: 'مدينة الاقصر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Luxor', name:'Esna', names:[Namez(code:'ar', value: 'إسنا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Red Sea', name:'Hurghada', names:[Namez(code:'ar', value: 'الغردقة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Matrouh', name:'Matrouh', names:[Namez(code:'ar', value: 'مرسى مطروح'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'South Sinai', name:'Sharm Al-Sheikh', names:[Namez(code:'ar', value: 'شرم الشيخ'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'South Sinai', name:'Al-Areish', names:[Namez(code:'ar', value: 'العريش'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'NorthCoast', name:'North Coast', names:[Namez(code:'ar', value: 'الساحل الشمالي'),], isActivated: true, isPublic: false, ),
];