
import 'package:bldrs/models/planet/country_model.dart';
import 'package:bldrs/view_brains/theme/flagz.dart';

final List<CountryModel> dbCountries = [
  CountryModel(countryISO3: 'AFG', countryISO2: 'AF', countryName: 'Afghanistan', regionID: "034", countryFlag: Flagz.Afghanistan, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'ALB', countryISO2: 'AL', countryName: 'Albania', regionID: "039", countryFlag: Flagz.Albania, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'DZA', countryISO2: 'DZ', countryName: 'Algeria', regionID: "015", countryFlag: Flagz.Algeria, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'ASM', countryISO2: 'AS', countryName: 'American Samoa', regionID: "061", countryFlag: Flagz.American_Samoa, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'AND', countryISO2: 'AD', countryName: 'Andorra', regionID: "039", countryFlag: Flagz.Andorra, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'AGO', countryISO2: 'AO', countryName: 'Angola', regionID: "017", countryFlag: Flagz.Angola, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'ATG', countryISO2: 'AG', countryName: 'Antigua And Barbuda', regionID: "029", countryFlag: Flagz.Antigua_And_Barbuda, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'ARG', countryISO2: 'AR', countryName: 'Argentina', regionID: "005", countryFlag: Flagz.Argentina, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'ARM', countryISO2: 'AM', countryName: 'Armenia', regionID: "145", countryFlag: Flagz.Armenia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'ABW', countryISO2: 'AW', countryName: 'Aruba', regionID: "029", countryFlag: Flagz.Aruba, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'AUS', countryISO2: 'AU', countryName: 'Australia', regionID: "053", countryFlag: Flagz.Australia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'AUT', countryISO2: 'AT', countryName: 'Austria', regionID: "155", countryFlag: Flagz.Austria, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'AZE', countryISO2: 'AZ', countryName: 'Azerbaijan', regionID: "145", countryFlag: Flagz.Azerbaijan, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'BHS', countryISO2: 'BS', countryName: 'Bahamas, The', regionID: "029", countryFlag: Flagz.Bahamas, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'BHR', countryISO2: 'BH', countryName: 'Bahrain', regionID: "145", countryFlag: Flagz.Bahrain, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'BGD', countryISO2: 'BD', countryName: 'Bangladesh', regionID: "034", countryFlag: Flagz.Bangladesh, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'BRB', countryISO2: 'BB', countryName: 'Barbados', regionID: "029", countryFlag: Flagz.Barbados, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'BLR', countryISO2: 'BY', countryName: 'Belarus', regionID: "151", countryFlag: Flagz.Belarus, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'BEL', countryISO2: 'BE', countryName: 'Belgium', regionID: "155", countryFlag: Flagz.Belgium, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'BLZ', countryISO2: 'BZ', countryName: 'Belize', regionID: "013", countryFlag: Flagz.Belize, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'BEN', countryISO2: 'BJ', countryName: 'Benin', regionID: "011", countryFlag: Flagz.Benin, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'BMU', countryISO2: 'BM', countryName: 'Bermuda', regionID: "021", countryFlag: Flagz.Bermuda, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'BTN', countryISO2: 'BT', countryName: 'Bhutan', regionID: "034", countryFlag: Flagz.Bhutan, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'BOL', countryISO2: 'BO', countryName: 'Bolivia', regionID: "005", countryFlag: Flagz.Bolivia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'BIH', countryISO2: 'BA', countryName: 'Bosnia And Herzegovina', regionID: "039", countryFlag: Flagz.Bosnia_And_Herzegovina, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'BWA', countryISO2: 'BW', countryName: 'Botswana', regionID: "018", countryFlag: Flagz.Botswana, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'BRA', countryISO2: 'BR', countryName: 'Brazil', regionID: "005", countryFlag: Flagz.Brazil, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'BRN', countryISO2: 'BN', countryName: 'Brunei', regionID: "035", countryFlag: Flagz.Brunei, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'BGR', countryISO2: 'BG', countryName: 'Bulgaria', regionID: "151", countryFlag: Flagz.Bulgaria, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'BFA', countryISO2: 'BF', countryName: 'Burkina Faso', regionID: "011", countryFlag: Flagz.Burkina_Faso, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'MMR', countryISO2: 'MM', countryName: 'Burma', regionID: "035", countryFlag: Flagz.Myanmar, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'BDI', countryISO2: 'BI', countryName: 'Burundi', regionID: "014", countryFlag: Flagz.Burundi, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'CPV', countryISO2: 'CV', countryName: 'Cabo Verde', regionID: "011", countryFlag: Flagz.Cape_Verde, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'KHM', countryISO2: 'KH', countryName: 'Cambodia', regionID: "035", countryFlag: Flagz.Cambodia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'CMR', countryISO2: 'CM', countryName: 'Cameroon', regionID: "017", countryFlag: Flagz.Cameroon, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'CAN', countryISO2: 'CA', countryName: 'Canada', regionID: "021", countryFlag: Flagz.Canada, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'CYM', countryISO2: 'KY', countryName: 'Cayman Islands', regionID: "029", countryFlag: Flagz.Cayman_Islands, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'CAF', countryISO2: 'CF', countryName: 'Central African Republic', regionID: "017", countryFlag: Flagz.Central_African_Republic, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'TCD', countryISO2: 'TD', countryName: 'Chad', regionID: "017", countryFlag: Flagz.Chad, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'CHL', countryISO2: 'CL', countryName: 'Chile', regionID: "005", countryFlag: Flagz.Chile, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'CHN', countryISO2: 'CN', countryName: 'China', regionID: "030", countryFlag: Flagz.China, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'COL', countryISO2: 'CO', countryName: 'Colombia', regionID: "005", countryFlag: Flagz.Colombia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'COM', countryISO2: 'KM', countryName: 'Comoros', regionID: "014", countryFlag: Flagz.Comoros, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'COG', countryISO2: 'CG', countryName: 'Congo (Brazzaville)', regionID: "017", countryFlag: Flagz.Congo, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'COD', countryISO2: 'CD', countryName: 'Congo (Kinshasa)', regionID: "017", countryFlag: Flagz.Congo2, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'COK', countryISO2: 'CK', countryName: 'Cook Islands', regionID: "061", countryFlag: Flagz.Cook_Islands, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'CRI', countryISO2: 'CR', countryName: 'Costa Rica', regionID: "013", countryFlag: Flagz.Costa_Rica, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'CIV', countryISO2: 'CI', countryName: 'Côte D’Ivoire', regionID: "011", countryFlag: Flagz.Cote_Divoire, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'HRV', countryISO2: 'HR', countryName: 'Croatia', regionID: "039", countryFlag: Flagz.Croatia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'CUB', countryISO2: 'CU', countryName: 'Cuba', regionID: "029", countryFlag: Flagz.Cuba, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'CUW', countryISO2: 'CW', countryName: 'Curaçao', regionID: "029", countryFlag: Flagz.Curacao, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'CYP', countryISO2: 'CY', countryName: 'Cyprus', regionID: "145", countryFlag: Flagz.Cyprus, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'CZE', countryISO2: 'CZ', countryName: 'Czechia', regionID: "151", countryFlag: Flagz.Czech_Republic, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'DNK', countryISO2: 'DK', countryName: 'Denmark', regionID: "154", countryFlag: Flagz.Denmark, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'DJI', countryISO2: 'DJ', countryName: 'Djibouti', regionID: "014", countryFlag: Flagz.Djibouti, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'DMA', countryISO2: 'DM', countryName: 'Dominica', regionID: "029", countryFlag: Flagz.Dominica, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'DOM', countryISO2: 'DO', countryName: 'Dominican Republic', regionID: "029", countryFlag: Flagz.Dominican_Republic, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'ECU', countryISO2: 'EC', countryName: 'Ecuador', regionID: "005", countryFlag: Flagz.Ecuador, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'EGY', countryISO2: 'EG', countryName: 'Egypt', regionID: "015", countryFlag: Flagz.Egypt, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'SLV', countryISO2: 'SV', countryName: 'El Salvador', regionID: "013", countryFlag: Flagz.El_Salvador, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'GNQ', countryISO2: 'GQ', countryName: 'Equatorial Guinea', regionID: "017", countryFlag: Flagz.Equatorial_Guinea, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'ERI', countryISO2: 'ER', countryName: 'Eritrea', regionID: "014", countryFlag: Flagz.Eritrea, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'EST', countryISO2: 'EE', countryName: 'Estonia', regionID: "154", countryFlag: Flagz.Estonia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'ETH', countryISO2: 'ET', countryName: 'Ethiopia', regionID: "014", countryFlag: Flagz.Ethiopia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'FLK', countryISO2: 'FK', countryName: 'Falkland Islands (Islas Malvinas)', regionID: "005", countryFlag: Flagz.Falkland_Islands, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'FRO', countryISO2: 'FO', countryName: 'Faroe Islands', regionID: "154", countryFlag: Flagz.Faroe_Islands, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'FJI', countryISO2: 'FJ', countryName: 'Fiji', regionID: "054", countryFlag: Flagz.Fiji, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'FIN', countryISO2: 'FI', countryName: 'Finland', regionID: "154", countryFlag: Flagz.Finland, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'FRA', countryISO2: 'FR', countryName: 'France', regionID: "155", countryFlag: Flagz.France, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'GUF', countryISO2: 'GF', countryName: 'French Guiana', regionID: "005", countryFlag: Flagz.French_Guiana, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'PYF', countryISO2: 'PF', countryName: 'French Polynesia', regionID: "061", countryFlag: Flagz.French_Polynesia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'GAB', countryISO2: 'GA', countryName: 'Gabon', regionID: "017", countryFlag: Flagz.Gabon, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'GMB', countryISO2: 'GM', countryName: 'Gambia, The', regionID: "011", countryFlag: Flagz.Gambia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'GEO', countryISO2: 'GE', countryName: 'Georgia', regionID: "145", countryFlag: Flagz.Georgia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'DEU', countryISO2: 'DE', countryName: 'Germany', regionID: "155", countryFlag: Flagz.Germany, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'GHA', countryISO2: 'GH', countryName: 'Ghana', regionID: "011", countryFlag: Flagz.Ghana, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'GIB', countryISO2: 'GI', countryName: 'Gibraltar', regionID: "039", countryFlag: Flagz.Gibraltar, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'GRC', countryISO2: 'GR', countryName: 'Greece', regionID: "039", countryFlag: Flagz.Greece, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'GRL', countryISO2: 'GL', countryName: 'Greenland', regionID: "021", countryFlag: Flagz.Greenland, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'GRD', countryISO2: 'GD', countryName: 'Grenada', regionID: "029", countryFlag: Flagz.Grenada, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'GLP', countryISO2: 'GP', countryName: 'Guadeloupe', regionID: "029", countryFlag: Flagz.Guadeloupe, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'GUM', countryISO2: 'GU', countryName: 'Guam', regionID: "057", countryFlag: Flagz.Guam, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'GTM', countryISO2: 'GT', countryName: 'Guatemala', regionID: "013", countryFlag: Flagz.Guatemala, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'GIN', countryISO2: 'GN', countryName: 'Guinea', regionID: "011", countryFlag: Flagz.Guinea, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'GNB', countryISO2: 'GW', countryName: 'Guinea-Bissau', regionID: "011", countryFlag: Flagz.Guinea_Bissau, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'GUY', countryISO2: 'GY', countryName: 'Guyana', regionID: "005", countryFlag: Flagz.Guyana, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'HTI', countryISO2: 'HT', countryName: 'Haiti', regionID: "029", countryFlag: Flagz.Haiti, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'HND', countryISO2: 'HN', countryName: 'Honduras', regionID: "013", countryFlag: Flagz.Honduras, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'HKG', countryISO2: 'HK', countryName: 'Hong Kong', regionID: "030", countryFlag: Flagz.Hong_Kong, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'HUN', countryISO2: 'HU', countryName: 'Hungary', regionID: "151", countryFlag: Flagz.Hungary, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'ISL', countryISO2: 'IS', countryName: 'Iceland', regionID: "154", countryFlag: Flagz.Iceland, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'IND', countryISO2: 'IN', countryName: 'India', regionID: "034", countryFlag: Flagz.India, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'IDN', countryISO2: 'ID', countryName: 'Indonesia', regionID: "035", countryFlag: Flagz.Indonesia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'IRN', countryISO2: 'IR', countryName: 'Iran', regionID: "034", countryFlag: Flagz.Iran, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'IRQ', countryISO2: 'IQ', countryName: 'Iraq', regionID: "145", countryFlag: Flagz.Iraq, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'IRL', countryISO2: 'IE', countryName: 'Ireland', regionID: "154", countryFlag: Flagz.Ireland, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'IMN', countryISO2: 'IM', countryName: 'Isle Of Man', regionID: "154", countryFlag: Flagz.Isle_Of_Man, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'ISR', countryISO2: 'IL', countryName: 'Israel', regionID: "145", countryFlag: Flagz.Israel, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'ITA', countryISO2: 'IT', countryName: 'Italy', regionID: "039", countryFlag: Flagz.Italy, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'JAM', countryISO2: 'JM', countryName: 'Jamaica', regionID: "029", countryFlag: Flagz.Jamaica, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'JPN', countryISO2: 'JP', countryName: 'Japan', regionID: "030", countryFlag: Flagz.Japan, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'JEY', countryISO2: 'JE', countryName: 'Jersey', regionID: "154", countryFlag: Flagz.Jersey, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'JOR', countryISO2: 'JO', countryName: 'Jordan', regionID: "145", countryFlag: Flagz.Jordan, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'KAZ', countryISO2: 'KZ', countryName: 'Kazakhstan', regionID: "143", countryFlag: Flagz.Kazakhstan, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'KEN', countryISO2: 'KE', countryName: 'Kenya', regionID: "014", countryFlag: Flagz.Kenya, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'KIR', countryISO2: 'KI', countryName: 'Kiribati', regionID: "057", countryFlag: Flagz.Kiribati, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'PRK', countryISO2: 'KP', countryName: 'Korea, North', regionID: "030", countryFlag: Flagz.North_Korea, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'KOR', countryISO2: 'KR', countryName: 'Korea, South', regionID: "030", countryFlag: Flagz.South_Korea, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'XKS', countryISO2: 'XK', countryName: 'Kosovo', regionID: "039", countryFlag: Flagz.Kosovo, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'KWT', countryISO2: 'KW', countryName: 'Kuwait', regionID: "145", countryFlag: Flagz.Kuwait, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'KGZ', countryISO2: 'KG', countryName: 'Kyrgyzstan', regionID: "143", countryFlag: Flagz.Kyrgyzstan, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'LAO', countryISO2: 'LA', countryName: 'Laos', regionID: "035", countryFlag: Flagz.Laos, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'LVA', countryISO2: 'LV', countryName: 'Latvia', regionID: "154", countryFlag: Flagz.Latvia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'LBN', countryISO2: 'LB', countryName: 'Lebanon', regionID: "145", countryFlag: Flagz.Lebanon, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'LSO', countryISO2: 'LS', countryName: 'Lesotho', regionID: "018", countryFlag: Flagz.Lesotho, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'LBR', countryISO2: 'LR', countryName: 'Liberia', regionID: "011", countryFlag: Flagz.Liberia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'LBY', countryISO2: 'LY', countryName: 'Libya', regionID: "015", countryFlag: Flagz.Libya, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'LIE', countryISO2: 'LI', countryName: 'Liechtenstein', regionID: "155", countryFlag: Flagz.Liechtenstein, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'LTU', countryISO2: 'LT', countryName: 'Lithuania', regionID: "154", countryFlag: Flagz.Lithuania, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'LUX', countryISO2: 'LU', countryName: 'Luxembourg', regionID: "155", countryFlag: Flagz.Luxembourg, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'MAC', countryISO2: 'MO', countryName: 'Macau', regionID: "030", countryFlag: Flagz.Macao, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'MKD', countryISO2: 'MK', countryName: 'Macedonia', regionID: "039", countryFlag: Flagz.Macedonia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'MDG', countryISO2: 'MG', countryName: 'Madagascar', regionID: "014", countryFlag: Flagz.Madagascar, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'MWI', countryISO2: 'MW', countryName: 'Malawi', regionID: "014", countryFlag: Flagz.Malawi, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'MYS', countryISO2: 'MY', countryName: 'Malaysia', regionID: "035", countryFlag: Flagz.Malaysia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'MDV', countryISO2: 'MV', countryName: 'Maldives', regionID: "034", countryFlag: Flagz.Maldives, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'MLI', countryISO2: 'ML', countryName: 'Mali', regionID: "011", countryFlag: Flagz.Mali, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'MLT', countryISO2: 'MT', countryName: 'Malta', regionID: "039", countryFlag: Flagz.Malta, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'MHL', countryISO2: 'MH', countryName: 'Marshall Islands', regionID: "057", countryFlag: Flagz.Marshall_Island, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'MTQ', countryISO2: 'MQ', countryName: 'Martinique', regionID: "029", countryFlag: Flagz.Martinique, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'MRT', countryISO2: 'MR', countryName: 'Mauritania', regionID: "011", countryFlag: Flagz.Mauritania, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'MUS', countryISO2: 'MU', countryName: 'Mauritius', regionID: "014", countryFlag: Flagz.Mauritius, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'MYT', countryISO2: 'YT', countryName: 'Mayotte', regionID: "014", countryFlag: Flagz.Mayotte, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'MEX', countryISO2: 'MX', countryName: 'Mexico', regionID: "013", countryFlag: Flagz.Mexico, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'FSM', countryISO2: 'FM', countryName: 'Micronesia, Federated States Of', regionID: "057", countryFlag: Flagz.Micronesia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'MDA', countryISO2: 'MD', countryName: 'Moldova', regionID: "151", countryFlag: Flagz.Moldova, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'MCO', countryISO2: 'MC', countryName: 'Monaco', regionID: "155", countryFlag: Flagz.Monaco, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'MNG', countryISO2: 'MN', countryName: 'Mongolia', regionID: "030", countryFlag: Flagz.Mongolia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'MNE', countryISO2: 'ME', countryName: 'Montenegro', regionID: "039", countryFlag: Flagz.Montenegro, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'MAR', countryISO2: 'MA', countryName: 'Morocco', regionID: "015", countryFlag: Flagz.Morocco, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'MOZ', countryISO2: 'MZ', countryName: 'Mozambique', regionID: "014", countryFlag: Flagz.Mozambique, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'NAM', countryISO2: 'NA', countryName: 'Namibia', regionID: "018", countryFlag: Flagz.Namibia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'NPL', countryISO2: 'NP', countryName: 'Nepal', regionID: "034", countryFlag: Flagz.Nepal, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'NLD', countryISO2: 'NL', countryName: 'Netherlands', regionID: "155", countryFlag: Flagz.Netherlands, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'NCL', countryISO2: 'NC', countryName: 'New Caledonia', regionID: "054", countryFlag: Flagz.France, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'NZL', countryISO2: 'NZ', countryName: 'New Zealand', regionID: "053", countryFlag: Flagz.New_Zealand, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'NIC', countryISO2: 'NI', countryName: 'Nicaragua', regionID: "013", countryFlag: Flagz.Nicaragua, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'NER', countryISO2: 'NE', countryName: 'Niger', regionID: "011", countryFlag: Flagz.Niger, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'NGA', countryISO2: 'NG', countryName: 'Nigeria', regionID: "011", countryFlag: Flagz.Nigeria, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'MNP', countryISO2: 'MP', countryName: 'Northern Mariana Islands', regionID: "057", countryFlag: Flagz.Northern_Marianas_Islands, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'NOR', countryISO2: 'NO', countryName: 'Norway', regionID: "154", countryFlag: Flagz.Norway, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'OMN', countryISO2: 'OM', countryName: 'Oman', regionID: "145", countryFlag: Flagz.Oman, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'PAK', countryISO2: 'PK', countryName: 'Pakistan', regionID: "034", countryFlag: Flagz.Pakistan, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'PLW', countryISO2: 'PW', countryName: 'Palau', regionID: "057", countryFlag: Flagz.Palau, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'PAN', countryISO2: 'PA', countryName: 'Panama', regionID: "013", countryFlag: Flagz.Panama, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'PNG', countryISO2: 'PG', countryName: 'Papua New Guinea', regionID: "054", countryFlag: Flagz.Papua_New_Guinea, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'PRY', countryISO2: 'PY', countryName: 'Paraguay', regionID: "005", countryFlag: Flagz.Paraguay, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'PER', countryISO2: 'PE', countryName: 'Peru', regionID: "005", countryFlag: Flagz.Peru, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'PHL', countryISO2: 'PH', countryName: 'Philippines', regionID: "035", countryFlag: Flagz.Philippines, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'POL', countryISO2: 'PL', countryName: 'Poland', regionID: "151", countryFlag: Flagz.Poland, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'PRT', countryISO2: 'PT', countryName: 'Portugal', regionID: "039", countryFlag: Flagz.Portugal, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'PRI', countryISO2: 'PR', countryName: 'Puerto Rico', regionID: "029", countryFlag: Flagz.Puerto_Rico, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'QAT', countryISO2: 'QA', countryName: 'Qatar', regionID: "145", countryFlag: Flagz.Qatar, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'REU', countryISO2: 'RE', countryName: 'Reunion', regionID: "014", countryFlag: Flagz.Reunion, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'ROU', countryISO2: 'RO', countryName: 'Romania', regionID: "151", countryFlag: Flagz.Romania, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'RUS', countryISO2: 'RU', countryName: 'Russia', regionID: "151", countryFlag: Flagz.Russia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'RWA', countryISO2: 'RW', countryName: 'Rwanda', regionID: "014", countryFlag: Flagz.Rwanda, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'SHN', countryISO2: 'SH', countryName: 'Saint Helena, Ascension, And Tristan Da Cunha', regionID: "011", countryFlag: Flagz.Saint_Helena, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'KNA', countryISO2: 'KN', countryName: 'Saint Kitts And Nevis', regionID: "029", countryFlag: Flagz.Saint_Kitts_And_Nevis, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'LCA', countryISO2: 'LC', countryName: 'Saint Lucia', regionID: "029", countryFlag: Flagz.Saint_Lucia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'VCT', countryISO2: 'VC', countryName: 'Saint Vincent And The Grenadines', regionID: "029", countryFlag: Flagz.Saint_Vincent_And_The_Grenadines, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'WSM', countryISO2: 'WS', countryName: 'Samoa', regionID: "061", countryFlag: Flagz.Samoa, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'SMR', countryISO2: 'SM', countryName: 'San Marino', regionID: "039", countryFlag: Flagz.San_Marino, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'STP', countryISO2: 'ST', countryName: 'Sao Tome And Principe', regionID: "017", countryFlag: Flagz.Sao_Tome_And_Principe, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'SAU', countryISO2: 'SA', countryName: 'Saudi Arabia', regionID: "145", countryFlag: Flagz.Saudi_Arabia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'SEN', countryISO2: 'SN', countryName: 'Senegal', regionID: "011", countryFlag: Flagz.Senegal, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'SRB', countryISO2: 'RS', countryName: 'Serbia', regionID: "039", countryFlag: Flagz.Serbia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'SYC', countryISO2: 'SC', countryName: 'Seychelles', regionID: "014", countryFlag: Flagz.Seychelles, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'SLE', countryISO2: 'SL', countryName: 'Sierra Leone', regionID: "011", countryFlag: Flagz.Sierra_Leone, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'SGP', countryISO2: 'SG', countryName: 'Singapore', regionID: "035", countryFlag: Flagz.Singapore, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'SVK', countryISO2: 'SK', countryName: 'Slovakia', regionID: "151", countryFlag: Flagz.Slovakia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'SVN', countryISO2: 'SI', countryName: 'Slovenia', regionID: "039", countryFlag: Flagz.Slovenia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'SLB', countryISO2: 'SB', countryName: 'Solomon Islands', regionID: "054", countryFlag: Flagz.Solomon_Islands, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'SOM', countryISO2: 'SO', countryName: 'Somalia', regionID: "014", countryFlag: Flagz.Somalia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'ZAF', countryISO2: 'ZA', countryName: 'South Africa', regionID: "018", countryFlag: Flagz.South_Africa, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'SGS', countryISO2: 'GS', countryName: 'South Georgia And South Sandwich Islands', regionID: "005", countryFlag: Flagz.South_Georgia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'SSD', countryISO2: 'SS', countryName: 'South Sudan', regionID: "014", countryFlag: Flagz.South_Sudan, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'ESP', countryISO2: 'ES', countryName: 'Spain', regionID: "039", countryFlag: Flagz.Spain, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'LKA', countryISO2: 'LK', countryName: 'Sri Lanka', regionID: "034", countryFlag: Flagz.Sri_Lanka, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'SDN', countryISO2: 'SD', countryName: 'Sudan', regionID: "015", countryFlag: Flagz.Sudan, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'SUR', countryISO2: 'SR', countryName: 'Suriname', regionID: "005", countryFlag: Flagz.Suriname, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'SWZ', countryISO2: 'SZ', countryName: 'Swaziland', regionID: "018", countryFlag: Flagz.Swaziland, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'SWE', countryISO2: 'SE', countryName: 'Sweden', regionID: "154", countryFlag: Flagz.Sweden, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'CHE', countryISO2: 'CH', countryName: 'Switzerland', regionID: "155", countryFlag: Flagz.Switzerland, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'SYR', countryISO2: 'SY', countryName: 'Syria', regionID: "145", countryFlag: Flagz.Syria, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'TWN', countryISO2: 'TW', countryName: 'Taiwan', regionID: "030", countryFlag: Flagz.Taiwan, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'TJK', countryISO2: 'TJ', countryName: 'Tajikistan', regionID: "143", countryFlag: Flagz.Tajikistan, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'TZA', countryISO2: 'TZ', countryName: 'Tanzania', regionID: "014", countryFlag: Flagz.Tanzania, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'THA', countryISO2: 'TH', countryName: 'Thailand', regionID: "035", countryFlag: Flagz.Thailand, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'TLS', countryISO2: 'TL', countryName: 'Timor-Leste', regionID: "035", countryFlag: Flagz.Timor_Leste, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'TGO', countryISO2: 'TG', countryName: 'Togo', regionID: "011", countryFlag: Flagz.Togo, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'TON', countryISO2: 'TO', countryName: 'Tonga', regionID: "061", countryFlag: Flagz.Tonga, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'TTO', countryISO2: 'TT', countryName: 'Trinidad And Tobago', regionID: "029", countryFlag: Flagz.Trinidad_And_Tobago, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'TUN', countryISO2: 'TN', countryName: 'Tunisia', regionID: "015", countryFlag: Flagz.Tunisia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'TUR', countryISO2: 'TR', countryName: 'Turkey', regionID: "145", countryFlag: Flagz.Turkey, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'TKM', countryISO2: 'TM', countryName: 'Turkmenistan', regionID: "143", countryFlag: Flagz.Turkmenistan, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'TCA', countryISO2: 'TC', countryName: 'Turks And Caicos Islands', regionID: "029", countryFlag: Flagz.Turks_And_Caicos, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'TUV', countryISO2: 'TV', countryName: 'Tuvalu', regionID: "061", countryFlag: Flagz.Tuvalu, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'UGA', countryISO2: 'UG', countryName: 'Uganda', regionID: "014", countryFlag: Flagz.Uganda, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'UKR', countryISO2: 'UA', countryName: 'Ukraine', regionID: "151", countryFlag: Flagz.Ukraine, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'ARE', countryISO2: 'AE', countryName: 'United Arab Emirates', regionID: "145", countryFlag: Flagz.Uae, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'GBR', countryISO2: 'GB', countryName: 'United Kingdom', regionID: "154", countryFlag: Flagz.United_Kingdom, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'USA', countryISO2: 'US', countryName: 'United States', regionID: "021", countryFlag: Flagz.USA, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'URY', countryISO2: 'UY', countryName: 'Uruguay', regionID: "005", countryFlag: Flagz.Uruguay, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'UZB', countryISO2: 'UZ', countryName: 'Uzbekistan', regionID: "143", countryFlag: Flagz.Uzbekistn, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'VUT', countryISO2: 'VU', countryName: 'Vanuatu', regionID: "054", countryFlag: Flagz.Vanuatu, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'VAT', countryISO2: 'VA', countryName: 'Vatican City', regionID: "039", countryFlag: Flagz.Vatican_City, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'VEN', countryISO2: 'VE', countryName: 'Venezuela', regionID: "005", countryFlag: Flagz.Venezuela, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'VNM', countryISO2: 'VN', countryName: 'Vietnam', regionID: "035", countryFlag: Flagz.Vietnam, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'WLF', countryISO2: 'WF', countryName: 'Wallis And Futuna', regionID: "061", countryFlag: Flagz.France, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'XWB', countryISO2: 'XW', countryName: 'Palestine', regionID: "145", countryFlag: Flagz.Palestine, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'YEM', countryISO2: 'YE', countryName: 'Yemen', regionID: "145", countryFlag: Flagz.Yemen, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'ZMB', countryISO2: 'ZM', countryName: 'Zambia', regionID: "014", countryFlag: Flagz.Zambia, countryIsActivated: true, countryWentGlobal: true),
  CountryModel(countryISO3: 'ZWE', countryISO2: 'ZW', countryName: 'Zimbabwe', regionID: "014", countryFlag: Flagz.Zimbabwe, countryIsActivated: true, countryWentGlobal: true),
];
