import 'package:bldrs/models/planet/country_model.dart';
import 'package:bldrs/view_brains/theme/flagz.dart';

final List<Country> dbCountries = [
Country(iso3: 'afg', name: 'Afghanistan', region: 'Southern Asia', continent: 'Asia', flag: Flagz.afg, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'ala', name: 'Åland Islands', region: 'Northern Europe', continent: 'Europe', flag: Flagz.ala, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'alb', name: 'Albania', region: 'Southern Europe', continent: 'Europe', flag: Flagz.alb, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'dza', name: 'Algeria', region: 'Northern Africa', continent: 'Africa', flag: Flagz.dza, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'asm', name: 'American Samoa', region: 'Polynesia', continent: 'Oceania', flag: Flagz.asm, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'and', name: 'Andorra', region: 'Southern Europe', continent: 'Europe', flag: Flagz.and, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'ago', name: 'Angola', region: 'Middle Africa', continent: 'Africa', flag: Flagz.ago, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'aia', name: 'Anguilla', region: 'Caribbean', continent: 'South America', flag: Flagz.aia, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'ata', name: 'Antarctica', region: 'Antarctica', continent: 'Antarctica', flag: Flagz.ata, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'atg', name: 'Antigua and Barbuda', region: 'Caribbean', continent: 'South America', flag: Flagz.atg, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'arg', name: 'Argentina', region: 'South America', continent: 'South America', flag: Flagz.arg, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'arm', name: 'Armenia', region: 'Western Asia', continent: 'Asia', flag: Flagz.arm, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'abw', name: 'Aruba', region: 'Caribbean', continent: 'South America', flag: Flagz.abw, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'aus', name: 'Australia', region: 'Australia and New Zealand', continent: 'Oceania', flag: Flagz.aus, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'aut', name: 'Austria', region: 'Western Europe', continent: 'Europe', flag: Flagz.aut, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'aze', name: 'Azerbaijan', region: 'Western Asia', continent: 'Asia', flag: Flagz.aze, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'bhs', name: 'Bahamas', region: 'Caribbean', continent: 'South America', flag: Flagz.bhs, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'bhr', name: 'Bahrain', region: 'Western Asia', continent: 'Asia', flag: Flagz.bhr, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'bgd', name: 'Bangladesh', region: 'Southern Asia', continent: 'Asia', flag: Flagz.bgd, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'brb', name: 'Barbados', region: 'Caribbean', continent: 'South America', flag: Flagz.brb, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'blr', name: 'Belarus', region: 'Eastern Europe', continent: 'Europe', flag: Flagz.blr, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'bel', name: 'Belgium', region: 'Western Europe', continent: 'Europe', flag: Flagz.bel, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'blz', name: 'Belize', region: 'Central America', continent: 'South America', flag: Flagz.blz, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'ben', name: 'Benin', region: 'Western Africa', continent: 'Africa', flag: Flagz.ben, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'bmu', name: 'Bermuda', region: 'Northern America', continent: 'North America', flag: Flagz.bmu, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'btn', name: 'Bhutan', region: 'Southern Asia', continent: 'Asia', flag: Flagz.btn, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'bol', name: 'Bolivia (Plurinational State of)', region: 'South America', continent: 'South America', flag: Flagz.bol, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'bes', name: 'Bonaire, Sint Eustatius and Saba', region: 'Caribbean', continent: 'South America', flag: Flagz.bes, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'bih', name: 'Bosnia and Herzegovina', region: 'Southern Europe', continent: 'Europe', flag: Flagz.bih, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'bwa', name: 'Botswana', region: 'Southern Africa', continent: 'Africa', flag: Flagz.bwa, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'bvt', name: 'Bouvet Island', region: 'Southern Indian Ocean', continent: 'Southern Ocean', flag: Flagz.bvt, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'bra', name: 'Brazil', region: 'South America', continent: 'South America', flag: Flagz.bra, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'iot', name: 'British Indian Ocean Territory', region: 'Northern Indian Ocean', continent: 'Indian Ocean', flag: Flagz.iot, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'brn', name: 'Brunei Darussalam', region: 'South-eastern Asia', continent: 'Asia', flag: Flagz.brn, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'bgr', name: 'Bulgaria', region: 'Eastern Europe', continent: 'Europe', flag: Flagz.bgr, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'bfa', name: 'Burkina Faso', region: 'Western Africa', continent: 'Africa', flag: Flagz.bfa, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'bdi', name: 'Burundi', region: 'Eastern Africa', continent: 'Africa', flag: Flagz.bdi, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'cpv', name: 'Cabo Verde', region: 'Western Africa', continent: 'Africa', flag: Flagz.cpv, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'khm', name: 'Cambodia', region: 'South-eastern Asia', continent: 'Asia', flag: Flagz.khm, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'cmr', name: 'Cameroon', region: 'Middle Africa', continent: 'Africa', flag: Flagz.cmr, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'can', name: 'Canada', region: 'Northern America', continent: 'North America', flag: Flagz.can, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'cym', name: 'Cayman Islands', region: 'Caribbean', continent: 'South America', flag: Flagz.cym, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'caf', name: 'Central African Republic', region: 'Middle Africa', continent: 'Africa', flag: Flagz.caf, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'tcd', name: 'Chad', region: 'Middle Africa', continent: 'Africa', flag: Flagz.tcd, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'chl', name: 'Chile', region: 'South America', continent: 'South America', flag: Flagz.chl, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'chn', name: 'China', region: 'Eastern Asia', continent: 'Asia', flag: Flagz.chn, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'cxr', name: 'Christmas Island', region: 'South-eastern Asia', continent: 'Asia', flag: Flagz.cxr, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'cck', name: 'Cocos (Keeling) Islands', region: 'South-eastern Asia', continent: 'Asia', flag: Flagz.cck, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'col', name: 'Colombia', region: 'South America', continent: 'South America', flag: Flagz.col, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'com', name: 'Comoros', region: 'Eastern Africa', continent: 'Africa', flag: Flagz.com, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'cog', name: 'Congo', region: 'Middle Africa', continent: 'Africa', flag: Flagz.cog, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'cod', name: 'Congo, Democratic Republic of the', region: 'Middle Africa', continent: 'Africa', flag: Flagz.cod, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'cok', name: 'Cook Islands', region: 'Polynesia', continent: 'Oceania', flag: Flagz.cok, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'cri', name: 'Costa Rica', region: 'Central America', continent: 'South America', flag: Flagz.cri, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'civ', name: 'Côte d\'Ivoire', region: 'Western Africa', continent: 'Africa', flag: Flagz.civ, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'hrv', name: 'Croatia', region: 'Southern Europe', continent: 'Europe', flag: Flagz.hrv, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'cub', name: 'Cuba', region: 'Caribbean', continent: 'South America', flag: Flagz.cub, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'cuw', name: 'Curaçao', region: 'Caribbean', continent: 'South America', flag: Flagz.cuw, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'cyp', name: 'Cyprus', region: 'Western Asia', continent: 'Asia', flag: Flagz.cyp, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'cze', name: 'Czechia', region: 'Eastern Europe', continent: 'Europe', flag: Flagz.cze, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'dnk', name: 'Denmark', region: 'Northern Europe', continent: 'Europe', flag: Flagz.dnk, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'dji', name: 'Djibouti', region: 'Eastern Africa', continent: 'Africa', flag: Flagz.dji, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'dma', name: 'Dominica', region: 'Caribbean', continent: 'South America', flag: Flagz.dma, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'dom', name: 'Dominican Republic', region: 'Caribbean', continent: 'South America', flag: Flagz.dom, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'ecu', name: 'Ecuador', region: 'South America', continent: 'South America', flag: Flagz.ecu, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'egy', name: 'Egypt', region: 'Northern Africa', continent: 'Africa', flag: Flagz.egy, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'slv', name: 'El Salvador', region: 'Central America', continent: 'South America', flag: Flagz.slv, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'gnq', name: 'Equatorial Guinea', region: 'Middle Africa', continent: 'Africa', flag: Flagz.gnq, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'eri', name: 'Eritrea', region: 'Eastern Africa', continent: 'Africa', flag: Flagz.eri, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'est', name: 'Estonia', region: 'Northern Europe', continent: 'Europe', flag: Flagz.est, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'swz', name: 'Eswatini', region: 'Southern Africa', continent: 'Africa', flag: Flagz.swz, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'eth', name: 'Ethiopia', region: 'Eastern Africa', continent: 'Africa', flag: Flagz.eth, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'flk', name: 'Falkland Islands (Malvinas)', region: 'South America', continent: 'South America', flag: Flagz.flk, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'fro', name: 'Faroe Islands', region: 'Northern Europe', continent: 'Europe', flag: Flagz.fro, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'fji', name: 'Fiji', region: 'Melanesia', continent: 'Oceania', flag: Flagz.fji, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'fin', name: 'Finland', region: 'Northern Europe', continent: 'Europe', flag: Flagz.fin, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'fra', name: 'France', region: 'Western Europe', continent: 'Europe', flag: Flagz.fra, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'guf', name: 'French Guiana', region: 'South America', continent: 'South America', flag: Flagz.guf, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'pyf', name: 'French Polynesia', region: 'Polynesia', continent: 'Oceania', flag: Flagz.pyf, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'atf', name: 'French Southern Territories', region: 'Southern Indian Ocean', continent: 'Indian Ocean', flag: Flagz.atf, isActivated: false, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'gab', name: 'Gabon', region: 'Middle Africa', continent: 'Africa', flag: Flagz.gab, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'gmb', name: 'Gambia', region: 'Western Africa', continent: 'Africa', flag: Flagz.gmb, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'geo', name: 'Georgia', region: 'Western Asia', continent: 'Asia', flag: Flagz.geo, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'deu', name: 'Germany', region: 'Western Europe', continent: 'Europe', flag: Flagz.deu, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'gha', name: 'Ghana', region: 'Western Africa', continent: 'Africa', flag: Flagz.gha, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'gib', name: 'Gibraltar', region: 'Southern Europe', continent: 'Europe', flag: Flagz.gib, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'grc', name: 'Greece', region: 'Southern Europe', continent: 'Europe', flag: Flagz.grc, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'grl', name: 'Greenland', region: 'Northern America', continent: 'North America', flag: Flagz.grl, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'grd', name: 'Grenada', region: 'Caribbean', continent: 'South America', flag: Flagz.grd, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'glp', name: 'Guadeloupe', region: 'Caribbean', continent: 'South America', flag: Flagz.glp, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'gum', name: 'Guam', region: 'Micronesia', continent: 'Oceania', flag: Flagz.gum, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'gtm', name: 'Guatemala', region: 'Central America', continent: 'South America', flag: Flagz.gtm, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'ggy', name: 'Guernsey', region: 'Western Europe', continent: 'Europe', flag: Flagz.ggy, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'gin', name: 'Guinea', region: 'Western Africa', continent: 'Africa', flag: Flagz.gin, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'gnb', name: 'Guinea-Bissau', region: 'Western Africa', continent: 'Africa', flag: Flagz.gnb, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'guy', name: 'Guyana', region: 'South America', continent: 'South America', flag: Flagz.guy, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'hti', name: 'Haiti', region: 'Caribbean', continent: 'South America', flag: Flagz.hti, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'hmd', name: 'Heard Island and McDonald Islands', region: 'Southern Indian Ocean', continent: 'Indian Ocean', flag: Flagz.hmd, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'vat', name: 'Holy See', region: 'Southern Europe', continent: 'Europe', flag: Flagz.vat, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'hnd', name: 'Honduras', region: 'Central America', continent: 'South America', flag: Flagz.hnd, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'hkg', name: 'Hong Kong', region: 'Eastern Asia', continent: 'Asia', flag: Flagz.hkg, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'hun', name: 'Hungary', region: 'Eastern Europe', continent: 'Europe', flag: Flagz.hun, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'isl', name: 'Iceland', region: 'Northern Europe', continent: 'Europe', flag: Flagz.isl, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'ind', name: 'India', region: 'Southern Asia', continent: 'Asia', flag: Flagz.ind, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'idn', name: 'Indonesia', region: 'South-eastern Asia', continent: 'Asia', flag: Flagz.idn, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'irn', name: 'Iran (Islamic Republic of)', region: 'Southern Asia', continent: 'Asia', flag: Flagz.irn, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'irq', name: 'Iraq', region: 'Western Asia', continent: 'Asia', flag: Flagz.irq, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'irl', name: 'Ireland', region: 'Northern Europe', continent: 'Europe', flag: Flagz.irl, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'imn', name: 'Isle of Man', region: 'Northern Europe', continent: 'Europe', flag: Flagz.imn, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'isr', name: 'Israel', region: 'Western Asia', continent: 'Asia', flag: Flagz.isr, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'ita', name: 'Italy', region: 'Southern Europe', continent: 'Europe', flag: Flagz.ita, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'jam', name: 'Jamaica', region: 'Caribbean', continent: 'South America', flag: Flagz.jam, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'jpn', name: 'Japan', region: 'Eastern Asia', continent: 'Asia', flag: Flagz.jpn, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'jey', name: 'Jersey', region: 'Northern Europe', continent: 'Europe', flag: Flagz.jey, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'jor', name: 'Jordan', region: 'Western Asia', continent: 'Asia', flag: Flagz.jor, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'kaz', name: 'Kazakhstan', region: 'Central Asia', continent: 'Asia', flag: Flagz.kaz, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'ken', name: 'Kenya', region: 'Eastern Africa', continent: 'Africa', flag: Flagz.ken, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'kir', name: 'Kiribati', region: 'Micronesia', continent: 'Oceania', flag: Flagz.kir, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'prk', name: 'Korea (Democratic People\'s Republic of)', region: 'Eastern Asia', continent: 'Asia', flag: Flagz.prk, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'kor', name: 'Korea, Republic of', region: 'Eastern Asia', continent: 'Asia', flag: Flagz.kor, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'kwt', name: 'Kuwait', region: 'Western Asia', continent: 'Asia', flag: Flagz.kwt, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'kgz', name: 'Kyrgyzstan', region: 'Central Asia', continent: 'Asia', flag: Flagz.kgz, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'lao', name: 'Lao People\'s Democratic Republic', region: 'South-eastern Asia', continent: 'Asia', flag: Flagz.lao, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'lva', name: 'Latvia', region: 'Northern Europe', continent: 'Europe', flag: Flagz.lva, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'lbn', name: 'Lebanon', region: 'Western Asia', continent: 'Asia', flag: Flagz.lbn, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'lso', name: 'Lesotho', region: 'Southern Africa', continent: 'Africa', flag: Flagz.lso, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'lbr', name: 'Liberia', region: 'Western Africa', continent: 'Africa', flag: Flagz.lbr, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'lby', name: 'Libya', region: 'Northern Africa', continent: 'Africa', flag: Flagz.lby, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'lie', name: 'Liechtenstein', region: 'Western Europe', continent: 'Europe', flag: Flagz.lie, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'ltu', name: 'Lithuania', region: 'Northern Europe', continent: 'Europe', flag: Flagz.ltu, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'lux', name: 'Luxembourg', region: 'Western Europe', continent: 'Europe', flag: Flagz.lux, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'mac', name: 'Macao', region: 'Eastern Asia', continent: 'Asia', flag: Flagz.mac, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'mdg', name: 'Madagascar', region: 'Eastern Africa', continent: 'Africa', flag: Flagz.mdg, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'mwi', name: 'Malawi', region: 'Eastern Africa', continent: 'Africa', flag: Flagz.mwi, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'mys', name: 'Malaysia', region: 'South-eastern Asia', continent: 'Asia', flag: Flagz.mys, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'mdv', name: 'Maldives', region: 'Southern Asia', continent: 'Asia', flag: Flagz.mdv, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'mli', name: 'Mali', region: 'Western Africa', continent: 'Africa', flag: Flagz.mli, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'mlt', name: 'Malta', region: 'Southern Europe', continent: 'Europe', flag: Flagz.mlt, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'mhl', name: 'Marshall Islands', region: 'Micronesia', continent: 'Oceania', flag: Flagz.mhl, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'mtq', name: 'Martinique', region: 'Caribbean', continent: 'South America', flag: Flagz.mtq, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'mrt', name: 'Mauritania', region: 'Western Africa', continent: 'Africa', flag: Flagz.mrt, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'mus', name: 'Mauritius', region: 'Eastern Africa', continent: 'Africa', flag: Flagz.mus, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'myt', name: 'Mayotte', region: 'Eastern Africa', continent: 'Africa', flag: Flagz.myt, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'mex', name: 'Mexico', region: 'Central America', continent: 'South America', flag: Flagz.mex, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'fsm', name: 'Micronesia (Federated States of)', region: 'Micronesia', continent: 'Oceania', flag: Flagz.fsm, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'mda', name: 'Moldova, Republic of', region: 'Eastern Europe', continent: 'Europe', flag: Flagz.mda, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'mco', name: 'Monaco', region: 'Western Europe', continent: 'Europe', flag: Flagz.mco, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'mng', name: 'Mongolia', region: 'Eastern Asia', continent: 'Asia', flag: Flagz.mng, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'mne', name: 'Montenegro', region: 'Southern Europe', continent: 'Europe', flag: Flagz.mne, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'msr', name: 'Montserrat', region: 'Caribbean', continent: 'South America', flag: Flagz.msr, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'mar', name: 'Morocco', region: 'Northern Africa', continent: 'Africa', flag: Flagz.mar, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'moz', name: 'Mozambique', region: 'Eastern Africa', continent: 'Africa', flag: Flagz.moz, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'mmr', name: 'Myanmar', region: 'South-eastern Asia', continent: 'Asia', flag: Flagz.mmr, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'nam', name: 'Namibia', region: 'Southern Africa', continent: 'Africa', flag: Flagz.nam, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'nru', name: 'Nauru', region: 'Micronesia', continent: 'Oceania', flag: Flagz.nru, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'npl', name: 'Nepal', region: 'Southern Asia', continent: 'Asia', flag: Flagz.npl, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'nld', name: 'Netherlands', region: 'Western Europe', continent: 'Europe', flag: Flagz.nld, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'ncl', name: 'New Caledonia', region: 'Melanesia', continent: 'Oceania', flag: Flagz.ncl, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'nzl', name: 'New Zealand', region: 'Australia and New Zealand', continent: 'Oceania', flag: Flagz.nzl, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'nic', name: 'Nicaragua', region: 'Central America', continent: 'South America', flag: Flagz.nic, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'ner', name: 'Niger', region: 'Western Africa', continent: 'Africa', flag: Flagz.ner, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'nga', name: 'Nigeria', region: 'Western Africa', continent: 'Africa', flag: Flagz.nga, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'niu', name: 'Niue', region: 'Polynesia', continent: 'Oceania', flag: Flagz.niu, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'nfk', name: 'Norfolk Island', region: 'Melanesia', continent: 'Oceania', flag: Flagz.nfk, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'mkd', name: 'North Macedonia', region: 'Southern Europe', continent: 'Europe', flag: Flagz.mkd, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'mnp', name: 'Northern Mariana Islands', region: 'Micronesia', continent: 'Oceania', flag: Flagz.mnp, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'nor', name: 'Norway', region: 'Northern Europe', continent: 'Europe', flag: Flagz.nor, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'omn', name: 'Oman', region: 'Western Asia', continent: 'Asia', flag: Flagz.omn, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'pak', name: 'Pakistan', region: 'Southern Asia', continent: 'Asia', flag: Flagz.pak, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'plw', name: 'Palau', region: 'Micronesia', continent: 'Oceania', flag: Flagz.plw, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'pse', name: 'Palestine, State of', region: 'Western Asia', continent: 'Asia', flag: Flagz.pse, isActivated: true, isGlobal: false, cities: [], language: 'en'),Country(iso3: 'pan', name: 'Panama', region: 'Central America', continent: 'Asia', flag: Flagz.pan, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'png', name: 'Papua New Guinea', region: 'Melanesia', continent: 'Oceania', flag: Flagz.png, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'pry', name: 'Paraguay', region: 'South America', continent: 'South America', flag: Flagz.pry, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'per', name: 'Peru', region: 'South America', continent: 'South America', flag: Flagz.per, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'phl', name: 'Philippines', region: 'South-eastern Asia', continent: 'Asia', flag: Flagz.phl, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'pcn', name: 'Pitcairn', region: 'Polynesia', continent: 'Oceania', flag: Flagz.pcn, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'pol', name: 'Poland', region: 'Eastern Europe', continent: 'Europe', flag: Flagz.pol, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'prt', name: 'Portugal', region: 'Southern Europe', continent: 'Europe', flag: Flagz.prt, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'pri', name: 'Puerto Rico', region: 'Caribbean', continent: 'South America', flag: Flagz.pri, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'qat', name: 'Qatar', region: 'Western Asia', continent: 'Asia', flag: Flagz.qat, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'reu', name: 'Réunion', region: 'Eastern Africa', continent: 'Africa', flag: Flagz.reu, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'rou', name: 'Romania', region: 'Eastern Europe', continent: 'Europe', flag: Flagz.rou, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'rus', name: 'Russian Federation', region: 'Eastern Europe', continent: 'Europe', flag: Flagz.rus, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'rwa', name: 'Rwanda', region: 'Eastern Africa', continent: 'Africa', flag: Flagz.rwa, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'blm', name: 'Saint Barthélemy', region: 'Caribbean', continent: 'South America', flag: Flagz.blm, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'shn', name: 'Saint Helena, Ascension and Tristan da Cunha', region: 'Western Africa', continent: 'Africa', flag: Flagz.shn, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'kna', name: 'Saint Kitts and Nevis', region: 'Caribbean', continent: 'South America', flag: Flagz.kna, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'lca', name: 'Saint Lucia', region: 'Caribbean', continent: 'South America', flag: Flagz.lca, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'maf', name: 'Saint Martin (French part)', region: 'Caribbean', continent: 'South America', flag: Flagz.maf, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'spm', name: 'Saint Pierre and Miquelon', region: 'Northern America', continent: 'Northern America', flag: Flagz.spm, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'vct', name: 'Saint Vincent and the Grenadines', region: 'Caribbean', continent: 'South America', flag: Flagz.vct, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'wsm', name: 'Samoa', region: 'Polynesia', continent: 'Oceania', flag: Flagz.wsm, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'smr', name: 'San Marino', region: 'Southern Europe', continent: 'Europe', flag: Flagz.smr, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'stp', name: 'Sao Tome and Principe', region: 'Middle Africa', continent: 'Africa', flag: Flagz.stp, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'sau', name: 'Saudi Arabia', region: 'Western Asia', continent: 'Asia', flag: Flagz.sau, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'sen', name: 'Senegal', region: 'Western Africa', continent: 'Africa', flag: Flagz.sen, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'srb', name: 'Serbia', region: 'Southern Europe', continent: 'Europe', flag: Flagz.srb, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'syc', name: 'Seychelles', region: 'Eastern Africa', continent: 'Africa', flag: Flagz.syc, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'sle', name: 'Sierra Leone', region: 'Western Africa', continent: 'Africa', flag: Flagz.sle, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'sgp', name: 'Singapore', region: 'South-eastern Asia', continent: 'Asia', flag: Flagz.sgp, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'sxm', name: 'Sint Maarten (Dutch part)', region: 'Caribbean', continent: 'South America', flag: Flagz.sxm, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'svk', name: 'Slovakia', region: 'Eastern Europe', continent: 'Europe', flag: Flagz.svk, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'svn', name: 'Slovenia', region: 'Southern Europe', continent: 'Europe', flag: Flagz.svn, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'slb', name: 'Solomon Islands', region: 'Melanesia', continent: 'Oceania', flag: Flagz.slb, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'som', name: 'Somalia', region: 'Eastern Africa', continent: 'Africa', flag: Flagz.som, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'zaf', name: 'South Africa', region: 'Southern Africa', continent: 'Africa', flag: Flagz.zaf, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'sgs', name: 'South Georgia and the South Sandwich Islands', region: 'South America', continent: 'South America', flag: Flagz.sgs, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'ssd', name: 'South Sudan', region: 'Eastern Africa', continent: 'Africa', flag: Flagz.ssd, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'esp', name: 'Spain', region: 'Southern Europe', continent: 'Europe', flag: Flagz.esp, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'lka', name: 'Sri Lanka', region: 'Southern Asia', continent: 'Asia', flag: Flagz.lka, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'sdn', name: 'Sudan', region: 'Northern Africa', continent: 'Africa', flag: Flagz.sdn, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'sur', name: 'Suriname', region: 'South America', continent: 'South America', flag: Flagz.sur, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'sjm', name: 'Svalbard and Jan Mayen', region: 'Arctic Ocean', continent: 'Arctic Ocean', flag: Flagz.sjm, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'swe', name: 'Sweden', region: 'Northern Europe', continent: 'Europe', flag: Flagz.swe, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'che', name: 'Switzerland', region: 'Western Europe', continent: 'Europe', flag: Flagz.che, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'syr', name: 'Syrian Arab Republic', region: 'Western Asia', continent: 'Asia', flag: Flagz.syr, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'twn', name: 'Taiwan, Province of China', region: 'Eastern Asia', continent: 'Asia', flag: Flagz.twn, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'tjk', name: 'Tajikistan', region: 'Central Asia', continent: 'Asia', flag: Flagz.tjk, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'tza', name: 'Tanzania, United Republic of', region: 'Eastern Africa', continent: 'Africa', flag: Flagz.tza, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'tha', name: 'Thailand', region: 'South-eastern Asia', continent: 'Asia', flag: Flagz.tha, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'tls', name: 'Timor-Leste', region: 'South-eastern Asia', continent: 'Asia', flag: Flagz.tls, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'tgo', name: 'Togo', region: 'Western Africa', continent: 'Africa', flag: Flagz.tgo, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'tkl', name: 'Tokelau', region: 'Australia and New Zealand', continent: 'Oceania', flag: Flagz.tkl, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'ton', name: 'Tonga', region: 'Polynesia', continent: 'Oceania', flag: Flagz.ton, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'tto', name: 'Trinidad and Tobago', region: 'Caribbean', continent: 'South America', flag: Flagz.tto, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'tun', name: 'Tunisia', region: 'Northern Africa', continent: 'Africa', flag: Flagz.tun, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'tur', name: 'Turkey', region: 'Western Asia', continent: 'Asia', flag: Flagz.tur, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'tkm', name: 'Turkmenistan', region: 'Central Asia', continent: 'Asia', flag: Flagz.tkm, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'tca', name: 'Turks and Caicos Islands', region: 'Caribbean', continent: 'South America', flag: Flagz.tca, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'tuv', name: 'Tuvalu', region: 'Polynesia', continent: 'Oceania', flag: Flagz.tuv, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'uga', name: 'Uganda', region: 'Eastern Africa', continent: 'Africa', flag: Flagz.uga, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'ukr', name: 'Ukraine', region: 'Eastern Europe', continent: 'Europe', flag: Flagz.ukr, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'are', name: 'United Arab Emirates', region: 'Western Asia', continent: 'Asia', flag: Flagz.are, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'gbr', name: 'United Kingdom of Great Britain and Northern Ireland', region: 'Northern Europe', continent: 'Europe', flag: Flagz.gbr, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'usa', name: 'United States of America', region: 'Northern America', continent: 'North America', flag: Flagz.usa, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'umi', name: 'United States Minor Outlying Islands', region: 'Pacific Ocean', continent: 'Pacific Ocean', flag: Flagz.umi, isActivated: false, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'ury', name: 'Uruguay', region: 'South America', continent: 'South America', flag: Flagz.ury, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'uzb', name: 'Uzbekistan', region: 'Central Asia', continent: 'Asia', flag: Flagz.uzb, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'vut', name: 'Vanuatu', region: 'Melanesia', continent: 'Oceania', flag: Flagz.vut, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'ven', name: 'Venezuela (Bolivarian Republic of)', region: 'South America', continent: 'South America', flag: Flagz.ven, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'vnm', name: 'Viet Nam', region: 'South-eastern Asia', continent: 'Asia', flag: Flagz.vnm, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'vgb', name: 'Virgin Islands (British)', region: 'Caribbean', continent: 'South America', flag: Flagz.vgb, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'vir', name: 'Virgin Islands (U.S.)', region: 'Caribbean', continent: 'South America', flag: Flagz.vir, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'wlf', name: 'Wallis and Futuna', region: 'Polynesia', continent: 'Oceania', flag: Flagz.wlf, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'esh', name: 'Western Sahara', region: 'Northern Africa', continent: 'Africa', flag: Flagz.esh, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'yem', name: 'Yemen', region: 'Western Asia', continent: 'Asia', flag: Flagz.yem, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'zmb', name: 'Zambia', region: 'Eastern Africa', continent: 'Africa', flag: Flagz.zmb, isActivated: true, isGlobal: false, cities: [], language: 'en'),
Country(iso3: 'zwe', name: 'Zimbabwe', region: 'Eastern Africa', continent: 'Africa', flag: Flagz.zwe, isActivated: true, isGlobal: false, cities: [], language: 'en'),
];