import 'package:bldrs/models/planet/city_model.dart';

final List<Province> dbProvinces = <Province>[
  Province(iso3: 'egy', name: 'Cairo', names: [Namez(code: 'ar', value: 'القاهرة',),],),
  Province(iso3: 'egy', name: 'Alexandria', names: [Namez(code: 'ar', value: 'الإسكندرية',),],),
  Province(iso3: 'egy', name: 'Port Said', names: [Namez(code: 'ar', value: 'بورسعيد',),],),
  Province(iso3: 'egy', name: 'Suez', names: [Namez(code: 'ar', value: 'السويس',),],),
  Province(iso3: 'egy', name: 'Damietta', names: [Namez(code: 'ar', value: 'دمياط',),],),
  Province(iso3: 'egy', name: 'Dakahlia', names: [Namez(code: 'ar', value: 'الدقهلية',),],),
  Province(iso3: 'egy', name: 'Sharkia', names: [Namez(code: 'ar', value: 'الشرقية',),],),
  Province(iso3: 'egy', name: 'Qaliubiya', names: [Namez(code: 'ar', value: 'القليوبية',),],),
  Province(iso3: 'egy', name: 'Qaliubiya', names: [Namez(code: 'ar', value: 'القليوبية',),],),
  Province(iso3: 'egy', name: 'Kafr El Sheikh', names: [Namez(code: 'ar', value: 'كفر الشيخ',),],),
  Province(iso3: 'egy', name: 'Gharbia', names: [Namez(code: 'ar', value: 'الغربية',),],),
  Province(iso3: 'egy', name: 'Monoufia', names: [Namez(code: 'ar', value: 'المنوفية',),],),
  Province(iso3: 'egy', name: 'Beheira', names: [Namez(code: 'ar', value: 'البحيرة',),],),
  Province(iso3: 'egy', name: 'Ismailia', names: [Namez(code: 'ar', value: 'الاسماعيلية',),],),
  Province(iso3: 'egy', name: 'Giza', names: [Namez(code: 'ar', value: 'الجيزة',),],),
  Province(iso3: 'egy', name: 'Bani Sweif', names: [Namez(code: 'ar', value: 'بنى سويف',),],),
  Province(iso3: 'egy', name: 'Fayoum', names: [Namez(code: 'ar', value: 'الفيوم',),],),
  Province(iso3: 'egy', name: 'Minya', names: [Namez(code: 'ar', value: 'المنيا',),],),
  Province(iso3: 'egy', name: 'Asyut', names: [Namez(code: 'ar', value: 'أسيوط',),],),
  Province(iso3: 'egy', name: 'Sohag', names: [Namez(code: 'ar', value: 'سوهاج',),],),
  Province(iso3: 'egy', name: 'Qena', names: [Namez(code: 'ar', value: 'قنا',),],),
  Province(iso3: 'egy', name: 'Aswan', names: [Namez(code: 'ar', value: 'أسوان',),],),
  Province(iso3: 'egy', name: 'Luxor', names: [Namez(code: 'ar', value: 'الأقصر',),],),
  Province(iso3: 'egy', name: 'Red Sea', names: [Namez(code: 'ar', value: 'البحر الأحمر',),],),
  Province(iso3: 'egy', name: 'Matrouh', names: [Namez(code: 'ar', value: 'مطروح',),],),
  Province(iso3: 'egy', name: 'South Sinai', names: [Namez(code: 'ar', value: 'سيناء',),],),
  Province(iso3: 'egy', name: 'NorthCoast', names: [Namez(code: 'ar', value: 'الساحل الشمالي',),],),
  Province(iso3: 'sau', name: 'Al Riyadh', names: [Namez(code: 'ar', value: 'الرياض',),],),
  Province(iso3: 'sau', name: 'Jeddah', names: [Namez(code: 'ar', value: 'جدة',),],),
  Province(iso3: 'sau', name: 'Al Dammam', names: [Namez(code: 'ar', value: 'الدمام',),],),
  Province(iso3: 'sau', name: 'Al Khobar', names: [Namez(code: 'ar', value: 'الخبر',),],),
  Province(iso3: 'sau', name: 'Al Duwadimi', names: [Namez(code: 'ar', value: 'الدوادمي',),],),
  Province(iso3: 'sau', name: 'Shaqra', names: [Namez(code: 'ar', value: 'شقراء',),],),
  Province(iso3: 'sau', name: 'Al Kharj', names: [Namez(code: 'ar', value: 'الخرج',),],),
  Province(iso3: 'sau', name: 'Wadi Al Dawasir', names: [Namez(code: 'ar', value: 'وادي الدواسر',),],),
  Province(iso3: 'sau', name: 'Al Qutaif', names: [Namez(code: 'ar', value: 'القطيف',),],),
  Province(iso3: 'sau', name: 'Anak', names: [Namez(code: 'ar', value: 'عنك',),],),
  Province(iso3: 'sau', name: 'Khamis Mushait', names: [Namez(code: 'ar', value: 'خميس مشيط',),],),
  Province(iso3: 'sau', name: 'Hafar Al Batin', names: [Namez(code: 'ar', value: 'حفر الباطن',),],),
  Province(iso3: 'sau', name: 'Najran', names: [Namez(code: 'ar', value: 'نجران',),],),
  Province(iso3: 'sau', name: 'Makkah Al Mukarrama', names: [Namez(code: 'ar', value: 'مكة المكرمة',),],),
  Province(iso3: 'sau', name: 'Jazan', names: [Namez(code: 'ar', value: 'جازان',),],),
  Province(iso3: 'sau', name: 'Al Dhahran', names: [Namez(code: 'ar', value: 'الظهران',),],),
  Province(iso3: 'sau', name: 'Al Madina Al Munawara', names: [Namez(code: 'ar', value: 'المدينة المنورة',),],),
  Province(iso3: 'sau', name: 'Al Ehsaa', names: [Namez(code: 'ar', value: 'الاحساء',),],),
  Province(iso3: 'sau', name: 'Buraydah', names: [Namez(code: 'ar', value: 'بريدة',),],),
  Province(iso3: 'sau', name: 'Unayzah', names: [Namez(code: 'ar', value: 'عنيزه',),],),
  Province(iso3: 'sau', name: 'Hail', names: [Namez(code: 'ar', value: 'حائل',),],),
  Province(iso3: 'sau', name: 'Al Taif', names: [Namez(code: 'ar', value: 'الطائف',),],),
  Province(iso3: 'sau', name: 'Abha', names: [Namez(code: 'ar', value: 'أبها',),],),
];