import 'package:bldrs/models/planet/city_model.dart';

final List<Province> dbProvinces = <Province>[
Province(iso3: 'egy', name: 'Cairo', names: [Namez(code: 'ar', value: 'القاهرة',),],),
Province(iso3: 'egy', name: 'Alexandria', names: [Namez(code: 'ar', value: 'الإسكندرية',),],),
Province(iso3: 'egy', name: 'Port Said', names: [Namez(code: 'ar', value: 'بورسعيد',),],),
Province(iso3: 'egy', name: 'Suez', names: [Namez(code: 'ar', value: 'السويس',),],),
Province(iso3: 'egy', name: 'Damietta', names: [Namez(code: 'ar', value: 'دمياط',),],),
Province(iso3: 'egy', name: 'Dakahlia', names: [Namez(code: 'ar', value: 'الدقهلية',),],),
Province(iso3: 'egy', name: 'Sharkia', names: [Namez(code: 'ar', value: 'الشرقية',),],),
Province(iso3: 'egy', name: 'Qaliubiya', names: [Namez(code: 'ar', value: 'القليوبية',),],),
Province(iso3: 'egy', name: 'Qaliubiya', names: [Namez(code: 'ar', value: 'القليوبية',),],),
Province(iso3: 'egy', name: 'Kafr El Sheikh', names: [Namez(code: 'ar', value: 'كفر الشيخ',),],),
Province(iso3: 'egy', name: 'Gharbia', names: [Namez(code: 'ar', value: 'الغربية',),],),
Province(iso3: 'egy', name: 'Monoufia', names: [Namez(code: 'ar', value: 'المنوفية',),],),
Province(iso3: 'egy', name: 'Beheira', names: [Namez(code: 'ar', value: 'البحيرة',),],),
Province(iso3: 'egy', name: 'Ismailia', names: [Namez(code: 'ar', value: 'الاسماعيلية',),],),
Province(iso3: 'egy', name: 'Giza', names: [Namez(code: 'ar', value: 'الجيزة',),],),
Province(iso3: 'egy', name: 'Bani Sweif', names: [Namez(code: 'ar', value: 'بنى سويف',),],),
Province(iso3: 'egy', name: 'Fayoum', names: [Namez(code: 'ar', value: 'الفيوم',),],),
Province(iso3: 'egy', name: 'Minya', names: [Namez(code: 'ar', value: 'المنيا',),],),
Province(iso3: 'egy', name: 'Asyut', names: [Namez(code: 'ar', value: 'أسيوط',),],),
Province(iso3: 'egy', name: 'Sohag', names: [Namez(code: 'ar', value: 'سوهاج',),],),
Province(iso3: 'egy', name: 'Qena', names: [Namez(code: 'ar', value: 'قنا',),],),
Province(iso3: 'egy', name: 'Aswan', names: [Namez(code: 'ar', value: 'أسوان',),],),
Province(iso3: 'egy', name: 'Luxor', names: [Namez(code: 'ar', value: 'الأقصر',),],),
Province(iso3: 'egy', name: 'Red Sea', names: [Namez(code: 'ar', value: 'البحر الأحمر',),],),
Province(iso3: 'egy', name: 'Matrouh', names: [Namez(code: 'ar', value: 'مطروح',),],),
Province(iso3: 'egy', name: 'South Sinai', names: [Namez(code: 'ar', value: 'سيناء',),],),
Province(iso3: 'egy', name: 'NorthCoast', names: [Namez(code: 'ar', value: 'الساحل الشمالي',),],),
];