import 'package:bldrs/models/planet/region_model.dart';

final List<RegionModel> dbRegions = [
  RegionModel(regionID: "015", regionName: 'Northern Africa', continentID: 'AF'),
  RegionModel(regionID: "014", regionName: 'Eastern Africa', continentID: 'AF'),
  RegionModel(regionID: "017", regionName: 'Middle Africa', continentID: 'AF'),
  RegionModel(regionID: "018", regionName: 'Southern Africa', continentID: 'AF'),
  RegionModel(regionID: "011", regionName: 'Western Africa', continentID: 'AF'),
  RegionModel(regionID: "021", regionName: 'Northern America', continentID: 'NA'),
  RegionModel(regionID: "029", regionName: 'Caribbean', continentID: 'SA'),
  RegionModel(regionID: "013", regionName: 'Central America', continentID: 'SA'),
  RegionModel(regionID: "005", regionName: 'South America', continentID: 'SA'),
  RegionModel(regionID: "143", regionName: 'Central Asia', continentID: 'AS'),
  RegionModel(regionID: "030", regionName: 'Eastern Asia', continentID: 'AS'),
  RegionModel(regionID: "035", regionName: 'South-eastern Asia', continentID: 'AS'),
  RegionModel(regionID: "034", regionName: 'Southern Asia', continentID: 'AS'),
  RegionModel(regionID: "145", regionName: 'Western Asia', continentID: 'AS'),
  RegionModel(regionID: "151", regionName: 'Eastern Europe', continentID: 'EU'),
  RegionModel(regionID: "154", regionName: 'Northern Europe', continentID: 'EU'),
  RegionModel(regionID: "039", regionName: 'Southern Europe', continentID: 'EU'),
  RegionModel(regionID: "155", regionName: 'Western Europe', continentID: 'EU'),
  RegionModel(regionID: "053", regionName: 'Australia and New Zealand', continentID: 'OC'),
  RegionModel(regionID: "054", regionName: 'Melanesia', continentID: 'OC'),
  RegionModel(regionID: "057", regionName: 'Micronesia', continentID: 'OC'),
  RegionModel(regionID: "061", regionName: 'Polynesia', continentID: 'OC'),
];