import 'package:bldrs/models/planet/area_model.dart';
import 'package:bldrs/models/planet/namez_model.dart';

List<Area> geebAreasByProvince(String province){
  List<Area> _areas = new List();
  dbAreas.forEach((ar) {
    if(ar.province == province){
      _areas.add(ar);
    }
  });
  return _areas;
}

List<Area> dbAreas = <Area>[
  Area(iso3: 'egy', province: 'Cairo', id:'1', name:'Heliopolis', namez:[Namez(code:'ar', value: 'مصر الجديدة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'2', name:'Nasr City', namez:[Namez(code:'ar', value: 'مدينة نصر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'3', name:'El-Maadi', namez:[Namez(code:'ar', value: 'المعادي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'4', name:'New Cairo', namez:[Namez(code:'ar', value: 'التجمع'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'5', name:'Hadayek El-Kobba', namez:[Namez(code:'ar', value: 'حدائق القبة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'6', name:'El-Obour City', namez:[Namez(code:'ar', value: 'مدينة العبور'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'7', name:'El-Manyal', namez:[Namez(code:'ar', value: 'المنيل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'8', name:'Shoubra', namez:[Namez(code:'ar', value: 'شبرا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'9', name:'West El-Balad', namez:[Namez(code:'ar', value: 'وسط البلد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'10', name:'El Salam City', namez:[Namez(code:'ar', value: 'مدينة السلام'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'11', name:'El-Rehab', namez:[Namez(code:'ar', value: 'الرحاب'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'12', name:'El-Zamalek', namez:[Namez(code:'ar', value: 'الزمالك'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'13', name:'El-Zaitoun', namez:[Namez(code:'ar', value: 'الزيتون'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'14', name:'El-Sayeda Zainab', namez:[Namez(code:'ar', value: 'السيدة زينب'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'15', name:'El-Shorouk', namez:[Namez(code:'ar', value: 'الشروق'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'16', name:'10th of Ramadan', namez:[Namez(code:'ar', value: 'العاشر من رمضان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'17', name:'El-Abbasia', namez:[Namez(code:'ar', value: 'العباسية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'18', name:'El-Kattameya', namez:[Namez(code:'ar', value: 'القطامية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'19', name:'El-Marg', namez:[Namez(code:'ar', value: 'المرج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'20', name:'El-Matareya', namez:[Namez(code:'ar', value: 'المطرية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'21', name:'El-Mokattam', namez:[Namez(code:'ar', value: 'المقطم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'22', name:'Boulaq', namez:[Namez(code:'ar', value: 'بولاق'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'23', name:'Hadayek El Maadi', namez:[Namez(code:'ar', value: 'حدائق المعادي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'24', name:'Hadayek Helwan', namez:[Namez(code:'ar', value: 'حدائق حلوان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'25', name:'Helwan', namez:[Namez(code:'ar', value: 'حلوان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'26', name:'Dar El-Salam', namez:[Namez(code:'ar', value: 'دار السلام'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'27', name:'Shoubra El-Kheima', namez:[Namez(code:'ar', value: 'شبرا الخيمة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'28', name:'Ain Shams', namez:[Namez(code:'ar', value: 'عين شمس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'29', name:'Badr City', namez:[Namez(code:'ar', value: 'مدينة بدر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'30', name:'Madinaty', namez:[Namez(code:'ar', value: 'مدينتي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Cairo', id:'31', name:'Masr El-Kadima', namez:[Namez(code:'ar', value: 'مصر القديمة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'32', name:'Mahatet El-Raml', namez:[Namez(code:'ar', value: 'محطة الرمل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'33', name:'Roshdy', namez:[Namez(code:'ar', value: 'رشدي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'34', name:'Smouha', namez:[Namez(code:'ar', value: 'سموحة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'35', name:'Sporting', namez:[Namez(code:'ar', value: 'سبورتينج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'36', name:'Sidy Gaber', namez:[Namez(code:'ar', value: 'سيدي جابر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'37', name:'Loran', namez:[Namez(code:'ar', value: 'لوران'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'38', name:'Camp Caesar', namez:[Namez(code:'ar', value: 'كامب شيزار'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'39', name:'El-Ibrahimia', namez:[Namez(code:'ar', value: 'الإبراهيمية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'40', name:'Janaklees', namez:[Namez(code:'ar', value: 'جانكليس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'41', name:'Abou Keir', namez:[Namez(code:'ar', value: 'ابو قير'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'42', name:'El-Azarita', namez:[Namez(code:'ar', value: 'الأزاريطه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'43', name:'El-Seyouf', namez:[Namez(code:'ar', value: 'السيوف'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'44', name:'El-Shatby', namez:[Namez(code:'ar', value: 'الشاطبي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'45', name:'El-Amreya', namez:[Namez(code:'ar', value: 'العامرية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'46', name:'El-Agamy', namez:[Namez(code:'ar', value: 'العجمي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'47', name:'El-Asafra', namez:[Namez(code:'ar', value: 'العصافرة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'48', name:'El-Montazah', namez:[Namez(code:'ar', value: 'المنتزه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'49', name:'El-Mandara', namez:[Namez(code:'ar', value: 'المندرة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'50', name:'El-Mansheyah', namez:[Namez(code:'ar', value: 'المنشية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'51', name:'El-Werdeyan', namez:[Namez(code:'ar', value: 'الورديان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'52', name:'Bakos', namez:[Namez(code:'ar', value: 'باكوس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'53', name:'Bahary', namez:[Namez(code:'ar', value: 'بحري'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'54', name:'Bulkly', namez:[Namez(code:'ar', value: 'بولكلي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'55', name:'Glym', namez:[Namez(code:'ar', value: 'جليم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'56', name:'Zizenia', namez:[Namez(code:'ar', value: 'زيزينيا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'57', name:'Saba Basha', namez:[Namez(code:'ar', value: 'سابا باشا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'58', name:'San Stefano', namez:[Namez(code:'ar', value: 'سان ستيفانو'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'59', name:'Stanley', namez:[Namez(code:'ar', value: 'ستانلي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'60', name:'Sidy Bishr', namez:[Namez(code:'ar', value: 'سيدي بشر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'61', name:'Fouad Street', namez:[Namez(code:'ar', value: 'شارع فؤاد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'62', name:'Fleming', namez:[Namez(code:'ar', value: 'فلمنج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'63', name:'Victoria', namez:[Namez(code:'ar', value: 'فيكتوريا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'64', name:'Kafr Abdouh', namez:[Namez(code:'ar', value: 'كفر عبده'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'65', name:'Cleopatra', namez:[Namez(code:'ar', value: 'كليوباترا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'66', name:'King Mariout', namez:[Namez(code:'ar', value: 'كينج ماريوط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'67', name:'Moharam Bek', namez:[Namez(code:'ar', value: 'محرم بيك'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'68', name:'Moustafa Kamel', namez:[Namez(code:'ar', value: 'مصطفى كامل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Alexandria', id:'69', name:'Miamy', namez:[Namez(code:'ar', value: 'ميامي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Port Said', id:'70', name:'Port Said City', namez:[Namez(code:'ar', value: 'مدينة بورسعيد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Port Said', id:'71', name:'Port Fouad', namez:[Namez(code:'ar', value: 'بورفؤاد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Suez', id:'72', name:'مدينة السويس', namez:[Namez(code:'ar', value: 'مدينة السويس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Damietta', id:'73', name:'Damietta El Gadeeda', namez:[Namez(code:'ar', value: 'مدينة دمياط الجديدة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Damietta', id:'74', name:'Damietta City', namez:[Namez(code:'ar', value: 'مدينة دمياط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Dakahlia', id:'75', name:'Aga', namez:[Namez(code:'ar', value: 'أجا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Dakahlia', id:'76', name:'Belkas', namez:[Namez(code:'ar', value: 'بلقاس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Dakahlia', id:'77', name:'Shirbin', namez:[Namez(code:'ar', value: 'شربين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Dakahlia', id:'78', name:'El Senbellawein', namez:[Namez(code:'ar', value: 'السنبلاوين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Dakahlia', id:'79', name:'El-Mansoura', namez:[Namez(code:'ar', value: 'المنصورة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Dakahlia', id:'80', name:'Mit Ghamr', namez:[Namez(code:'ar', value: 'ميت غمر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Sharkia', id:'81', name:'Abu Hammad', namez:[Namez(code:'ar', value: 'أبو حماد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Sharkia', id:'82', name:'Belbes', namez:[Namez(code:'ar', value: 'بلبيس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Sharkia', id:'83', name:'El-Zagazig', namez:[Namez(code:'ar', value: 'الزقازيق'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Sharkia', id:'84', name:'Menya El-Kamh', namez:[Namez(code:'ar', value: 'منيا القمح'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Sharkia', id:'85', name:'Fakous', namez:[Namez(code:'ar', value: 'فاقوس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Qaliubiya', id:'86', name:'Shibin Al Qanater', namez:[Namez(code:'ar', value: 'شبين القناطر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Qaliubiya', id:'87', name:'Banha', namez:[Namez(code:'ar', value: 'مركز بنها'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Qaliubiya', id:'88', name:'Qalyoub', namez:[Namez(code:'ar', value: 'قليوب'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Kafr El Sheikh', id:'89', name:'Kafr El sheikh City', namez:[Namez(code:'ar', value: 'مركز كفر الشيخ'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Gharbia', id:'90', name:'Tanta', namez:[Namez(code:'ar', value: 'طنطا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Gharbia', id:'91', name:'Kafr El Zayat', namez:[Namez(code:'ar', value: 'مركز كفر الزيات'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Gharbia', id:'92', name:'Mahalla', namez:[Namez(code:'ar', value: 'المحلة الكبرى'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Monoufia', id:'93', name:'Ashmun', namez:[Namez(code:'ar', value: 'اشمون'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Monoufia', id:'94', name:'Shibin El-Kom', namez:[Namez(code:'ar', value: 'شبين الكوم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Monoufia', id:'95', name:'Menouf', namez:[Namez(code:'ar', value: 'منوف'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Monoufia', id:'96', name:'Sadat City', namez:[Namez(code:'ar', value: 'مدينة السادات'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Monoufia', id:'97', name:'Birket El Sabea', namez:[Namez(code:'ar', value: 'بركة السبع'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Beheira', id:'98', name:'Damanhur', namez:[Namez(code:'ar', value: 'دمنهور'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Beheira', id:'99', name:'kafr El dawar', namez:[Namez(code:'ar', value: 'مركز كفر الدوار'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Ismailia', id:'100', name:'El-Ismailia city', namez:[Namez(code:'ar', value: 'مدينة الإسماعيلية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'101', name:'Dokki and Mohandessin', namez:[Namez(code:'ar', value: 'الدقي والمهندسين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'102', name:'6th of October', namez:[Namez(code:'ar', value: '6 اكتوبر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'103', name:'El-Haram', namez:[Namez(code:'ar', value: 'الهرم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'104', name:'Faisal', namez:[Namez(code:'ar', value: 'فيصل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'105', name:'El-Sheikh Zayed', namez:[Namez(code:'ar', value: 'الشيخ زايد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'106', name:'Hadayek El-Ahram', namez:[Namez(code:'ar', value: 'حدائق الأهرام'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'107', name:'El-Agouza', namez:[Namez(code:'ar', value: 'العجوزة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'108', name:'New Giza', namez:[Namez(code:'ar', value: 'الجيزة الجديدة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'109', name:'Boulaq El Dakrour', namez:[Namez(code:'ar', value: 'بولاق الدكرور'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'110', name:'El-Badrashin', namez:[Namez(code:'ar', value: 'البدراشين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'111', name:'El-Hawamdeya', namez:[Namez(code:'ar', value: 'الحوامدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'112', name:'El-Ayyat', namez:[Namez(code:'ar', value: 'العياط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'113', name:'Imbaba', namez:[Namez(code:'ar', value: 'إمبابة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Giza', id:'114', name:'El-Giza square', namez:[Namez(code:'ar', value: 'ميدان الجيزة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Bani Sweif', id:'115', name:'Beni Suef City', namez:[Namez(code:'ar', value: 'مدينة بنى سويف'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Fayoum', id:'116', name:'Ibsheway', namez:[Namez(code:'ar', value: 'ابشواي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Fayoum', id:'117', name:'El-Fayoum city', namez:[Namez(code:'ar', value: 'مدينة الفيوم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Minya', id:'118', name:'El Minya City', namez:[Namez(code:'ar', value: 'مركز المنيا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Minya', id:'119', name:'Mallawi', namez:[Namez(code:'ar', value: 'ملوي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Asyut', id:'120', name:'Abnub', namez:[Namez(code:'ar', value: 'ابنوب'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Asyut', id:'121', name:'Dayrout', namez:[Namez(code:'ar', value: 'ديروط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Asyut', id:'122', name:'Manfalut', namez:[Namez(code:'ar', value: 'منفلوط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Asyut', id:'123', name:'Assiut city', namez:[Namez(code:'ar', value: 'مركز أسيوط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Sohag', id:'124', name:'Sohag City', namez:[Namez(code:'ar', value: 'مدينة سوهاج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Qena', id:'125', name:'Qena City', namez:[Namez(code:'ar', value: 'مدينة سوهاج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Aswan', id:'126', name:'Aswan City', namez:[Namez(code:'ar', value: 'مدينة أسوان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Luxor', id:'127', name:'Luxor City', namez:[Namez(code:'ar', value: 'مدينة الاقصر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Luxor', id:'128', name:'Esna', namez:[Namez(code:'ar', value: 'إسنا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Red Sea', id:'129', name:'Hurghada', namez:[Namez(code:'ar', value: 'الغردقة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'Matrouh', id:'130', name:'Matrouh', namez:[Namez(code:'ar', value: 'مرسى مطروح'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'South Sinai', id:'131', name:'Sharm Al-Sheikh', namez:[Namez(code:'ar', value: 'شرم الشيخ'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'South Sinai', id:'132', name:'Al-Areish', namez:[Namez(code:'ar', value: 'العريش'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'egy', province: 'NorthCoast', id:'133', name:'North Coast', namez:[Namez(code:'ar', value: 'الساحل الشمالي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'134', name:'Al Sulaimaniyah', namez:[Namez(code:'ar', value: 'السليمانية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'135', name:'King Fahad', namez:[Namez(code:'ar', value: 'الملك فهد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'136', name:'Al Worood', namez:[Namez(code:'ar', value: 'الورود'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'137', name:'Al Maseef', namez:[Namez(code:'ar', value: 'المصيف'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'138', name:'Al Muruj', namez:[Namez(code:'ar', value: 'المروج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'139', name:'Al Morsalat', namez:[Namez(code:'ar', value: 'المرسلات'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'140', name:'Al Ghadeer', namez:[Namez(code:'ar', value: 'الغدير'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'141', name:'Al Wahah', namez:[Namez(code:'ar', value: 'الواحة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'142', name:'Al Rahmaniyyah', namez:[Namez(code:'ar', value: 'الرحمانية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'143', name:'Ishbiliyah', namez:[Namez(code:'ar', value: 'اشبيلية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'144', name:'Al Izdihar', namez:[Namez(code:'ar', value: 'الازدهار'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'145', name:'Al Badiah', namez:[Namez(code:'ar', value: 'البديعة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'146', name:'Al Batha', namez:[Namez(code:'ar', value: 'البطحاء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'147', name:'Takhassusi', namez:[Namez(code:'ar', value: 'التخصصي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'148', name:'Al Taawun', namez:[Namez(code:'ar', value: 'التعاون'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'149', name:'Al Janadriyyah', namez:[Namez(code:'ar', value: 'الجنادرية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'150', name:'Al Hamra', namez:[Namez(code:'ar', value: 'الحمرا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'151', name:'Al Khaleej', namez:[Namez(code:'ar', value: 'الخليج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'152', name:'Al Diriyah', namez:[Namez(code:'ar', value: 'الدرعية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'153', name:'Al Raed', namez:[Namez(code:'ar', value: 'الرائد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'154', name:'Al Rabwah', namez:[Namez(code:'ar', value: 'الربوة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'155', name:'Al Rabie', namez:[Namez(code:'ar', value: 'الربيع'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'156', name:'Al Rawabi', namez:[Namez(code:'ar', value: 'الروابي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'157', name:'Al Rawdah', namez:[Namez(code:'ar', value: 'الروضة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'158', name:'Al Rayyan', namez:[Namez(code:'ar', value: 'الريان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'159', name:'Al  Zahrah', namez:[Namez(code:'ar', value: 'الزهرة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'160', name:'Al  Saadah', namez:[Namez(code:'ar', value: 'السعادة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'161', name:'Al Safarat', namez:[Namez(code:'ar', value: 'السفارات'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'162', name:'Al Salam', namez:[Namez(code:'ar', value: 'السلام'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'163', name:'Al Sulay', namez:[Namez(code:'ar', value: 'السلي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'164', name:'Al Suwaidi', namez:[Namez(code:'ar', value: 'السويدي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'165', name:'Al Shifa', namez:[Namez(code:'ar', value: 'الشفا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'166', name:'Al Shimaisi', namez:[Namez(code:'ar', value: 'الشميسي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'167', name:'Al Shuhada', namez:[Namez(code:'ar', value: 'الشهداء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'168', name:'Al Sahafa', namez:[Namez(code:'ar', value: 'الصحافة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'169', name:'Al Uraija', namez:[Namez(code:'ar', value: 'العريجاء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'170', name:'Al Aziziyah', namez:[Namez(code:'ar', value: 'العزيزية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'171', name:'Al Aqiq', namez:[Namez(code:'ar', value: 'العقيق'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'172', name:'Al Olaya', namez:[Namez(code:'ar', value: 'العليا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'173', name:'Al Falah', namez:[Namez(code:'ar', value: 'الفلاح'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'174', name:'Al Fayha', namez:[Namez(code:'ar', value: 'الفيحاء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'175', name:'Al Quds', namez:[Namez(code:'ar', value: 'القدس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'176', name:'Al Mohammadiyyah', namez:[Namez(code:'ar', value: 'المحمدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'177', name:'Al Murabba', namez:[Namez(code:'ar', value: 'المربع'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'178', name:'Al Marwah', namez:[Namez(code:'ar', value: 'المروة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'179', name:'Al Mashael', namez:[Namez(code:'ar', value: 'المشاعل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'180', name:'Al Maather', namez:[Namez(code:'ar', value: 'المعذر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'181', name:'Al Mathar Ash Shamali', namez:[Namez(code:'ar', value: 'المعذر الشمالي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'182', name:'Al Mughrizat', namez:[Namez(code:'ar', value: 'المغرزات'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'183', name:'Al Malaz', namez:[Namez(code:'ar', value: 'الملز'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'184', name:'Al Malqa', namez:[Namez(code:'ar', value: 'الملقا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'185', name:'Al Mutamarat', namez:[Namez(code:'ar', value: 'المؤتمرات'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'186', name:'Al Munsiyah', namez:[Namez(code:'ar', value: 'المونسية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'187', name:'Al Nadwa', namez:[Namez(code:'ar', value: 'الندوة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'188', name:'Al Narjis', namez:[Namez(code:'ar', value: 'النرجس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'189', name:'Al Nozha', namez:[Namez(code:'ar', value: 'النزهة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'190', name:'Al Naseem Al Sharqi', namez:[Namez(code:'ar', value: 'النسيم الشرقي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'191', name:'Al Naseem Al Gharbi', namez:[Namez(code:'ar', value: 'النسيم الغربي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'192', name:'Al Nadheem', namez:[Namez(code:'ar', value: 'النظيم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'193', name:'Al Nafal', namez:[Namez(code:'ar', value: 'النفل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'194', name:'Al Nahdah', namez:[Namez(code:'ar', value: 'النهضة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'195', name:'Al Wadi', namez:[Namez(code:'ar', value: 'الوادي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'196', name:'Al Wizarat', namez:[Namez(code:'ar', value: 'الوزارات'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'197', name:'Al Yasmin', namez:[Namez(code:'ar', value: 'الياسمين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'198', name:'Al Yarmuk', namez:[Namez(code:'ar', value: 'اليرموك'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'199', name:'Um Al Hammam', namez:[Namez(code:'ar', value: 'ام الحمام'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'200', name:'Hittin', namez:[Namez(code:'ar', value: 'حطين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'201', name:'Badr', namez:[Namez(code:'ar', value: 'حي بدر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'202', name:'Shubra', namez:[Namez(code:'ar', value: 'شبرا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'203', name:'Salah Al Din', namez:[Namez(code:'ar', value: 'صلاح الدين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'204', name:'Tuwaiq', namez:[Namez(code:'ar', value: 'طويق'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'205', name:'Dhahrat Laban', namez:[Namez(code:'ar', value: 'ظهرة لبن'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'206', name:'Irqah', namez:[Namez(code:'ar', value: 'عرقة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'207', name:'Okaz', namez:[Namez(code:'ar', value: 'عكاظ'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'208', name:'Ghubairah', namez:[Namez(code:'ar', value: 'غبيرة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'209', name:'Ghirnatah', namez:[Namez(code:'ar', value: 'غرناطة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'210', name:'Qurtubah', namez:[Namez(code:'ar', value: 'قرطبة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'211', name:'Laban', namez:[Namez(code:'ar', value: 'لبن'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'212', name:'Manfuhah', namez:[Namez(code:'ar', value: 'منفوحة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'213', name:'Namar', namez:[Namez(code:'ar', value: 'نمار'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Riyadh', id:'214', name:'Wadi Laban', namez:[Namez(code:'ar', value: 'وادي لبن'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'215', name:'Al Shati', namez:[Namez(code:'ar', value: 'الشاطىء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'216', name:'Al Faisaliyah', namez:[Namez(code:'ar', value: 'الفيصلية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'217', name:'Al Rawdah', namez:[Namez(code:'ar', value: 'الروضة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'218', name:'Al Salamah', namez:[Namez(code:'ar', value: 'السلامة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'219', name:'Al Safa', namez:[Namez(code:'ar', value: 'الصفا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'220', name:'Al Andalus', namez:[Namez(code:'ar', value: 'الأندلس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'221', name:'Al Marwah', namez:[Namez(code:'ar', value: 'المروة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'222', name:'Al Zahraa', namez:[Namez(code:'ar', value: 'الزهراء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'223', name:'Al Bawadi', namez:[Namez(code:'ar', value: 'البوادي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'224', name:'Obhur Al Janoobiyah', namez:[Namez(code:'ar', value: 'أبحر الجنوبية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'225', name:'Obhur Al Shamaliyah', namez:[Namez(code:'ar', value: 'أبحر الشمالية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'226', name:'Abruq Al Rughamah', namez:[Namez(code:'ar', value: 'ابرق الرغامة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'227', name:'Al Ajaweed', namez:[Namez(code:'ar', value: 'الاجاويد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'228', name:'Al Bsateen', namez:[Namez(code:'ar', value: 'البساتين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'229', name:'Al Balad', namez:[Namez(code:'ar', value: 'البلد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'230', name:'AL Thagher', namez:[Namez(code:'ar', value: 'الثغر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'231', name:'Al Jam’Iah', namez:[Namez(code:'ar', value: 'الجامعة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'232', name:'Al Hamadaniyyah', namez:[Namez(code:'ar', value: 'الحمدانية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'233', name:'Al Hamra', namez:[Namez(code:'ar', value: 'الحمرا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'234', name:'Al Khaldiya', namez:[Namez(code:'ar', value: 'الخالدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'235', name:'Al Rehab', namez:[Namez(code:'ar', value: 'الرحاب'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'236', name:'Al Rawabi', namez:[Namez(code:'ar', value: 'الروابي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'237', name:'Al Ruwais', namez:[Namez(code:'ar', value: 'الرويس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'238', name:'Al Samer', namez:[Namez(code:'ar', value: 'السامر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'239', name:'Al Sulymaniya', namez:[Namez(code:'ar', value: 'السليمانية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'240', name:'Al Sanabel', namez:[Namez(code:'ar', value: 'السنابل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'241', name:'Al Fayhaa', namez:[Namez(code:'ar', value: 'الفيحاء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'242', name:'Al Mahameed', namez:[Namez(code:'ar', value: 'المحاميد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'243', name:'Al Mahjar', namez:[Namez(code:'ar', value: 'المحجر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'244', name:'Al Muhamdeya', namez:[Namez(code:'ar', value: 'المحمدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'245', name:'Al Manar', namez:[Namez(code:'ar', value: 'المنار'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'246', name:'Al Nuzhah', namez:[Namez(code:'ar', value: 'النزهة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'247', name:'Al Naseem', namez:[Namez(code:'ar', value: 'النسيم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'248', name:'Al Naeem', namez:[Namez(code:'ar', value: 'النعيم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'249', name:'Al Nahda', namez:[Namez(code:'ar', value: 'النهضة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'250', name:'Al Wazeeriyah', namez:[Namez(code:'ar', value: 'الوزيرية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'251', name:'Buriman', namez:[Namez(code:'ar', value: 'بريمان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'252', name:'Bani Malik', namez:[Namez(code:'ar', value: 'بني مالك'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'253', name:'Tiba', namez:[Namez(code:'ar', value: 'طيبة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'254', name:'Quwaizah', namez:[Namez(code:'ar', value: 'قويزة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'255', name:'Mraykh', namez:[Namez(code:'ar', value: 'مريخ'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jeddah', id:'256', name:'Mishrifah', namez:[Namez(code:'ar', value: 'مشرفة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'257', name:'Al Badiyah', namez:[Namez(code:'ar', value: 'البادية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'258', name:'Al Rakah Al Shamaliyah', namez:[Namez(code:'ar', value: 'الراكة الشمالية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'259', name:'Al Tubayshi', namez:[Namez(code:'ar', value: 'الطبيشي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'260', name:'Abdullah Fouad', namez:[Namez(code:'ar', value: 'عبدالله فؤاد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'261', name:'Hajar', namez:[Namez(code:'ar', value: 'هجر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'262', name:'Al Muntazah', namez:[Namez(code:'ar', value: 'المنتزة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'263', name:'Qasr Al Khaleej', namez:[Namez(code:'ar', value: 'قصر الخليج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'264', name:'Al Nahdah', namez:[Namez(code:'ar', value: 'النهضة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'265', name:'Tihamah', namez:[Namez(code:'ar', value: 'تهامه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'266', name:'Uhud', namez:[Namez(code:'ar', value: 'أحد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'267', name:'Al Itisalat', namez:[Namez(code:'ar', value: 'الاتصالات'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'268', name:'Al Badea', namez:[Namez(code:'ar', value: 'البديع'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'269', name:'Al Jamiyin', namez:[Namez(code:'ar', value: 'الجامعيين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'270', name:'Al Jalawiyah', namez:[Namez(code:'ar', value: 'الجلوية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'271', name:'Al Jawharah', namez:[Namez(code:'ar', value: 'الجوهرة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'272', name:'Al Hamra', namez:[Namez(code:'ar', value: 'الحمرا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'273', name:'Al Dana', namez:[Namez(code:'ar', value: 'الدانة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'274', name:'Al Rayyan', namez:[Namez(code:'ar', value: 'الريان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'275', name:'Al Zuhur', namez:[Namez(code:'ar', value: 'الزهور'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'276', name:'Al Shati', namez:[Namez(code:'ar', value: 'الشاطىء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'277', name:'Al Adamah', namez:[Namez(code:'ar', value: 'العدامة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'278', name:'Al Aziziyah', namez:[Namez(code:'ar', value: 'العزيزية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'279', name:'Al Firdaws', namez:[Namez(code:'ar', value: 'الفردوس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'280', name:'Al Faisaliyah', namez:[Namez(code:'ar', value: 'الفيصلية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'281', name:'Al Muhammadiyah', namez:[Namez(code:'ar', value: 'المحمدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'282', name:'Al Muraikabat', namez:[Namez(code:'ar', value: 'المريكبات'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'283', name:'Al Mazruiyah', namez:[Namez(code:'ar', value: 'المزروعية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'284', name:'Al Nakhil', namez:[Namez(code:'ar', value: 'النخيل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'285', name:'Al Nuzha', namez:[Namez(code:'ar', value: 'النزهة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'286', name:'Al Nur', namez:[Namez(code:'ar', value: 'النور'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dammam', id:'287', name:'Al Wahah', namez:[Namez(code:'ar', value: 'الواحة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'288', name:'Al Rakah Al Janubiyah', namez:[Namez(code:'ar', value: 'الراكة الجنوبية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'289', name:'Al Khuzama', namez:[Namez(code:'ar', value: 'الخزامى'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'290', name:'Al Aziziyah', namez:[Namez(code:'ar', value: 'العزيزية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'291', name:'Ishbilia', namez:[Namez(code:'ar', value: 'اشبيلية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'292', name:'Al Jisr', namez:[Namez(code:'ar', value: 'الجسر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'293', name:'Al Hamra', namez:[Namez(code:'ar', value: 'الحمراء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'294', name:'Al Khobar Al Janubiyah', namez:[Namez(code:'ar', value: 'الخبر الجنوبية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'295', name:'Madinat Al Umal', namez:[Namez(code:'ar', value: 'مدينة العمال'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'296', name:'Al Hada', namez:[Namez(code:'ar', value: 'الهداء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'297', name:'Al Andalus', namez:[Namez(code:'ar', value: 'الاندلس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'298', name:'Al Buhaira', namez:[Namez(code:'ar', value: 'البحيرة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'299', name:'Al Bandariyah', namez:[Namez(code:'ar', value: 'البندرية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'300', name:'Al Thuqbah', namez:[Namez(code:'ar', value: 'الثقبة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'301', name:'Al Hizam Al Akhdar', namez:[Namez(code:'ar', value: 'الحزام الاخضر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'302', name:'Al Hizam Al Thahabi', namez:[Namez(code:'ar', value: 'الحزام الذهبي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'303', name:'Al Khobar Al Shamalia', namez:[Namez(code:'ar', value: 'الخبر الشمالية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'304', name:'Al Rawabi', namez:[Namez(code:'ar', value: 'الروابي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'305', name:'Al Aqrabiyah', namez:[Namez(code:'ar', value: 'العقربية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'306', name:'Al Ulaya', namez:[Namez(code:'ar', value: 'العليا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'307', name:'Al Yarmouk', namez:[Namez(code:'ar', value: 'اليرموك'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Khobar', id:'308', name:'Qurtoba', namez:[Namez(code:'ar', value: 'قرطبة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Duwadimi', id:'309', name:'Al Nahdah', namez:[Namez(code:'ar', value: 'النهضه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Duwadimi', id:'310', name:'Al Qudus', namez:[Namez(code:'ar', value: 'القدس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Duwadimi', id:'311', name:'Al Harmin', namez:[Namez(code:'ar', value: 'الحرمين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Duwadimi', id:'312', name:'Al Salam', namez:[Namez(code:'ar', value: 'السلام'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Duwadimi', id:'313', name:'Al Faisaliah', namez:[Namez(code:'ar', value: 'الفيصلية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Shaqra', id:'314', name:'Al Rawdah', namez:[Namez(code:'ar', value: 'الخبر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Kharj', id:'315', name:'Al Rayyan', namez:[Namez(code:'ar', value: 'الريان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Wadi Al Dawasir', id:'316', name:'Al Khamasin', namez:[Namez(code:'ar', value: 'الخماسين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Wadi Al Dawasir', id:'317', name:'Al Lidam North', namez:[Namez(code:'ar', value: 'اللدام الشمالي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Wadi Al Dawasir', id:'318', name:'Al Lidam South', namez:[Namez(code:'ar', value: 'اللدام الجنوبي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Wadi Al Dawasir', id:'319', name:'Al Nuayema', namez:[Namez(code:'ar', value: 'النويعمة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Wadi Al Dawasir', id:'320', name:'Al Sharafa', namez:[Namez(code:'ar', value: 'الشرافاء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Wadi Al Dawasir', id:'321', name:'Al Quwayz', namez:[Namez(code:'ar', value: 'القويز'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Qutaif', id:'322', name:'Al Majidiyah', namez:[Namez(code:'ar', value: 'المجيدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Qutaif', id:'323', name:'Al Khamisah', namez:[Namez(code:'ar', value: 'الخامسة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Qutaif', id:'324', name:'Al Khuzama', namez:[Namez(code:'ar', value: 'الخزامى'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Qutaif', id:'325', name:'Al Fath', namez:[Namez(code:'ar', value: 'الفتح'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Qutaif', id:'326', name:'Al Nassirah', namez:[Namez(code:'ar', value: 'الناصرة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Qutaif', id:'327', name:'Al Wahah', namez:[Namez(code:'ar', value: 'الواحة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Anak', id:'328', name:'Al Narjis', namez:[Namez(code:'ar', value: 'النرجس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Anak', id:'329', name:'Al Mahar', namez:[Namez(code:'ar', value: 'المحار'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Khamis Mushait', id:'330', name:'Al Khalidiyyah', namez:[Namez(code:'ar', value: 'الخالدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Khamis Mushait', id:'331', name:'Al Nasim', namez:[Namez(code:'ar', value: 'حي النسيم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Khamis Mushait', id:'332', name:'Al Aziziyah', namez:[Namez(code:'ar', value: 'العزيزية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Khamis Mushait', id:'333', name:'Al Suqur', namez:[Namez(code:'ar', value: 'الصقور'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Khamis Mushait', id:'334', name:'Al Nakhil', namez:[Namez(code:'ar', value: 'النخيل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Khamis Mushait', id:'335', name:'Al Fath', namez:[Namez(code:'ar', value: 'الفتح'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Khamis Mushait', id:'336', name:'Al Rawdah', namez:[Namez(code:'ar', value: 'الروضة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Khamis Mushait', id:'337', name:'Al Sadd', namez:[Namez(code:'ar', value: 'السد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Khamis Mushait', id:'338', name:'Al Sharafiyah', namez:[Namez(code:'ar', value: 'الشرفية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Khamis Mushait', id:'339', name:'Shakar', namez:[Namez(code:'ar', value: 'شكر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'340', name:'Al Baladiyah', namez:[Namez(code:'ar', value: 'البلدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'341', name:'Abu Musa Al Ashari', namez:[Namez(code:'ar', value: 'ابو موسى الاشعري'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'342', name:'Al Sinaiyah', namez:[Namez(code:'ar', value: 'الصناعية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'343', name:'Al Rabi', namez:[Namez(code:'ar', value: 'الربيع'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'344', name:'Al Faiha', namez:[Namez(code:'ar', value: 'الفيحاء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'345', name:'Al Batin', namez:[Namez(code:'ar', value: 'الباطن'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'346', name:'Al Rawdah', namez:[Namez(code:'ar', value: 'الروضة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'347', name:'Al Aziziyah', namez:[Namez(code:'ar', value: 'العزيزية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'348', name:'Al Masif', namez:[Namez(code:'ar', value: 'المصيف'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'349', name:'Al Khalidiyah', namez:[Namez(code:'ar', value: 'الخالدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'350', name:'Al Safaa', namez:[Namez(code:'ar', value: 'الصفاء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'351', name:'Al Muhammadiyah', namez:[Namez(code:'ar', value: 'المحمدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'352', name:'Al Muruj', namez:[Namez(code:'ar', value: 'المروج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'353', name:'Al Wahah', namez:[Namez(code:'ar', value: 'الواحة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hafar Al Batin', id:'354', name:'Fulaij', namez:[Namez(code:'ar', value: 'فليج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'355', name:'Prince Mishal District', namez:[Namez(code:'ar', value: 'حي الامير مشعل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'356', name:'Al Khalidiyyah', namez:[Namez(code:'ar', value: 'الخالدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'357', name:'Al Mukhayyam', namez:[Namez(code:'ar', value: 'المخيم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'358', name:'Al Faisaliah', namez:[Namez(code:'ar', value: 'الفيصلية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'359', name:'Housing Of Interior Security Forces', namez:[Namez(code:'ar', value: 'الاسكان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'360', name:'Al Athaybah', namez:[Namez(code:'ar', value: 'الأثايبة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'361', name:'Dahdah', namez:[Namez(code:'ar', value: 'دحضه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'362', name:'Northern Al Fahd', namez:[Namez(code:'ar', value: 'شمال الفهد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'363', name:'Al Fahd', namez:[Namez(code:'ar', value: 'الفهد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'364', name:'Aba Lasaud', namez:[Namez(code:'ar', value: 'ابا لسعود'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'365', name:'Al Amlah', namez:[Namez(code:'ar', value: 'الاملاح'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'366', name:'Al Jurbah', namez:[Namez(code:'ar', value: 'الجربه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'367', name:'Al Dubat', namez:[Namez(code:'ar', value: 'الضباط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'368', name:'Al Qabil', namez:[Namez(code:'ar', value: 'القابل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'369', name:'Sharq Al Dubat', namez:[Namez(code:'ar', value: 'شرق الضباط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Najran', id:'370', name:'Shamal Al Dubat', namez:[Namez(code:'ar', value: 'شمال الضباط'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'371', name:'Al Sharaei', namez:[Namez(code:'ar', value: 'الشرائع'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'372', name:'Al Rashidiyyah', namez:[Namez(code:'ar', value: 'الراشدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'373', name:'Al Juranah', namez:[Namez(code:'ar', value: 'الجعرانة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'374', name:'Al Usaylah', namez:[Namez(code:'ar', value: 'العسيلة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'375', name:'Wadi Jalil', namez:[Namez(code:'ar', value: 'وادي جليل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'376', name:'Jabal Al Nour', namez:[Namez(code:'ar', value: 'جبل النور'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'377', name:'Al Khansa', namez:[Namez(code:'ar', value: 'الخنساء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'378', name:'Al Adel', namez:[Namez(code:'ar', value: 'العدل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'379', name:'Al Khadra', namez:[Namez(code:'ar', value: 'الخضراء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'380', name:'Al Buhayrat', namez:[Namez(code:'ar', value: 'البحيرات'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'381', name:'Al Bibyan', namez:[Namez(code:'ar', value: 'البيبان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'382', name:'Al Tanim', namez:[Namez(code:'ar', value: 'التنعيم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'383', name:'Al Taysir', namez:[Namez(code:'ar', value: 'التيسير'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'384', name:'Al Hujun', namez:[Namez(code:'ar', value: 'الحجون'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'385', name:'Al Hamra & Um Al Jud', namez:[Namez(code:'ar', value: 'الحمراء و أم الجود'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'386', name:'Al Khalidiya', namez:[Namez(code:'ar', value: 'الخالدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'387', name:'Al Rusayfah', namez:[Namez(code:'ar', value: 'الرصيفة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'388', name:'Al Zahir', namez:[Namez(code:'ar', value: 'الزاهر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'389', name:'Al Zahra', namez:[Namez(code:'ar', value: 'الزهراء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'390', name:'Al Salamah', namez:[Namez(code:'ar', value: 'السلامة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'391', name:'Al Shoqiyah', namez:[Namez(code:'ar', value: 'الشوقية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'392', name:'Al Diyafah', namez:[Namez(code:'ar', value: 'الضيافة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'393', name:'Al Utaybiyyah', namez:[Namez(code:'ar', value: 'العتيبية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'394', name:'Al Aziziyah', namez:[Namez(code:'ar', value: 'العزيزية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'395', name:'Al Umrah Al Jadidah', namez:[Namez(code:'ar', value: 'العمرة الجديدة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'396', name:'Al Awali', namez:[Namez(code:'ar', value: 'العوالي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'397', name:'Al Kakiyyah', namez:[Namez(code:'ar', value: 'الكعكية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'398', name:'Al Mansur', namez:[Namez(code:'ar', value: 'المنصور'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'399', name:'Al Nuzhah', namez:[Namez(code:'ar', value: 'النزهة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'400', name:'Al Nawariyah', namez:[Namez(code:'ar', value: 'النوارية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'401', name:'Al Hindawiyah', namez:[Namez(code:'ar', value: 'الهنداوية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'402', name:'Bathaa Quraish', namez:[Namez(code:'ar', value: 'بطحاء قريش'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'403', name:'Al Laith Road', namez:[Namez(code:'ar', value: 'طريق الليث'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Makkah Al Mukarrama', id:'404', name:'Waly Al Ahd', namez:[Namez(code:'ar', value: 'ولي العهد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jazan', id:'405', name:'Al Safa', namez:[Namez(code:'ar', value: 'الصفا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jazan', id:'406', name:'Al Rawdah', namez:[Namez(code:'ar', value: 'الروضة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jazan', id:'407', name:'Al Suways', namez:[Namez(code:'ar', value: 'السويس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jazan', id:'408', name:'Sabya', namez:[Namez(code:'ar', value: 'صبيا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Jazan', id:'409', name:'Abu Arish', namez:[Namez(code:'ar', value: 'أبو عريش'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dhahran', id:'410', name:'Dana Al Shamaliah', namez:[Namez(code:'ar', value: 'الدانة الشمالية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dhahran', id:'411', name:'Dana Al Janubiyah', namez:[Namez(code:'ar', value: 'الدانة الجنوبية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dhahran', id:'412', name:'Doha Al Shamaliah', namez:[Namez(code:'ar', value: 'الدوحة الشمالية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dhahran', id:'413', name:'Doha Al Janubiyah', namez:[Namez(code:'ar', value: 'الدوحة الجنوبية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dhahran', id:'414', name:'Al Jameah', namez:[Namez(code:'ar', value: 'الجامعة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dhahran', id:'415', name:'Al Qusur', namez:[Namez(code:'ar', value: 'القصور'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Dhahran', id:'416', name:'Tihamah', namez:[Namez(code:'ar', value: 'تهـامة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'417', name:'Um Khalid', namez:[Namez(code:'ar', value: 'ام خالد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'418', name:'Al Aziziyyah', namez:[Namez(code:'ar', value: 'العزيزيه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'419', name:'Dhul Hulaifah', namez:[Namez(code:'ar', value: 'ذو الحليفه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'420', name:'Abu Kabir', namez:[Namez(code:'ar', value: 'ابو كبير'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'421', name:'Al Faisaliyyah', namez:[Namez(code:'ar', value: 'الفيصلية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'422', name:'Al Jameiah', namez:[Namez(code:'ar', value: 'حي الجامعة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'423', name:'Al Salam', namez:[Namez(code:'ar', value: 'السلام'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'424', name:'Al Aqeeq', namez:[Namez(code:'ar', value: 'العقيق'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'425', name:'Al Shefa', namez:[Namez(code:'ar', value: 'الشفا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'426', name:'Al Khalidiyyah', namez:[Namez(code:'ar', value: 'الخالدية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'427', name:'Al Difa', namez:[Namez(code:'ar', value: 'الدفاع'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'428', name:'Al Rayah', namez:[Namez(code:'ar', value: 'الراية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'429', name:'Al Aridh', namez:[Namez(code:'ar', value: 'العريض'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'430', name:'Al Usbah', namez:[Namez(code:'ar', value: 'العصبة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'431', name:'Al Anabis', namez:[Namez(code:'ar', value: 'العنابس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'432', name:'Al Fath', namez:[Namez(code:'ar', value: 'الفتح'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'433', name:'Al Mughaisilah', namez:[Namez(code:'ar', value: 'المغيسلة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'434', name:'Al Wabra', namez:[Namez(code:'ar', value: 'الوبرة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'435', name:'Bani Muawiyah', namez:[Namez(code:'ar', value: 'بني معاوية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'436', name:'Bir Uthman', namez:[Namez(code:'ar', value: 'بئر عثمان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Madina Al Munawara', id:'437', name:'Qurban', namez:[Namez(code:'ar', value: 'قربان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Ehsaa', id:'438', name:'Al Hulaylah', namez:[Namez(code:'ar', value: 'الحليلة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Ehsaa', id:'439', name:'Al Mubarraz', namez:[Namez(code:'ar', value: 'المبرز'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Ehsaa', id:'440', name:'Al Hofuf', namez:[Namez(code:'ar', value: 'الهفوف'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Ehsaa', id:'441', name:'Madinat Al Jafr', namez:[Namez(code:'ar', value: 'مدينة الجفر'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'442', name:'Al Muntazah', namez:[Namez(code:'ar', value: 'المنتزة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'443', name:'Al Nahdah', namez:[Namez(code:'ar', value: 'النهضة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'444', name:'Al Quway', namez:[Namez(code:'ar', value: 'القويع'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'445', name:'Al Safra', namez:[Namez(code:'ar', value: 'حي الصفراء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'446', name:'Al Qadissya', namez:[Namez(code:'ar', value: 'القادسية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'447', name:'Al Shamas', namez:[Namez(code:'ar', value: 'الشماس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'448', name:'Al Amn', namez:[Namez(code:'ar', value: 'الأمن'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'449', name:'Al Nour', namez:[Namez(code:'ar', value: 'النور'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'450', name:'Al Taleem', namez:[Namez(code:'ar', value: 'التعليم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'451', name:'Al Iskan', namez:[Namez(code:'ar', value: 'الاسكان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'452', name:'Al Ofoq', namez:[Namez(code:'ar', value: 'الأفق'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'453', name:'Al Janoub', namez:[Namez(code:'ar', value: 'الجنوب'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'454', name:'Al Rawda', namez:[Namez(code:'ar', value: 'الروضة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'455', name:'Al Rayan', namez:[Namez(code:'ar', value: 'الريان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'456', name:'Al Sadah', namez:[Namez(code:'ar', value: 'السادة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'457', name:'Al Salhiyah', namez:[Namez(code:'ar', value: 'الصالحية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'458', name:'Al Fayziyyah', namez:[Namez(code:'ar', value: 'الفايزية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Buraydah', id:'459', name:'Al Manar', namez:[Namez(code:'ar', value: 'المنار'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'460', name:'Al Sulimaniyah', namez:[Namez(code:'ar', value: 'السليمانية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'461', name:'Al Mazadah', namez:[Namez(code:'ar', value: 'المزادة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'462', name:'Al Salhiyah', namez:[Namez(code:'ar', value: 'الصالحية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'463', name:'Al Shuraymiyyah', namez:[Namez(code:'ar', value: 'الشريمية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'464', name:'Al Fakhrya', namez:[Namez(code:'ar', value: 'الفاخرية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'465', name:'Al Manar', namez:[Namez(code:'ar', value: 'المنار'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'466', name:'Al Ashrafyah', namez:[Namez(code:'ar', value: 'الأشرفية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'467', name:'Al Khuzama', namez:[Namez(code:'ar', value: 'الخزامى'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'468', name:'Al Olaya', namez:[Namez(code:'ar', value: 'العليا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'469', name:'Al Badya', namez:[Namez(code:'ar', value: 'البديعة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'470', name:'Al Rayan', namez:[Namez(code:'ar', value: 'الريان'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'471', name:'Al Faidha', namez:[Namez(code:'ar', value: 'الفيضة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'472', name:'Al Qadisiyah', namez:[Namez(code:'ar', value: 'القادسية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'473', name:'Al Matar', namez:[Namez(code:'ar', value: 'المطار'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'474', name:'Al Nuzha', namez:[Namez(code:'ar', value: 'النزهة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'475', name:'Al Hadaa', namez:[Namez(code:'ar', value: 'الهداء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'476', name:'Sultanah', namez:[Namez(code:'ar', value: 'سلطانة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Unayzah', id:'477', name:'Shaikhah', namez:[Namez(code:'ar', value: 'شيخة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hail', id:'478', name:'Al Khuzama', namez:[Namez(code:'ar', value: 'الخزامي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hail', id:'479', name:'Al Wusayta', namez:[Namez(code:'ar', value: 'الوسيطاء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hail', id:'480', name:'Al Mahattah', namez:[Namez(code:'ar', value: 'المحطة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hail', id:'481', name:'Al Zahra', namez:[Namez(code:'ar', value: 'الزهراء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hail', id:'482', name:'Al Aziziyah', namez:[Namez(code:'ar', value: 'العزيزية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hail', id:'483', name:'Al Masyaf', namez:[Namez(code:'ar', value: 'المصيف'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hail', id:'484', name:'Al Zibarah', namez:[Namez(code:'ar', value: 'الزبارة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Hail', id:'485', name:'Aja', namez:[Namez(code:'ar', value: 'اجا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'486', name:'Al Maashi', namez:[Namez(code:'ar', value: 'المعشي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'487', name:'Al Huwaya', namez:[Namez(code:'ar', value: 'الحويه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'488', name:'Qurwa', namez:[Namez(code:'ar', value: 'قروي'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'489', name:'Al Sharqyyah', namez:[Namez(code:'ar', value: 'الشرقية'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'490', name:'Wadi Waj', namez:[Namez(code:'ar', value: 'وادي وج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'491', name:'Shihar', namez:[Namez(code:'ar', value: 'شهار'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'492', name:'Al Jal', namez:[Namez(code:'ar', value: 'الجال'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'493', name:'Jubrah', namez:[Namez(code:'ar', value: 'جبره'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'494', name:'Al Aqeeq', namez:[Namez(code:'ar', value: 'العقيق'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'495', name:'Al Khalidiyyah', namez:[Namez(code:'ar', value: 'الخالديه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'496', name:'Al Sadad', namez:[Namez(code:'ar', value: 'السداد'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'497', name:'Al Salamah', namez:[Namez(code:'ar', value: 'السلامه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'498', name:'Al Shuhada', namez:[Namez(code:'ar', value: 'الشهداء'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'499', name:'Al Aziziyyah', namez:[Namez(code:'ar', value: 'العزيزيه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'500', name:'Al Mathnah', namez:[Namez(code:'ar', value: 'المثناه'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'501', name:'Hawaya', namez:[Namez(code:'ar', value: 'حوايا'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Al Taif', id:'502', name:'Nakhab', namez:[Namez(code:'ar', value: 'نخب'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Abha', id:'503', name:'Mansak', namez:[Namez(code:'ar', value: 'المنسك'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Abha', id:'504', name:'Al Muftaha', namez:[Namez(code:'ar', value: 'المفتاحة'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Abha', id:'505', name:'Al Qabil', namez:[Namez(code:'ar', value: 'القابل'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Abha', id:'506', name:'Al Alandalus', namez:[Namez(code:'ar', value: 'الاندلس'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Abha', id:'507', name:'Al Arin', namez:[Namez(code:'ar', value: 'العرين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Abha', id:'508', name:'Al Marooj', namez:[Namez(code:'ar', value: 'المروج'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Abha', id:'509', name:'Al Nasim', namez:[Namez(code:'ar', value: 'النسيم'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Abha', id:'510', name:'Al Muathafein', namez:[Namez(code:'ar', value: 'الموظفين'),], isActivated: true, isPublic: false, ),
  Area(iso3: 'sau', province: 'Abha', id:'511', name:'Al Dabab', namez:[Namez(code:'ar', value: 'الضباب'),], isActivated: true, isPublic: false, ),
];