// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:  return android; break;
      case TargetPlatform.iOS:      return ios; break;
      case TargetPlatform.windows:  return web; break;
      case TargetPlatform.macOS:    platformNotSupported('MacOS'); return null; break;
      case TargetPlatform.linux:    platformNotSupported('Linux'); return null; break;
      default: platformNotSupported('NOTHING'); return null;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_1BLdRfQGsfKwk_6nHwZB9cAEqutiCdY',
    appId: '1:439018969330:web:b110117c6a47ed5003186b',
    messagingSenderId: '439018969330',
    projectId: 'bldrsnet',
    authDomain: 'bldrsnet.firebaseapp.com',
    databaseURL: 'https://bldrsnet.firebaseio.com',
    storageBucket: 'bldrsnet.appspot.com',
    measurementId: 'G-NJM2DNMK00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5IaZsHjj_rlagXm-9Hq0Epl7bEtdsmho',
    appId: '1:439018969330:android:eb5211399ceb6de403186b',
    messagingSenderId: '439018969330',
    projectId: 'bldrsnet',
    databaseURL: 'https://bldrsnet.firebaseio.com',
    storageBucket: 'bldrsnet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_VAr_fQwnb--Z-pSWBn5lHaIEt_7MVrY',
    appId: '1:439018969330:ios:6b38af9e92642fc603186b',
    messagingSenderId: '439018969330',
    projectId: 'bldrsnet',
    databaseURL: 'https://bldrsnet.firebaseio.com',
    storageBucket: 'bldrsnet.appspot.com',
    androidClientId: '439018969330-gd0s8talc5michs970i9neofqc3c6lf6.apps.googleusercontent.com',
    iosClientId: '439018969330-o93if8djhfn3naftc361uker0s97n5oj.apps.googleusercontent.com',
    iosBundleId: 'net.bldrs.app',
  );
}

void platformNotSupported(String platform) {
  throw UnsupportedError(
    'DefaultFirebaseOptions have not been configured for $platform - '
    'you can reconfigure this by running the FlutterFire CLI again.',
  );
}
