

import 'package:bldrs/a_models/secondary_models/phrase_model.dart';

const List<Phrase> extraPhrases = <Phrase>[

  Phrase(id: 'phid_k_flyer_type_product', value: 'Products', langCode: 'en'), Phrase(id: 'phid_k_flyer_type_product', value: 'منتجات', langCode: 'ar'),
  Phrase(id: 'phid_k_flyer_type_equipment', value: 'Equipment', langCode: 'en'), Phrase(id: 'phid_k_flyer_type_equipment', value: 'معدات', langCode: 'ar'),
  Phrase(id: 'phid_k_flyer_type_property', value: 'Properties', langCode: 'en'), Phrase(id: 'phid_k_flyer_type_property', value: 'عقارات', langCode: 'ar'),
  Phrase(id: 'phid_k_flyer_type_design', value: 'Designs & Projects', langCode: 'en'), Phrase(id: 'phid_k_flyer_type_design', value: 'تصاميم و مشاريع', langCode: 'ar'),
  Phrase(id: 'phid_k_flyer_type_craft', value: 'Craft Samples', langCode: 'en'), Phrase(id: 'phid_k_flyer_type_craft', value: 'عينات حرفية', langCode: 'ar'),

  Phrase(id: 'phid_k_group_prd_walls', value: 'Walls & Room Partitions', langCode: 'en'), Phrase(id: 'phid_k_group_prd_walls', value: 'حوائط و فواصل غرف', langCode: 'ar'),
  Phrase(id: 'phid_k_group_prd_floors', value: 'Floors & ٍSkirting', langCode: 'en'), Phrase(id: 'phid_k_group_prd_floors', value: 'أرضيات و وزر', langCode: 'ar'),
  Phrase(id: 'phid_k_group_prd_structure', value: 'Light Structures', langCode: 'en'), Phrase(id: 'phid_k_group_prd_structure', value: 'هياكل و منشآت خفيفة', langCode: 'ar'),
  Phrase(id: 'phid_k_group_prd_fireFighting', value: 'Fire Fighting', langCode: 'en'), Phrase(id: 'phid_k_group_prd_fireFighting', value: 'مقاومة حريق', langCode: 'ar'),
  Phrase(id: 'phid_k_group_prd_safety', value: 'Safety', langCode: 'en'), Phrase(id: 'phid_k_group_prd_safety', value: 'أمن و سلامة', langCode: 'ar'),
  Phrase(id: 'phid_k_group_prd_stairs', value: 'Stairs', langCode: 'en'), Phrase(id: 'phid_k_group_prd_stairs', value: 'سلالم', langCode: 'ar'),
  Phrase(id: 'phid_k_group_prd_roofing', value: 'Roofing', langCode: 'en'), Phrase(id: 'phid_k_group_prd_roofing', value: 'أسطح', langCode: 'ar'),
  Phrase(id: 'phid_k_group_prd_doors', value: 'Doors & Windows', langCode: 'en'), Phrase(id: 'phid_k_group_prd_doors', value: 'أبواب و شبابيك', langCode: 'ar'),
  Phrase(id: 'phid_k_group_prd_landscape', value: 'Planting & Landscape', langCode: 'en'), Phrase(id: 'phid_k_group_prd_landscape', value: 'زراعات و لاندسكيب', langCode: 'ar'),
  Phrase(id: 'phid_k_group_prd_hvac', value: 'Heating Ventilation Air Conditioning', langCode: 'en'), Phrase(id: 'phid_k_group_prd_hvac', value: 'تدفئة تهوية تكييف', langCode: 'ar'),
  Phrase(id: 'phid_k_group_prd_plumbing', value: 'Plumbing & Sanitary ware', langCode: 'en'), Phrase(id: 'phid_k_group_prd_plumbing', value: 'سباكة و أدوات صحية', langCode: 'ar'),
  Phrase(id: 'phid_k_group_prd_lighting', value: 'Lighting', langCode: 'en'), Phrase(id: 'phid_k_group_prd_lighting', value: 'إضاءة', langCode: 'ar'),
  Phrase(id: 'phid_k_group_prd_electricity', value: 'Electricity', langCode: 'en'), Phrase(id: 'phid_k_group_prd_electricity', value: 'كهرباء', langCode: 'ar'),
  Phrase(id: 'phid_k_group_prd_security', value: 'Security', langCode: 'en'), Phrase(id: 'phid_k_group_prd_security', value: 'الحماية و الأمان', langCode: 'ar'),
  Phrase(id: 'phid_k_group_prd_poolSpa', value: 'Pools & Spa', langCode: 'en'), Phrase(id: 'phid_k_group_prd_poolSpa', value: 'حمامات سباحة و حمامات صحية', langCode: 'ar'),
  Phrase(id: 'phid_k_group_prd_smartHome', value: 'Smart home', langCode: 'en'), Phrase(id: 'phid_k_group_prd_smartHome', value: 'تجهيزات المنازل الذكية', langCode: 'ar'),
  Phrase(id: 'phid_k_group_prd_furniture', value: 'Furniture', langCode: 'en'), Phrase(id: 'phid_k_group_prd_furniture', value: 'أثاث و مفروشات', langCode: 'ar'),
  Phrase(id: 'phid_k_group_prd_appliances', value: 'Appliances', langCode: 'en'), Phrase(id: 'phid_k_group_prd_appliances', value: 'أجهزة كهربائية', langCode: 'ar'),
  Phrase(id: 'phid_k_group_prd_materials', value: 'Construction Materials', langCode: 'en'), Phrase(id: 'phid_k_group_prd_materials', value: 'مواد بناء', langCode: 'ar'),
  Phrase(id: 'phid_k_group_equip_handheld', value: 'Handheld equipment & tools', langCode: 'en'), Phrase(id: 'phid_k_group_equip_handheld', value: 'معدات و أدوات خفيفة', langCode: 'ar'),
  Phrase(id: 'phid_k_group_equip_prep', value: 'Construction preparations', langCode: 'en'), Phrase(id: 'phid_k_group_equip_prep', value: 'تجهيزات الموقع', langCode: 'ar'),
  Phrase(id: 'phid_k_group_equip_vehicle', value: 'Vehicles', langCode: 'en'), Phrase(id: 'phid_k_group_equip_vehicle', value: 'عربات', langCode: 'ar'),
  Phrase(id: 'phid_k_group_equip_handling', value: 'Material handling equipment', langCode: 'en'), Phrase(id: 'phid_k_group_equip_handling', value: 'معدات نقل و تحميل', langCode: 'ar'),
  Phrase(id: 'phid_k_group_equip_heavy', value: 'Heavy machinery', langCode: 'en'), Phrase(id: 'phid_k_group_equip_heavy', value: 'معدات ثقيلة', langCode: 'ar'),
  Phrase(id: 'phid_k_group_ppt_form', value: 'Property Form', langCode: 'en'), Phrase(id: 'phid_k_group_ppt_form', value: 'هيئة العقار', langCode: 'ar'),
  Phrase(id: 'phid_k_group_ppt_type', value: 'Property Type', langCode: 'en'), Phrase(id: 'phid_k_group_ppt_type', value: 'نوع العقار', langCode: 'ar'),
  Phrase(id: 'phid_k_group_ppt_area', value: 'Area', langCode: 'en'), Phrase(id: 'phid_k_group_ppt_area', value: 'المساحة', langCode: 'ar'),
  Phrase(id: 'phid_k_group_ppt_spaces', value: 'Spaces', langCode: 'en'), Phrase(id: 'phid_k_group_ppt_spaces', value: 'مساحات العقار', langCode: 'ar'),
  Phrase(id: 'phid_k_group_ppt_features', value: 'Property Features', langCode: 'en'), Phrase(id: 'phid_k_group_ppt_features', value: 'خواص العقار', langCode: 'ar'),
  Phrase(id: 'phid_k_group_ppt_price', value: 'Property Price', langCode: 'en'), Phrase(id: 'phid_k_group_ppt_price', value: 'سعر العقار', langCode: 'ar'),
  Phrase(id: 'phid_k_group_dz_type', value: 'Design Type', langCode: 'en'), Phrase(id: 'phid_k_group_dz_type', value: 'نوع التصميم', langCode: 'ar'),
  Phrase(id: 'phid_k_group_dz_style', value: 'Architectural Style', langCode: 'en'), Phrase(id: 'phid_k_group_dz_style', value: 'الطراز المعماري', langCode: 'ar'),
  Phrase(id: 'phid_k_group_craft_trade', value: 'Construction Trade', langCode: 'en'), Phrase(id: 'phid_k_group_craft_trade', value: 'الحرفة', langCode: 'ar'),
  Phrase(id: 'phid_k_group_ppt_license', value: 'Property License', langCode: 'en'), Phrase(id: 'phid_k_group_ppt_license', value: 'رخصة العقار', langCode: 'ar'),
  Phrase(id: 'phid_k_group_space_type', value: 'Space Type', langCode: 'en'), Phrase(id: 'phid_k_group_space_type', value: 'نوع الفراغ', langCode: 'ar'),
  Phrase(id: 'phid_k_group_dz_kioskType', value: 'Kiosk Type', langCode: 'en'), Phrase(id: 'phid_k_group_dz_kioskType', value: 'نوع الكشك', langCode: 'ar'),
  Phrase(id: 'phid_k_group_prd_price', value: 'Product Price', langCode: 'en'), Phrase(id: 'phid_k_group_prd_price', value: 'سعر المنتج', langCode: 'ar'),

  Phrase(id: 'phid_k_sub_prd_walls_partitions', value: 'Room Partitions', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_walls_partitions', value: 'فواصل غرف', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_walls_cladding', value: 'Wall Cladding', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_walls_cladding', value: 'تبليط و تجلاليد حوائط', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_walls_moldings', value: 'Moldings & Millwork', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_walls_moldings', value: 'قوالب و عواميد', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_walls_ceiling', value: 'Ceiling Cladding', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_walls_ceiling', value: 'تجاليد أسقف', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_floors_tiles', value: 'Floor Tiles', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_floors_tiles', value: 'بلاط أرضيات', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_floors_planks', value: 'Floor Planks', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_floors_planks', value: 'ألواح أرضيات', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_floors_covering', value: 'Floor Covering', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_floors_covering', value: 'تغطيات أرضيات', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_floors_paving', value: 'Floor Paving', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_floors_paving', value: 'تمهيد أرضيات', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_floors_skirting', value: 'Skirting', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_floors_skirting', value: 'وزر', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_struc_shades', value: 'Shades', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_struc_shades', value: 'مظلات', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_struc_light', value: 'Light Structures', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_struc_light', value: 'منشآت خفيفة', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_fire_equip', value: 'Fire Fighting Equipment', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_fire_equip', value: 'معدات مكافحة حريق', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_fire_pumpsCont', value: 'Pumps & Controllers', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_fire_pumpsCont', value: 'مضخات و متحكمات', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_fire_detectors', value: 'Fire Detectors', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_fire_detectors', value: 'كاشفات حريق', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_fire_clothes', value: 'Fire Fighting Cloth', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_fire_clothes', value: 'ملابس مكافحة حريق', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_safety_clothes', value: 'Safety Clothes', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_safety_clothes', value: 'ملابس أمن و سلامة', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_safety_equip', value: 'Safety Equipment', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_safety_equip', value: 'معدات سلامة', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_safety_floorProtection', value: 'Floor Protection', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_safety_floorProtection', value: 'حماية أرضيات', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_stairs_handrails', value: 'Handrails', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_stairs_handrails', value: 'درابزين سلالم', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_roof_drainage', value: 'Roof Drainage', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_roof_drainage', value: 'صرف أسطح', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_roof_cladding', value: 'Roof Cladding', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_roof_cladding', value: 'تجاليد أسطح', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_doors_shutters', value: 'Shutters', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_doors_shutters', value: 'شيش حصيرة', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_door_doors', value: 'Doors', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_door_doors', value: 'أبواب', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_door_windows', value: 'Windows', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_door_windows', value: 'شبابيك', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_door_hardware', value: 'Hardware', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_door_hardware', value: 'اكسسوارات', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_scape_livePlants', value: 'Live Plants', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_scape_livePlants', value: 'نباتات حية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_scape_artificial', value: 'Artificial plants', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_scape_artificial', value: 'نباتات صناعية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_scape_potsVases', value: 'Pots & Vases', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_scape_potsVases', value: 'أواني و مزهريات', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_scape_birds', value: 'Birds fixtures', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_scape_birds', value: 'تجهيزات عصافير', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_scape_fountainsPonds', value: 'Fountains & Ponds', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_scape_fountainsPonds', value: 'نوافير و برك', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_scape_hardscape', value: 'Hardscape', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_scape_hardscape', value: 'هاردسكيب', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_hvac_heating', value: 'Heating', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_hvac_heating', value: 'تدفئة', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_hvac_ventilation', value: 'Ventilation', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_hvac_ventilation', value: 'تهوية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_hvac_ac', value: 'Air Conditioning', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_hvac_ac', value: 'تكييف هواء', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_hvac_fireplaces', value: 'Fireplaces', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_hvac_fireplaces', value: 'مواقد نار', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_hvac_fireplaceEquip', value: 'Fireplace Equipment', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_hvac_fireplaceEquip', value: 'أدوات مواقد نار', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_plumb_connections', value: 'Connections', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_plumb_connections', value: 'وصلات', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_plumb_treatment', value: 'Water Treatment', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_plumb_treatment', value: 'معالجة مياه', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_plumb_sanitary', value: 'Sanitary ware', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_plumb_sanitary', value: 'أدوات صحية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_plumb_kitchen', value: 'Kitchen Sanitary ware', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_plumb_kitchen', value: 'أدوات مطبخ صحية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_plumb_handwash', value: 'Handwash Sanitary ware', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_plumb_handwash', value: 'أدوات غسيل أيدي صحية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_plumb_toilet', value: 'Toilet Sanitary ware', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_plumb_toilet', value: 'أدوات مراحيض صحية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_plumb_shower', value: 'Shower Sanitary ware', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_plumb_shower', value: 'أدوات استحمام صحية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_plumb_tub', value: 'Tub Sanitary ware', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_plumb_tub', value: 'أدوات بانيو صحية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_light_lamps', value: 'Lamps', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_light_lamps', value: 'مصابيح', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_light_ceiling', value: 'Ceiling Lighting', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_light_ceiling', value: 'إضاءة أسقف', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_light_wall', value: 'Wall Lighting', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_light_wall', value: 'إضاءة حائطية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_light_outdoor', value: 'Outdoor Lighting', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_light_outdoor', value: 'إضاءة خارجية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_light_access', value: 'Lighting Accessories', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_light_access', value: 'اكسسوارات إضاءة', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_light_bulbs', value: 'Light bulbs', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_light_bulbs', value: 'لمبات إضاءة', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_elec_cables', value: 'Cables & Wires', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_elec_cables', value: 'كابلات أسلاك', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_elec_connectors', value: 'Electrical Connectors', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_elec_connectors', value: 'وصلات كهربائية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_elec_switches', value: 'Electrical Switches', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_elec_switches', value: 'مفاتيح كهربائية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_elec_organization', value: 'Electricity Organizers', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_elec_organization', value: 'منسقات كهربائية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_elec_powerStorage', value: 'Power Storage', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_elec_powerStorage', value: 'تخزين كهرباء', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_elec_instruments', value: 'Electricity Instruments', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_elec_instruments', value: 'أجهزة كهربائية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_elec_generators', value: 'Electricity Generators', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_elec_generators', value: 'مولدات كهرباء', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_elec_motors', value: 'Electrical Motors', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_elec_motors', value: 'مواتير كهربائية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_security_surveillance', value: 'Surveillance Systems', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_security_surveillance', value: 'أنظمة مراقبة', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_security_accessibility', value: 'Accessibility Systems', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_security_accessibility', value: 'أنظمة دخول', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_security_roadControl', value: 'Road Control', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_security_roadControl', value: 'تحكم في الطرق', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_security_safes', value: 'Security Safes', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_security_safes', value: 'خزائن أمان', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_pool_pools', value: 'Swimming Pools', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_pool_pools', value: 'حمامات سباحة', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_pool_equipment', value: 'Pools Equipment', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_pool_equipment', value: 'عدات حمامات سباحة', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_pool_accessories', value: 'Pool Accessories', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_pool_accessories', value: 'اكسسوارات حمامات سباحة', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_pool_spa', value: 'Spa', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_pool_spa', value: 'حمامات صحية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_smart_audio', value: 'Audio Systems', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_smart_audio', value: 'أنظمة صوت', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_smart_automation', value: 'Automation Systems', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_smart_automation', value: 'أنظمة أوتوماتية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_sets', value: 'Complete Sets', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_sets', value: 'أطقم متكااملة', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_chairs', value: 'Chairs', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_chairs', value: 'كراسي', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_tables', value: 'Tables', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_tables', value: 'طاولات', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_outSeating', value: 'Outdoor Seating', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_outSeating', value: 'مقاعد خارجية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_outTables', value: 'Outdoor Tables', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_outTables', value: 'طاولات خارجية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_parts', value: 'Furniture Parts', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_parts', value: 'أجزاء أثاث', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_couch', value: 'Couches', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_couch', value: 'أرائك و كنب', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_seatingBench', value: 'Seating Benches', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_seatingBench', value: 'مجالس', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_kitchenStorage', value: 'Kitchen Storage', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_kitchenStorage', value: 'خزائن مطبخ', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_diningStorage', value: 'Dining Storage', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_diningStorage', value: 'خزائن غرفة طعام', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_bathStorage', value: 'Bathroom Storage', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_bathStorage', value: 'خزائن حمام', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_dressingStorage', value: 'Dressing Storage', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_dressingStorage', value: 'خزائن ملابس', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_livingStorage', value: 'Living Storage', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_livingStorage', value: 'خزائن غرفة معيشة', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_boxes', value: 'Boxes', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_boxes', value: 'صناديق ', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_kids', value: 'Kids Furniture', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_kids', value: 'أثاث أطفال', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_planting', value: 'Planting', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_planting', value: 'زراعة منزلية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_laundry', value: 'Laundry', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_laundry', value: 'تجهيزات مغسلة ملابس', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_accessories', value: 'Furniture Accessories', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_accessories', value: 'اكسسوارات أثاث', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_organizers', value: 'Organizers', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_organizers', value: 'منظمات', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_artworks', value: 'Artworks', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_artworks', value: 'أعمال فنية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_bathHardware', value: 'Bathroom Hardware', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_bathHardware', value: 'اكسسوارات حمامات', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_wasteDisposal', value: 'Waste Disposal', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_wasteDisposal', value: 'تخلص من النفايات', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_cabinetHardware', value: 'Cabinet Hardware', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_cabinetHardware', value: 'اكسسوارات كابينات', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_carpetsRugs', value: 'Carpets & Rugs', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_carpetsRugs', value: 'سجاد', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_blindsCurtains', value: 'Blinds & Curtains', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_blindsCurtains', value: 'ستائر', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_Kitchen Accessories', value: 'Kitchen Accessories', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_Kitchen Accessories', value: 'اكسسوارات مطبخ', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_beds', value: 'Beds & Headboards', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_beds', value: 'سرائر و ظهور سرائر', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_cushions', value: 'Cushions & Pillows', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_cushions', value: 'وسائد و مساند', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_office', value: 'Office Furniture', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_office', value: 'أثاث مكاتب', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_furn_tops', value: 'Vanity Tops', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_furn_tops', value: 'أسطح وحدات حمام و مطبخ', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_app_refrigeration', value: 'Refrigeration', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_app_refrigeration', value: 'مبردات و ثلاجات', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_app_indoorCooking', value: 'Indoor Cooking', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_app_indoorCooking', value: 'أجهزة طبخ داخلي', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_app_foodProcessors', value: 'Food Processors', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_app_foodProcessors', value: 'محضرات طعام', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_app_outdoorCooking', value: 'Outdoor Cooking', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_app_outdoorCooking', value: 'أجهزة طبخ خارجي', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_app_bathroom', value: 'Bathroom Appliances', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_app_bathroom', value: 'أجهزة حمام كهربائية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_app_housekeeping', value: 'HouseKeeping Appliances', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_app_housekeeping', value: 'أجهزة غسيل و نظافة', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_app_drinks', value: 'Drinks Appliances', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_app_drinks', value: 'أجهزة تحضير مشروبات', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_app_snacks', value: 'Snacks Appliances', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_app_snacks', value: 'أجهزة تحضير وجبات خفيفة', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_app_wasteDisposal', value: 'Waste Disposal Appliances', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_app_wasteDisposal', value: 'أجهزة تخلص من النفايات', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_app_media', value: 'Media Appliances', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_app_media', value: 'أجهزة ميديا', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_mat_cement', value: 'Cement', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_mat_cement', value: 'أسمنت', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_mat_steel', value: 'Steel', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_mat_steel', value: 'حديد مسلح', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_mat_gypsum', value: 'Gypsum', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_mat_gypsum', value: 'جبس', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_mat_sandRubble', value: 'Sand & Rubble', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_mat_sandRubble', value: 'رمل و زلط', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_mat_bricks', value: 'Bricks', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_mat_bricks', value: 'طوب', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_mat_manuWood', value: 'Manufactured Wood', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_mat_manuWood', value: 'أخشاب مصنعة', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_mat_solidWood', value: 'Solid Wood', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_mat_solidWood', value: 'أخشاب طبيعية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_mat_stones', value: 'Stones', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_mat_stones', value: 'حجر', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_mat_woodCoats', value: 'Wood Coats', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_mat_woodCoats', value: 'دهانات خشب', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_mat_paints', value: 'Paints', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_mat_paints', value: 'دهانات', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_mat_glass', value: 'Glass', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_mat_glass', value: 'زجاج', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_mat_acrylic', value: 'Acrylic', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_mat_acrylic', value: 'أكريليك', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_mat_metals', value: 'Metals', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_mat_metals', value: 'معادن', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_mat_fabrics', value: 'Fabrics', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_mat_fabrics', value: 'أنسجة', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_mat_waterProofing', value: 'Water Proofing', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_mat_waterProofing', value: 'عوازل رطوبة و مياه', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_mat_heatIMin', value: 'Mineral Heat Insulation', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_mat_heatIMin', value: 'عوازل حرارية من ألياف معدنية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_mat_heatSynth', value: 'Synthetic Heat Insulation', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_mat_heatSynth', value: 'عوازل حرارية مصنوعة', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_handheld_cleaning', value: 'Cleaning Tools', langCode: 'en'), Phrase(id: 'phid_k_sub_handheld_cleaning', value: 'أدوات نظافة', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_handheld_gardenTools', value: 'Garden Tools', langCode: 'en'), Phrase(id: 'phid_k_sub_handheld_gardenTools', value: 'أدوات زراعة', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_handheld_handTools', value: 'Hand tools', langCode: 'en'), Phrase(id: 'phid_k_sub_handheld_handTools', value: 'أدوات يدوية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_handheld_power', value: 'Power tools', langCode: 'en'), Phrase(id: 'phid_k_sub_handheld_power', value: 'أدوات كهربية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_handheld_measure', value: 'Measurement tools', langCode: 'en'), Phrase(id: 'phid_k_sub_handheld_measure', value: 'أدوات قياس', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_handheld_machinery', value: 'Handheld machinery', langCode: 'en'), Phrase(id: 'phid_k_sub_handheld_machinery', value: 'ماكينات يدوية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_vehicle_earthmoving', value: 'Earth moving vehicles', langCode: 'en'), Phrase(id: 'phid_k_sub_vehicle_earthmoving', value: 'عربات تحريك الأرض', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_vehicle_transport', value: 'Transporting vehicles', langCode: 'en'), Phrase(id: 'phid_k_sub_vehicle_transport', value: 'عربات ناقلة', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_vehicle_paving', value: 'Paving vehicles', langCode: 'en'), Phrase(id: 'phid_k_sub_vehicle_paving', value: 'عربات تمهيد طرق', langCode: 'ar'),
  Phrase(id: 'phid_k_ppt_lic_residential', value: 'Residential', langCode: 'en'), Phrase(id: 'phid_k_ppt_lic_residential', value: 'سكني', langCode: 'ar'),
  Phrase(id: 'phid_k_ppt_lic_retail', value: 'Retail', langCode: 'en'), Phrase(id: 'phid_k_ppt_lic_retail', value: 'تجاري', langCode: 'ar'),
  Phrase(id: 'phid_k_ppt_lic_industrial', value: 'Industrial', langCode: 'en'), Phrase(id: 'phid_k_ppt_lic_industrial', value: 'صناعي', langCode: 'ar'),
  Phrase(id: 'phid_k_ppt_lic_administration', value: 'Administration', langCode: 'en'), Phrase(id: 'phid_k_ppt_lic_administration', value: 'إداري', langCode: 'ar'),
  Phrase(id: 'phid_k_ppt_lic_educational', value: 'Educational', langCode: 'en'), Phrase(id: 'phid_k_ppt_lic_educational', value: 'تعليمي', langCode: 'ar'),
  Phrase(id: 'phid_k_ppt_lic_hotel', value: 'Hotel', langCode: 'en'), Phrase(id: 'phid_k_ppt_lic_hotel', value: 'فندقي', langCode: 'ar'),
  Phrase(id: 'phid_k_ppt_lic_sports', value: 'Sports', langCode: 'en'), Phrase(id: 'phid_k_ppt_lic_sports', value: 'رياضي', langCode: 'ar'),
  Phrase(id: 'phid_k_ppt_lic_entertainment', value: 'Entertainment', langCode: 'en'), Phrase(id: 'phid_k_ppt_lic_entertainment', value: 'ترفيهي', langCode: 'ar'),
  Phrase(id: 'phid_k_ppt_lic_medical', value: 'Medical', langCode: 'en'), Phrase(id: 'phid_k_ppt_lic_medical', value: 'طبي', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_ppt_area_pptArea', value: 'Property Area', langCode: 'en'), Phrase(id: 'phid_k_sub_ppt_area_pptArea', value: 'مساحة العقار', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_ppt_area_lotArea', value: 'Lot Area', langCode: 'en'), Phrase(id: 'phid_k_sub_ppt_area_lotArea', value: 'مساحة الأرض', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_ppt_spaces_bedrooms', value: 'Number of Bedrooms', langCode: 'en'), Phrase(id: 'phid_k_sub_ppt_spaces_bedrooms', value: 'عدد غرف النوم', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_ppt_spaces_bathrooms', value: 'Number of Bathrooms', langCode: 'en'), Phrase(id: 'phid_k_sub_ppt_spaces_bathrooms', value: 'عدد الحمامات', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_ppt_spaces_rooms', value: 'Property Rooms', langCode: 'en'), Phrase(id: 'phid_k_sub_ppt_spaces_rooms', value: 'غرف العقار', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_ppt_spaces_parkings', value: 'Number of private Parking Lots', langCode: 'en'), Phrase(id: 'phid_k_sub_ppt_spaces_parkings', value: 'عدد مواقف السيارات الخاصة', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_ppt_feat_compound', value: 'In a Compound', langCode: 'en'), Phrase(id: 'phid_k_sub_ppt_feat_compound', value: 'في مجمع سكني', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_ppt_feat_view', value: 'Property View', langCode: 'en'), Phrase(id: 'phid_k_sub_ppt_feat_view', value: 'المنظر المطل عليه  العقار', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_ppt_feat_floors', value: 'Number of Floor', langCode: 'en'), Phrase(id: 'phid_k_sub_ppt_feat_floors', value: 'الدور', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_ppt_feat_age', value: 'Building Age', langCode: 'en'), Phrase(id: 'phid_k_sub_ppt_feat_age', value: 'عمر المنشأ', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_ppt_feat_finishing', value: 'Finishing level', langCode: 'en'), Phrase(id: 'phid_k_sub_ppt_feat_finishing', value: 'مستوى التشطيب', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_ppt_feat_indoor', value: 'Indoor Features', langCode: 'en'), Phrase(id: 'phid_k_sub_ppt_feat_indoor', value: 'خواص داخلية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_ppt_feat_amenities', value: 'Amenities', langCode: 'en'), Phrase(id: 'phid_k_sub_ppt_feat_amenities', value: 'منشآت خدمية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_ppt_feat_services', value: 'Additional Services', langCode: 'en'), Phrase(id: 'phid_k_sub_ppt_feat_services', value: 'خدمات إضافية', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_ppt_price_sellEGY', value: 'Property selling price (EGP)', langCode: 'en'), Phrase(id: 'phid_k_sub_ppt_price_sellEGY', value: 'سعر بيع العقار (جم)', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_ppt_price_payments', value: 'Payment Method', langCode: 'en'), Phrase(id: 'phid_k_sub_ppt_price_payments', value: 'طريقة السداد', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_ppt_price_duration', value: 'Installments Duration', langCode: 'en'), Phrase(id: 'phid_k_sub_ppt_price_duration', value: 'فترة الأقساط', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_ppt_price_rentalType', value: 'Rental Type', langCode: 'en'), Phrase(id: 'phid_k_sub_ppt_price_rentalType', value: 'نوع الإيجار', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_ppt_price_rentValue', value: 'Rental Price', langCode: 'en'), Phrase(id: 'phid_k_sub_ppt_price_rentValue', value: 'سعر إيجار العقار', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_price', value: 'Product price', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_price', value: 'سعر المنتج', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_priceType', value: 'Price type', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_priceType', value: 'نوع السعر', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_rentType', value: 'Rent type', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_rentType', value: 'نوع الإيجار', langCode: 'ar'),
  Phrase(id: 'phid_k_sub_prd_price_unit', value: 'Measurement unit', langCode: 'en'), Phrase(id: 'phid_k_sub_prd_price_unit', value: 'وحدة القياس', langCode: 'ar'),

];
