// library authing;
// // -----------------------------------------------------------------------------
// import 'package:bldrs_theme/bldrs_theme.dart';
// import 'package:extension_google_sign_in_as_googleapis_auth/extension_google_sign_in_as_googleapis_auth.dart';
// import 'package:filers/filers.dart';
// import 'package:firebase_auth/firebase_auth.dart';
// import 'package:firebase_ui_auth/firebase_ui_auth.dart' as fireUI;
// import 'package:firebase_ui_oauth_apple/firebase_ui_oauth_apple.dart';
// import 'package:firebase_ui_oauth_facebook/firebase_ui_oauth_facebook.dart';
// import 'package:firebase_ui_oauth_google/firebase_ui_oauth_google.dart';
// import 'package:flutter/foundation.dart';
// import 'package:flutter_facebook_auth/flutter_facebook_auth.dart';
// import 'package:google_sign_in/google_sign_in.dart';
// import 'package:googleapis_auth/googleapis_auth.dart'; // as gapis;
// import 'package:mapper/mapper.dart';
// import 'package:sign_in_with_apple/sign_in_with_apple.dart';
// import 'package:space_time/space_time.dart';
// import 'package:stringer/stringer.dart';
// import 'package:flutter/material.dart';
// import 'package:super_box/super_box.dart';
// // -----------------------------------------------------------------------------
// export 'package:firebase_auth/firebase_auth.dart';
// // -----------------------------------------------------------------------------
// /// METHODS
// part 'methods/a_authing.dart';
// part 'methods/b_email_authing.dart';
// part 'methods/c_google_authing.dart';
// part 'methods/d_facebook_authing.dart';
// part 'methods/e_apple_authing.dart';
// // --------------------
// /// HELPERS
// part 'helpers/auth_error.dart';
// part 'helpers/auth_blog.dart';
// // --------------------
// /// MODELS
// part 'models/sign_in_method.dart';
// part 'models/auth_model.dart';
// part 'models/social_keys.dart';
// // --------------------
// /// WIDGETS
// part 'buttons/auth_button_box.dart';
// part 'buttons/social_auth_button.dart';
// // -----------------------------------------------------------------------------
